### ISSUE TITLE
Add support for LeakyReLU.

### ISSUE THREAD

**Issue by devansh20la** [openvinotoolkit/nncf#1001]
Filter pruning skips all convolutions that are followed by leaky relu e.g
```
model = nn.Sequential(
            nn.Conv2d(3, 128, kernel_size=3),
            nn.LeakyReLU()
)
```

**Comment by daniil-lyakhov** [comment]
Greetings, @devansh20la!

Thanks for your finding! Looks like leakyrelu operation is missed in torch pruning operation set. I'll fix it soon
