### ISSUE TITLE
infinite hang of 'from nncf.torch import create_compressed_model'

### ISSUE THREAD

**Issue by huntkao** [openvinotoolkit/nncf#1033]
When I do these:
```
import torch
import nncf
from nncf.torch import create_compressed_model

```
it always hang at the last command. No response at all.
What did I wrong, please? Thanks.
------------------- -------
My environment:
python  3.8.10
CUDA 10.1

Package             Version
attrs               21.2.0 
importlib-resources 5.4.0  
jsonschema          4.2.1  
jstyleson           0.0.2  
networkx            2.6.3  
numpy               1.21.4 
pip                 20.0.2 
pkg-resources       0.0.0  
pyrsistent          0.18.0 
setuptools          44.0.0 
texttable           1.6.4  
torch               1.9.1  
typing-extensions   4.0.1  
wheel               0.34.2 
zipp                3.6.0

**Comment by huntkao** [comment]
I found the reason.
There are lock files in ~/.cache/torch_extensions/...
which causes  torch.util.import wait forever.

**Comment by billionfish** [comment]
ps windows on AppData\Local\torch_extensions\torch_extensions\Cache
