### ISSUE TITLE
parameter count and model size are still the same.

### ISSUE THREAD

**Issue by huntkao** [openvinotoolkit/nncf#1038]
After filter pruning and fine tuning, we can see NNCF works alright.
But the parameter count and model size of the saved pytorch model are the same as those of the original's.
How can I obtain the compressed model (new architecture and weights, etc) in Pytorch format (.pth)?

Thank you very much.

**Comment by AlexKoff88** [comment]
The actual pruning (removal of zeroed filters) happens at the model conversion step to OpenVINO IR.
@daniil-lyakhov, please provide guidance on how to use OpenVINO to improve the performance and decrease model size.

**Comment by kartikp7** [comment]
I have the same question. I am running nncf tf on a linux server on my ML pipeline. Is there a way for me to identify what filters from my original model were pruned in the compressed model (I have both the .h5 files)? Do I need to install OpenVINO on the server?

**Comment by daniil-lyakhov** [comment]
Greetings, @huntkao, @kartikp7!

Pruning algorithm working in the following way:
NNCF is wrapping model to enable pruning aware training. The output of pruning algorithm is wrapped model contains all its weights + convolution layers kernel masks with information which layer channel should be pruned and which shouldn't.

To figure out which channels are going to be pruned please refer to pruning algo statistics:
[Example of retrieving statistic from classification sample](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/main.py#L248-L249)
[Docstring on pruning statistics](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/common/pruning/statistics.py#L98-L106)
(Note:  coming [PR](https://github.com/openvinotoolkit/nncf/pull/1030) should make pruning statistics more clear)

To actually prune obtained model one should
* Install [openvino-dev](https://pypi.org/project/openvino-dev/)
For example, to install openvino with onnx prerequirement one should do
`$pip install openvino-dev[onnx]`
* Convert your model to IR format by [model optimizer tool](https://docs.openvino.ai/latest/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html)
* Explicitly call pruning transformation:
```
$python pruning_transformation.py path/to/input/ir/model.xml path/to/output/model_name
```
pruning_transformation.py:
```
import sys

from openvino.inference_engine import IECore
from openvino.offline_transformations import ApplyPruningTransformation

print(f'input model path {sys.argv[1]} \n output model path {sys.argv[2]}.xml \n output model weights {sys.argv[2]}.bin')

ie = IECore()
net = ie.read_network(sys.argv[1])

ApplyPruningTransformation(net)
net.serialize(sys.argv[2] + '.xml', sys.argv[2] + '.bin')
print('Done!')
```  

The simplest way to check your model was pruned is to
* compare sizes of `.bin` parts of original and pruned model
* benchmark model performance by [benchmark tool](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html)

In case something goes wrong and pruning transformation didn't change the size of model please contact me. 

Note: implicit call of pruning transformation by special model optimizer CLI feature is coming, I'll inform you when this feature will be available.

**Comment by huntkao** [comment]
Hi, @daniil-lyakhov ,

   Million thanks for your guidance. I tried the approach on nncf-develop and **it works.** 

   Is it possible to export the **compressed** model to Pytorch .pth format directly other than ONNX? 
   
   Thanks again.

**Comment by daniil-lyakhov** [comment]
Welcome, @huntkao!

To export pytorch model checkpoint **with** compression (with additional mask layers) you can make it as it showed in [nncf classification sample](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/main.py#L334-L344). After that you can use this checkpoint to load compressed model, please see the classification sample again for details.

To clarify: you can actually remove weights from your model only after openvino model optimizer IR conversion, in the IR format. The api for removing weights directly from torch model was deprecated.

**Comment by huntkao** [comment]
If I want to make the weight-removing API back by myself, do you have any suggestion? Thx.

**Comment by daniil-lyakhov** [comment]
You can try [this](https://github.com/openvinotoolkit/nncf/blob/2f231aa3903a286dafaa15eaae54758e2a2f346b/nncf/torch/pruning/operations.py#L318-L350), but on your own risks. This functionality isn't tested and updated since a while, and it could be some problems. 

If openvino runtime is fitting your requirements I recommend you to try it. It won't only remove weights but should speedup you model overall due to internal optimizations

**Comment by huntkao** [comment]
The output ONNX file by **nncf-release-v200**  is compressed model.
The output ONNX file by **nncf-develop** can be actually pruned by the steps provided by @daniil-lyakhov .
I think this issue could be closed. Thanks.

**Comment by mjw123bs** [comment]
> Greetings, @huntkao, @kartikp7!
> 
> Pruning algorithm working in the following way: NNCF is wrapping model to enable pruning aware training. The output of pruning algorithm is wrapped model contains all its weights + convolution layers kernel masks with information which layer channel should be pruned and which shouldn't.
> 
> To figure out which channels are going to be pruned please refer to pruning algo statistics: [Example of retrieving statistic from classification sample](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/main.py#L248-L249) [Docstring on pruning statistics](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/common/pruning/statistics.py#L98-L106) (Note: coming [PR](https://github.com/openvinotoolkit/nncf/pull/1030) should make pruning statistics more clear)
> 
> To actually prune obtained model one should
> 
>     * Install [openvino-dev](https://pypi.org/project/openvino-dev/)
>       For example, to install openvino with onnx prerequirement one should do
>       `$pip install openvino-dev[onnx]`
> 
>     * Convert your model to IR format by [model optimizer tool](https://docs.openvino.ai/latest/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html)
> 
>     * Explicitly call pruning transformation:
> 
> 
> ```
> $python pruning_transformation.py path/to/input/ir/model.xml path/to/output/model_name
> ```
> 
> pruning_transformation.py:
> 
> ```
> import sys
> 
> from openvino.inference_engine import IECore
> from openvino.offline_transformations import ApplyPruningTransformation
> 
> print(f'input model path {sys.argv[1]} \n output model path {sys.argv[2]}.xml \n output model weights {sys.argv[2]}.bin')
> 
> ie = IECore()
> net = ie.read_network(sys.argv[1])
> 
> ApplyPruningTransformation(net)
> net.serialize(sys.argv[2] + '.xml', sys.argv[2] + '.bin')
> print('Done!')
> ```
> 
> The simplest way to check your model was pruned is to
> 
>     * compare sizes of `.bin` parts of original and pruned model
> 
>     * benchmark model performance by [benchmark tool](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html)
> 
> 
> In case something goes wrong and pruning transformation didn't change the size of model please contact me.
> 
> Note: implicit call of pruning transformation by special model optimizer CLI feature is coming, I'll inform you when this feature will be available.

Hello, when I convert my model to IR format according to the method you provided, I report the following error：
`Traceback (most recent call last):
  File "/home/a504/mjw/Code/Compress_model/VGGNet_ML_Compress/convert_model.py", line 42, in <module>
    ov_model = ov.convert_model(model)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert.py", line 101, in convert_model
    ov_model, _ = _convert(cli_parser, params, True)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py", line 534, in _convert
    raise e
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py", line 476, in _convert
    ov_model = driver(argv, {"conversion_parameters": non_default_params})
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py", line 227, in driver
    ov_model = moc_emit_ir(prepare_ir(argv), argv)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py", line 177, in prepare_ir
    ov_model = moc_pipeline(argv, moc_front_end)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/moc_frontend/pipeline.py", line 244, in moc_pipeline
    ov_model = moc_front_end.convert(input_model)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/frontend.py", line 18, in convert
    converted_model = super().convert(model)
openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at src/frontends/pytorch/src/frontend.cpp:141:
FrontEnd API failed with OpConversionFailure:
Model wasn't fully converted. Failed operations detailed log:
-- prim::Constant with a message:
Exception happened during conversion of operation prim::Constant with schema (no schema)
TypeError: numpy() takes no keyword arguments

At:
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/pytorch/utils.py(70): torch_tensor_to_ov_const
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/pytorch/utils.py(87): ivalue_to_constant
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/pytorch/ts_decoder.py(328): as_constant
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/pytorch/ts_decoder.py(228): visit_subgraph
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/frontend.py(18): convert
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/moc_frontend/pipeline.py(244): moc_pipeline
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py(177): prepare_ir
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py(227): driver
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py(476): _convert
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert.py(101): convert_model
  /home/a504/mjw/Code/Compress_model/VGGNet_ML_Compress/convert_model.py(42): <module>
`
How to solve the problem?
My code is shown below：
`import openvino as ov
import torch
from torchvision import datasets, models, transforms
import torch.nn as nn

model = models.vgg16(weights="IMAGENET1K_V1")

for p in model.features.parameters():  
    p.requires_grad = True  

num_input = model.classifier[6].in_features 
feature_model = list(model.classifier.children())
feature_model.pop()
feature_model.append(nn.Linear(num_input, 42))
model.classifier = nn.Sequential(*feature_model)

prepare input_data
input_data = torch.rand(16, 3, 227, 227)

ov_model = ov.convert_model(model)

###### Option 1: Save to OpenVINO IR:

# save model to OpenVINO IR for later use
ov.save_model(ov_model, 'model.xml')`

**Comment by mjw123bs** [comment]
> Greetings, @huntkao, @kartikp7!
> 
> Pruning algorithm working in the following way: NNCF is wrapping model to enable pruning aware training. The output of pruning algorithm is wrapped model contains all its weights + convolution layers kernel masks with information which layer channel should be pruned and which shouldn't.
> 
> To figure out which channels are going to be pruned please refer to pruning algo statistics: [Example of retrieving statistic from classification sample](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/main.py#L248-L249) [Docstring on pruning statistics](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/common/pruning/statistics.py#L98-L106) (Note: coming [PR](https://github.com/openvinotoolkit/nncf/pull/1030) should make pruning statistics more clear)
> 
> To actually prune obtained model one should
> 
>     * Install [openvino-dev](https://pypi.org/project/openvino-dev/)
>       For example, to install openvino with onnx prerequirement one should do
>       `$pip install openvino-dev[onnx]`
> 
>     * Convert your model to IR format by [model optimizer tool](https://docs.openvino.ai/latest/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html)
> 
>     * Explicitly call pruning transformation:
> 
> 
> ```
> $python pruning_transformation.py path/to/input/ir/model.xml path/to/output/model_name
> ```
> 
> pruning_transformation.py:
> 
> ```
> import sys
> 
> from openvino.inference_engine import IECore
> from openvino.offline_transformations import ApplyPruningTransformation
> 
> print(f'input model path {sys.argv[1]} \n output model path {sys.argv[2]}.xml \n output model weights {sys.argv[2]}.bin')
> 
> ie = IECore()
> net = ie.read_network(sys.argv[1])
> 
> ApplyPruningTransformation(net)
> net.serialize(sys.argv[2] + '.xml', sys.argv[2] + '.bin')
> print('Done!')
> ```
> 
> The simplest way to check your model was pruned is to
> 
>     * compare sizes of `.bin` parts of original and pruned model
> 
>     * benchmark model performance by [benchmark tool](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html)
> 
> 
> In case something goes wrong and pruning transformation didn't change the size of model please contact me.
> 
> Note: implicit call of pruning transformation by special model optimizer CLI feature is coming, I'll inform you when this feature will be available.

Hello, when I convert my model to IR format according to the method you provided, I report the following error：
`Traceback (most recent call last):
  File "/home/a504/mjw/Code/Compress_model/VGGNet_ML_Compress/convert_model.py", line 42, in <module>
    ov_model = ov.convert_model(model)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert.py", line 101, in convert_model
    ov_model, _ = _convert(cli_parser, params, True)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py", line 534, in _convert
    raise e
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py", line 476, in _convert
    ov_model = driver(argv, {"conversion_parameters": non_default_params})
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py", line 227, in driver
    ov_model = moc_emit_ir(prepare_ir(argv), argv)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py", line 177, in prepare_ir
    ov_model = moc_pipeline(argv, moc_front_end)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/moc_frontend/pipeline.py", line 244, in moc_pipeline
    ov_model = moc_front_end.convert(input_model)
  File "/home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/frontend.py", line 18, in convert
    converted_model = super().convert(model)
openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at src/frontends/pytorch/src/frontend.cpp:141:
FrontEnd API failed with OpConversionFailure:
Model wasn't fully converted. Failed operations detailed log:
-- prim::Constant with a message:
Exception happened during conversion of operation prim::Constant with schema (no schema)
TypeError: numpy() takes no keyword arguments

At:
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/pytorch/utils.py(70): torch_tensor_to_ov_const
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/pytorch/utils.py(87): ivalue_to_constant
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/pytorch/ts_decoder.py(328): as_constant
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/pytorch/ts_decoder.py(228): visit_subgraph
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/frontend/frontend.py(18): convert
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/moc_frontend/pipeline.py(244): moc_pipeline
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py(177): prepare_ir
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py(227): driver
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert_impl.py(476): _convert
  /home/a504/mjw/envs/ML_Compress/lib/python3.8/site-packages/openvino/tools/ovc/convert.py(101): convert_model
  /home/a504/mjw/Code/Compress_model/VGGNet_ML_Compress/convert_model.py(42): <module>
`
How to solve the problem?
My code is shown below：
`import openvino as ov
import torch
from torchvision import datasets, models, transforms
import torch.nn as nn

model = models.vgg16(weights="IMAGENET1K_V1")

for p in model.features.parameters():  
    p.requires_grad = True  

num_input = model.classifier[6].in_features 
feature_model = list(model.classifier.children())
feature_model.pop()
feature_model.append(nn.Linear(num_input, 42))
model.classifier = nn.Sequential(*feature_model)

prepare input_data
input_data = torch.rand(16, 3, 227, 227)

ov_model = ov.convert_model(model)

###### Option 1: Save to OpenVINO IR:

# save model to OpenVINO IR for later use
ov.save_model(ov_model, 'model.xml')`
