### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by ZhaodaDu** [openvinotoolkit/nncf#1104]
> Traceback (most recent call last):
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/examples/torch/semantic_segmentation/main.py", line 34, in <module>
>     from examples.torch.semantic_segmentation.utils import loss_funcs
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/examples/torch/semantic_segmentation/utils/loss_funcs.py", line 19, in <module>
>     from examples.torch.common.models.segmentation.unet import center_crop
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/examples/torch/common/models/__init__.py", line 1, in <module>
>     from examples.torch.common.models.segmentation import *
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/examples/torch/common/models/segmentation/__init__.py", line 2, in <module>
>     from .icnet import *
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/examples/torch/common/models/segmentation/icnet.py", line 30, in <module>
>     from nncf.torch.utils import is_tracing_state
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/__init__.py", line 42, in <module>
>     from nncf.torch.binarization import algo as binarization_algo
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/binarization/algo.py", line 29, in <module>
>     from nncf.torch.algo_selector import PT_COMPRESSION_ALGORITHMS
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/algo_selector.py", line 20, in <module>
>     from nncf.torch.nncf_network import NNCFNetwork
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/nncf_network.py", line 70, in <module>
>     from nncf.torch.quantization.layers import QUANTIZATION_MODULES
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/quantization/__init__.py", line 14, in <module>
>     from . import layers
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/quantization/layers.py", line 31, in <module>
>     from nncf.torch.quantization.quantize_functions import symmetric_quantize, asymmetric_quantize, \
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/quantization/quantize_functions.py", line 18, in <module>
>     from .extensions import QuantizedFunctionsCPU, QuantizedFunctionsCUDA
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/quantization/extensions.py", line 65, in <module>
>     QuantizedFunctionsCUDA = QuantizedFunctionsCUDALoader.load()
>   File "/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/quantization/extensions.py", line 59, in load
>     verbose=False)
>   File "/home/pan/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 997, in load
>     keep_intermediates=keep_intermediates)
>   File "/home/pan/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1202, in _jit_compile
>     with_cuda=with_cuda)
>   File "/home/pan/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1300, in _write_ninja_file_and_build_library
>     error_prefix="Error building extension '{}'".format(name))
>   File "/home/pan/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
>     raise RuntimeError(message) from e
> RuntimeError: Error building extension 'quantized_functions_cuda': [1/2] :/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=quantized_functions_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/extensions/include -isystem /home/pan/.local/lib/python3.6/site-packages/torch/include -isystem /home/pan/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/pan/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/pan/.local/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/extensions/src/quantization/cuda/functions_cuda_impl.cu -o functions_cuda_impl.cuda.o 
> FAILED: functions_cuda_impl.cuda.o 
> :/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=quantized_functions_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/extensions/include -isystem /home/pan/.local/lib/python3.6/site-packages/torch/include -isystem /home/pan/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/pan/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/pan/.local/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/extensions/src/quantization/cuda/functions_cuda_impl.cu -o functions_cuda_impl.cuda.o 
> /bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
> ninja: build stopped: subcommand failed.
> 
> 
> Process finished with exit code 1

I have this error when I train the model.

1. python 3.6 
2. pytorch 1.7.1
3. ninja 1.10.2
4. nvcc 10.2 

I have also tried :

1. python 3.8 
2. pytorch 1.9.1
3. ninja 1.10.2 
4. nvcc 10.2 & 11.3

and have the same error

**Comment by ljaljushkin** [comment]
Hello @ZhaodaDu!

It seems like you have multiple versions of cuda installed and it fails to find nvcc in the default location - /usr/local/cuda/bin/nvcc

Try to explicitly specify path to nvcc.
There're multiple ways of doing this:
- export CUDA_HOME="/usr/local/cuda-`your cuda version`"
- export PATH="$PATH:/usr/local/cuda-`your cuda version`/bin"

**Comment by ZhaodaDu** [comment]
> Hello @ZhaodaDu!
> 
> It seems like you have multiple versions of cuda installed and it fails to find nvcc in the default location - /usr/local/cuda/bin/nvcc
> 
> Try to explicitly specify path to nvcc. There're multiple ways of doing this:
> 
> * export CUDA_HOME="/usr/local/cuda-`your cuda version`"
> * export PATH="$PATH:/usr/local/cuda-`your cuda version`/bin"

I have added them in my ~/.bashrc  but the it still has the same error.

> RuntimeError: Error building extension 'quantized_functions_cuda': [1/2] :/usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=quantized_functions_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/extensions/include -isystem /home/pan/.local/lib/python3.8/site-packages/torch/include -isystem /home/pan/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/pan/.local/lib/python3.8/site-packages/torch/include/TH -isystem /home/pan/.local/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/extensions/src/quantization/cuda/functions_cuda_impl.cu -o functions_cuda_impl.cuda.o 
> FAILED: functions_cuda_impl.cuda.o 
> :/usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=quantized_functions_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/extensions/include -isystem /home/pan/.local/lib/python3.8/site-packages/torch/include -isystem /home/pan/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/pan/.local/lib/python3.8/site-packages/torch/include/TH -isystem /home/pan/.local/lib/python3.8/site-packages/torch/include/THC -isystem :/usr/local/cuda-10.2/include -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/pan/zhaoda_code_important/zhaoda_code/nncf-develop/nncf/torch/extensions/src/quantization/cuda/functions_cuda_impl.cu -o functions_cuda_impl.cuda.o 
> /bin/sh: 1: :/usr/local/cuda-10.2/bin/nvcc: not found
> ninja: build stopped: subcommand failed.

my bashrc is :

> export PATH="$PATH:/usr/local/cuda-10.2/bin"
> export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-10.2/lib64/"
> export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/cuda-10.2/lib64"
> export PATH="/usr/local/mongodb/bin:$PATH"
> export CUDA_HOME="/usr/local/cuda-10.2"

and Im sure there exist a nvcc file .
should I reinstall my cuda and cudnn?

**Comment by alalek** [comment]
> `/bin/sh: 1: :/usr/local/cuda-10.2/bin/nvcc: not found`
> `:/usr/local/cuda-10.2/bin/nvcc`

> Im sure there exist a nvcc file

Need to investigate on which stage it gets the colon ":" prefix.

**Comment by xiexu666** [comment]
@ZhaodaDu Did you solve it? I had the same problem.

**Comment by ZhaodaDu** [comment]
@xiexu666 I haven't solved the problem, have you?

**Comment by xiexu666** [comment]
> @xiexu666 I haven't solved the problem, have you?
I created a new environment and sovle it.
ubuntu 20.04 
cuda 11.1
torch 1.9.1
