### ISSUE TITLE
Saved model or Darknet weights 

### ISSUE THREAD

**Issue by AyaNasser96** [openvinotoolkit/nncf#1121]
Hello, 
My custom yolov4 model was darknet, then I convert it to TF (Saved model) to be able to convert it to IR successfully, 
Now could I use nncf with that TF (Saved model) ? because I notice you used the H5 weight file only.
Thanks in advanced

**Comment by andrey-churkin** [comment]
@AyaNasser96 thanks for your question! The NNCF TensorFlow doesn't support models in the SavedModel format yet. For the quantization aware training, we need a python code of the model and a training pipeline. As an alternative, I suggest using our tool the [Post-Training Optimization Tool](https://docs.openvino.ai/latest/pot_README.html) which works directly with IR.

**Comment by andrey-churkin** [comment]
@AyaNasser96 I closed issue. Feel free to reopen if you have any question.
