### ISSUE TITLE
Requirements incompatible with M1 Mac

### ISSUE THREAD

**Issue by dreaquil** [openvinotoolkit/nncf#1142]
Currently when installing the requirements on an M1 Mac, there are certain packages (e.g numpy) for which the current version cannot be found or does not work.

I propose changing `numpy~=1.19.2` to `numpy>=1.22.3` in setup.py.

This is related to https://github.com/openvinotoolkit/anomalib/issues/150

**Comment by AlexKoff88** [comment]
I would even remove a connection to any numpy version from the user's requirements. Internal validation can use a fixed version for reproducibility. @vshampor, @alexsu52.

**Comment by MaximProshin** [comment]
@vshampor , please take a look. Any suggestions how we could overcome it?

**Comment by alexsu52** [comment]
@dreaquil The following PR #1220 should fix the issue. Stay tuned!

**Comment by vshampor** [comment]
Numpy requirement is now at `numpy>=1.19.1, <1.24`.
