### ISSUE TITLE
Int16 or Int8x16 Quantization 

### ISSUE THREAD

**Issue by schmiph2** [openvinotoolkit/nncf#1165]
Hi everyone

As the literature indicates, 8-bit quantization is barely sufficient for many LSTM/GRU applications. Do you support 16-bit quantization (including deployment with OpenVINO)? Another approach is to quantize the weights with 8 bits and quantize the activations with 16 bits. Do you support this kind of quantization?

**Comment by vinnamkim** [comment]
Hi, sorry for the late response.

For your first question, to my knowledge, when inferencing DNN, if you only convert the fp32 weights to 16bit and conduct all operations in fp16, it almost preserves the original accuracy without any special quantization technique.
OpenVINO supports fp16 inference. Please refer to https://docs.openvino.ai/latest/openvino_docs_MO_DG_FP16_Compression.html.

For your second question, keeping the weights with 8 bits and inferencing in fp16 precision, I don't exactly know whether OpenVINO supports this type of operation.
It would be better to open a question in OpenVINO runtime repository https://github.com/openvinotoolkit/openvino/issues for expertise on this problem.

Sorry for inconvenience.

**Comment by schmiph2** [comment]
Hi vinnamkim

Thank you very much for your answer! Sorry, my question was a bit imprecise. I meant int16 quantization and not fp16. Do you support int16 quantization and/or mixed int16/int8 quantization? Thank you for your help!

**Comment by vinnamkim** [comment]
As you see in our mixed-precision examples, you can give arbitrary bit-widths to NNCF (maybe you could give 16 for activations and 8 for weights):
https://github.com/openvinotoolkit/nncf/blob/d351ad617d4cab6ba0bcf7c52b0c144999725d16/examples/torch/classification/configs/mixed_precision/mobilenet_v2_imagenet_mixed_int_manual.json#L28-L37

This will be propagated to OpenVINO IR's [FakeQuantize::levels](https://docs.openvino.ai/latest/classov_1_1op_1_1v0_1_1FakeQuantize.html#doxid-classov-1-1op-1-1v0-1-1-fake-quantize).
However, I recommend opening the issue in the OpenVINO repository to know exactly how this quantization setup will be executed on the hardware level.

**Comment by schmiph2** [comment]
Perfect, thank you for your help! I will check it out.
