### ISSUE TITLE
how to export torch.fx converted int8 model to onnx?

### ISSUE THREAD

**Issue by lucasjinreal** [openvinotoolkit/nncf#1167]
Hi, since pytorch official released an easy and controlable quantization workflow with torch.fx

However, seems there still a gap from torch supported and user wanted. Just wonder, if nncf would support export fx converted int8 model to onnx? So that we can make full use of pytorch and nncf for deployment.

**Comment by vinnamkim** [comment]
Hi, sorry for the late response.
There is currently no roadmap for torch.fx support. We will let you know if there are any changes. Thank you!

**Comment by MaximProshin** [comment]
@vshampor , FYI, it's related to Torch.FX

**Comment by avitial** [comment]
Ref. 138686

**Comment by alexsu52** [comment]
NNCF provides compression capabilities, but this issue addressed to PyTorch export functionality. Your best option is to open an issue with PyTorch.
