### ISSUE TITLE
export .pth model to onnx

### ISSUE THREAD

**Issue by GitForKriti** [openvinotoolkit/nncf#1170]
Hi,

How to export a quantized .pth model to onnx?

**Comment by schmidtp1** [comment]
i think you can just follow the steps in the readme: https://github.com/openvinotoolkit/nncf/blob/develop/README.md?plain=1#L74

**Comment by jpablomch** [comment]
Hi, 

You can use the `export_model` method of the compression controller: 

`compression_ctrl.export_model(int8_onnx_path)`

**Comment by alexsu52** [comment]
Please, reopen the issue if you still have questions.
