### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by sankhujwal** [openvinotoolkit/nncf#1178]
Hi ,

While validating pytorch image classification model, I am following below command:

python main.py -m test --config=configs/quantization/mobilenet_v2_imagenet_int8.json --resume ../../results/quantization/mobilenet_v2_int8/mobilenet_v2_imagenet_int8/2022-05-11__17-28-50/intermediate_checkpoints/epoch_5.pth

ERROR:
 patching unique_dim since it is missing in this version of PyTorch
  warnings.warn("Not patching {} since it is missing in this version of PyTorch".format(op_name))
batch_size                 : 64
batch_size_init            : None
batch_size_val             : None
checkpoint_save_dir        : runs/mobilenet_v2_imagenet_int8/2022-05-12__17-58-19
compression                : {'algorithm': 'quantization', 'initializer': {'range': {'num_init_samples': 2560}}}
config                     : configs/quantization/mobilenet_v2_imagenet_int8.json
cpu_only                   : False
current_gpu                : None
dataset                    : None
dataset_dir                : None
device                     : cuda
disable_compression        : False
dist_backend               : nccl
dist_url                   : tcp://127.0.0.1:8899
distributed                : False
epochs                     : 5
execution_mode             : gpu_dataparallel
gpu_id                     : None
imshow_batch               : False
input_info                 : {'sample_size': [2, 3, 224, 224]}
intermediate_checkpoints_path: runs/mobilenet_v2_imagenet_int8/2022-05-12__17-58-19/intermediate_checkpoints
log_dir                    : runs/mobilenet_v2_imagenet_int8/2022-05-12__17-58-19
metrics_dump               : None
mlflow                     : <examples.torch.common.utils.SafeMLFLow object at 0x7fa148ec3550>
mode                       : ['test']
model                      : mobilenet_v2
multiprocessing_distributed: False
name                       : mobilenet_v2_imagenet_int8
nncf_config                : {'model': 'mobilenet_v2', 'pretrained': True, 'input_info': {'sample_size': [2, 3, 224, 224]}, 'num_classes': 1000, 'batch_size': 64, 'epochs': 5, 'optimizer': {'type': 'Adam', 'base_lr': 1e-05, 'schedule_type': 'multistep', 'steps': [5]}, 'compression': {'algorithm': 'quantization', 'initializer': {'range': {'num_init_samples': 2560}}}, 'log_dir': 'runs/mobilenet_v2_imagenet_int8/2022-05-12__17-58-19'}
num_classes                : 1000
optimizer                  : {'type': 'Adam', 'base_lr': 1e-05, 'schedule_type': 'multistep', 'steps': [5]}
pretrained                 : True
print_freq                 : 10
print_step                 : False
rank                       : 0
resuming_checkpoint_path   : ../../results/quantization/mobilenet_v2_int8/mobilenet_v2_imagenet_int8/2022-05-11__17-28-50/intermediate_checkpoints/epoch_5.pth
save_freq                  : 5
seed                       : None
start_epoch                : 0
target_device              : None
tb                         : <torch.utils.tensorboard.writer.SummaryWriter object at 0x7fa148ec3590>
test_every_n_epochs        : 1
to_onnx                    : None
weights                    : None
workers                    : 4
world_size                 : 1
Traceback (most recent call last):
  File "main.py", line 698, in <module>
    main(sys.argv[1:])
  File "main.py", line 134, in main
    start_worker(main_worker, config)
  File "/home/ujwala/Projects/Static_Hand_Gesture/nncf/examples/torch/common/execution.py", line 106, in start_worker
    main_worker(current_gpu=None, config=config)
  File "main.py", line 177, in main_worker
    train_dataset, val_dataset = create_datasets(config)
  File "main.py", line 451, in create_datasets
    val_dataset = get_dataset(dataset_config, config, val_transform, is_train=False)
  File "main.py", line 363, in get_dataset
    return datasets.ImageFolder(osp.join(config.dataset_dir, prefix), transform)
  File "/home/ujwala/.virtualenvs/NNCF/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Could you please help me to resolve this issue.

**Comment by vinnamkim** [comment]
Hi, Sorry for the late reply.

```
python main.py -m test --config=configs/quantization/mobilenet_v2_imagenet_int8.json --resume ../../results/quantization/mobilenet_v2_int8/mobilenet_v2_imagenet_int8/2022-05-11__17-28-50/intermediate_checkpoints/epoch_5.pth
```

Looking at your command, it seems that you didn't give a dataset path as an argument.

https://github.com/openvinotoolkit/nncf/blob/e85a695da95b202b4579ea11f880f1b14bfcda2e/examples/torch/classification/README.md?plain=1#L42-L48

Could you please add the valid dataset path to `--data`?

**Comment by sankhujwal** [comment]
@vinnamkim , Thank you issue got resolved.
