### ISSUE TITLE
TypeError: create_model() missing 1 required positional argument: 'resuming_checkpoint'

### ISSUE THREAD

**Issue by Praveen-24-mvp** [openvinotoolkit/nncf#1194]
Hi 

I am just trying to replicate the PyTorch Object Detection samples while running the object detection sample receiving an error like

error --- TypeError: create_model() missing 1 required positional argument: 'resuming_checkpoint'

![nncf-err (1)](https://user-images.githubusercontent.com/85551893/173315085-8d50d126-51c9-4f79-a93a-7144c1eb9d01.png)

Could somebody help me to fix this issue... 
Thanks in Advance :smile:

**Comment by vinnamkim** [comment]
Would you let me know the command that you tried?

**Comment by Praveen-24-mvp** [comment]
> Would you let me know the command that you tried?

python3 main.py --mode=test --config=configs/ssd300_vgg_voc_int8.json --data=/VOCtrainval_11-May-2012  --disable-compression

**Comment by sungchul2** [comment]
I tried to reproduce this issue, but I cannot show any problem.
`create_model` was changed with [this commit](https://github.com/openvinotoolkit/nncf/commit/9ca51e28e6fec0b7e15928f6a2f968ade329dc8c).
I'd like to know what commit you use and could you check that `create_model` has `resuming_checkpoint` arg?
