### ISSUE TITLE
Symmetric Quantization formula 

### ISSUE THREAD

**Issue by linhdb-2149** [openvinotoolkit/nncf#1230]
Are quantization formulas (specially symmetric quantization formula) the same as reported in paper?
https://arxiv.org/pdf/2002.08679.pdf

Paper:
![image](https://user-images.githubusercontent.com/61034772/179893576-c6875076-59be-4a11-bf92-5a26532ec727.png)

Docs:
https://github.com/openvinotoolkit/nncf/blob/4c7a0045abd557af13eb9b6386f88f5d5d30a2ff/docs/compression_algorithms/Quantization.md
![image](https://user-images.githubusercontent.com/61034772/179893642-5390610c-7884-4fd7-8c58-c76eca7d6145.png)

According to the paper, there are no rescale ($*\frac{scale}{levelhigh}$) after rounding. Furthermore, the multiplication factor of input should be reverse due to $s=\frac{q_{max} }{scale}$

Please have a look,
Thank you

**Comment by linhdb-2149** [comment]
I also find out the formula not consistent with nncf according to intellabs
https://intellabs.github.io/distiller/algo_quantization.html

**Comment by vinnamkim** [comment]
Hi @linhdb-2149,

This is our symmetric quantization forward function for CPU.
https://github.com/openvinotoolkit/nncf/blob/13cc15e6560985606abfd55086242d9f7687d6dd/nncf/torch/extensions/src/quantization/cpu/functions_cpu.cpp#L12-L19
You can see our implementation multiplying `s` = $\frac{q_{max}}{scale}$ ($q_{max}$ = `levels - 1` and $scale$ = `input_range`) to the real value input tensor `input`. So, our real implementation are doing $s * r$ to quantize the input.

Thank you
