### ISSUE TITLE
Use pretrained TCN model in nncf

### ISSUE THREAD

**Issue by AmanGoyal99** [openvinotoolkit/nncf#1278]
Use pretrained TCN model in nncf to create compression version of it

**Comment by MaximProshin** [comment]
@AmanGoyal99 , the issue description is unclear. Please provide more details about it.

**Comment by ljaljushkin** [comment]
@AmanGoyal99 is the mentioned issue with TCN resolved in https://github.com/openvinotoolkit/nncf/issues/1308?
Can we close the current issue?

**Comment by ljaljushkin** [comment]
Closing the issue since no details has been provided.
