### ISSUE TITLE
Support for Pytorch native nn.MultiheadAttention

### ISSUE THREAD

**Issue by vuiseng9** [openvinotoolkit/nncf#1285]
PyTorch has a native module now for Multi-head self-attention (MHA). In the past, users have been implementing MHA by using existing ```nn.Linear``` for feature projection in the layer. NNCFNetwork has no issue with this implementation since ```nn.Linear``` will be patched automatically to ```NNCFLinear```. However, in the native ```nn.MultiheadAttention``` ([see here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/activation.py#L887-L987)), it is implemented via ```nn.parameter```, per my understanding, this is not handled by NNCF. 

The current impact is that [out-of-the-box Vision Transformer](https://pytorch.org/vision/0.13/models.html#table-of-all-available-classification-weights) by TorchVision cannot be wrapped completely by NNCF. Below shows that only the MLP/FFNN of transformer block (EncoderBlock) has their layered swapped but not self-attention.

Original:
```
VisionTransformer(
  (conv_proj): Conv2d(3, 768, kernel_size=(32, 32), stride=(32, 32))
  (encoder): Encoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (layers): Sequential(
      (encoder_layer_0): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
        )
        (dropout): Dropout(p=0.0, inplace=False)
        (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (mlp): MLPBlock(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate=none)
          (2): Dropout(p=0.0, inplace=False)
          (3): Linear(in_features=3072, out_features=768, bias=True)
          (4): Dropout(p=0.0, inplace=False)
        )
      )
```

NNCFNetwork:
```
NNCFNetwork(
  (nncf_module): VisionTransformer(
    (conv_proj): NNCFConv2d(
      3, 768, kernel_size=(32, 32), stride=(32, 32)
      (pre_ops): ModuleDict()
      (post_ops): ModuleDict()
    )
    (encoder): Encoder(
      (dropout): Dropout(p=0.0, inplace=False)
      (layers): Sequential(
        (encoder_layer_0): EncoderBlock(
          (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
          *** (self_attention): MultiheadAttention(
          ***   (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
          *** )
          (dropout): Dropout(p=0.0, inplace=False)
          (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
          (mlp): MLPBlock(
            (0): NNCFLinear(
              in_features=768, out_features=3072, bias=True
              (pre_ops): ModuleDict()
              (post_ops): ModuleDict()
            )
            (1): GELU(approximate=none)
            (2): Dropout(p=0.0, inplace=False)
            (3): NNCFLinear(
              in_features=3072, out_features=768, bias=True
              (pre_ops): ModuleDict()
              (post_ops): ModuleDict()
            )
            (4): Dropout(p=0.0, inplace=False)
          )
        )
```

**Comment by vuiseng9** [comment]
@ljaljushkin @AlexKoff88 @vshampor

**Comment by ljaljushkin** [comment]
One possible option to support compression of this model is to create a `NNCFMultiheadAttention` wrapper. It would know everything about Q, K, V, O. It should simplify the task of tracing the graph and finding the transformer block, but at the same time it will require extra logic for setting and propagating compression. @daniil-lyakhov

**Comment by ljaljushkin** [comment]
The internals of this block still written using `linear` and `bmm` operations in case of not fast path, which is not active in the real cases (e.g. openclip). With https://github.com/openvinotoolkit/nncf/pull/1765 the block is represented as graph of operation that can be quantized and pruned separately as usual.
