### ISSUE TITLE
Revise quantization levels for weights

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/nncf#130]
The original problem is that QauntizeLinear and DequantizeLinear operation from ONNX do not support a shrunk range of quantization levels. So we can correctly export only levels of 256 for weights and activations. On the other hand 255 levels for weights were introduced to workaround the saturation issue on AVX targets. However, we do not know how it really affects accuracy and helps. 

My proposal is to have the full range of 2^bits levels but use a different workaround for saturations about which we know that it really works. It is about using 128 levels of 256 in the following way:

y = w*a = [sw * wq] * [sa * aq] * 1/sw * 1/sa =  [sw * wq / **2**] * [sa * aq] * **2**/sw * 1/sa

It means that we divide weights by the factor of 2.0 and adjust output scales of Dequatize operation (output_high and output_low in FQ) multiplying it by 2.0.

This is relevant for INT8 only!

We need to plan this for the next release. cc'ed @alexsu52, @kchechil

**Comment by AlexKoff88** [comment]
I would like to note that this is only for INT8 bits quantization. Lower bit-width should not be affected.

**Comment by AlexKoff88** [comment]
Definition of done:
- Implemented scaling of weights and scales in FQ operation
- Implemented proper export in FQ and Q/DQ
- E2E manual validation of MobileNet v2 on ImageNet and SSD-MobileNet on COCO (includes training in INT8, export to both FQ and Q/DQ and validation in OpenVINO)

**Comment by vshampor** [comment]
#225

**Comment by aleksei-kashapov** [comment]
See [PR](https://github.com/openvinotoolkit/nncf/pull/301)
