### ISSUE TITLE
package problem

### ISSUE THREAD

**Issue by liumingzhu6060** [openvinotoolkit/nncf#1321]
when I installed NNCF by pip install NNCF[torch] successfully, the command "from nncf.torch import create_compressed_model" is Stuck all the time，no response.

**Comment by vshampor** [comment]
See #1033. Basically - remove the torch cache folder in your system-specific location and try again.

**Comment by liumingzhu6060** [comment]
when i remove the torch cache, another problem occured ，“D:\Software\anaconda3\envs\NNCF-new\lib\site-packages\nncf\torch\dynamic_graph\patch_pytorch.py:163: UserWarning: Not patching unique_dim since it is missing in this version of PyTorch
  warnings.warn("Not patching {} since it is missing in this version of PyTorch".format(op_name))”

**Comment by liumingzhu6060** [comment]
when i remove the torch cache, another problem occured ，“D:\Software\anaconda3\envs\NNCF-new\lib\site-packages\nncf\torch\dynamic_graph\patch_pytorch.py:163: UserWarning: Not patching unique_dim since it is missing in this version of PyTorch
  warnings.warn("Not patching {} since it is missing in this version of PyTorch".format(op_name))”

**Comment by vshampor** [comment]
@liumingzhu6060 this is a warning, not a problem. If the original problem has been resolved, I suggest closing this issue.

**Comment by liumingzhu6060** [comment]
ok ,thanks
