### ISSUE TITLE
grad_output is not contiguous!

### ISSUE THREAD

**Issue by Alina9** [openvinotoolkit/nncf#1334]
Hello!

I use your lib for quantization of model. I have a warning during training : ``` WARNING:nncf:grad_output is not contiguous! ```
Please, explain to me meaning and the consequences of this. I see in your code, that you do grad_output is contiguous by force. 
Is it OK? Or have I got same mistake in my code?

Thank you!

<img width="851" alt="image" src="https://user-images.githubusercontent.com/14861005/196900208-18a4f198-4654-4e42-ade6-2f8559ecd4ee.png">

![image](https://user-images.githubusercontent.com/14861005/196900784-9c33ed56-c31c-433d-9cfb-7eaa05f2997f.png)

**Comment by vshampor** [comment]
Greetings!

The meaning here is that the underlying tensor is not laid out contiguosly in memory. See more info [here](https://pytorch.org/docs/stable/generated/torch.Tensor.is_contiguous.html). 

For proper functioning of our HW-accelerated quantization kernels the tensors that are processed during `backward` must be contiguous in memory, hence the warning. This does not impact functional results and can be safely ignored. We will move the warning to the debug level shortly.

**Comment by Alina9** [comment]
@vshampor , Thank you for your answer!
