### ISSUE TITLE
`.export_model()` breaks with PyTorch 1.11 and later

### ISSUE THREAD

**Issue by helena-intel** [openvinotoolkit/nncf#1354]
The `.export_model()` method for PyTorch models calls `torch.onnx.export()` with the `enable_onnx_checker` parameter set to False:
https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/exporter.py#L163
This parameter exists in PyTorch 1.9.1 and is set to True by default. In 1.10 the parameter is deprecated, and in 1.11 it doesn't exist anymore. This means that using NNCF with PyTorch 1.11 or later results in an error:
![image](https://user-images.githubusercontent.com/77325899/200345634-2ba97d05-12be-4bbc-be6d-d1a872b7bd11.png)

Could this be changed in NNCF so that it doesn't break with PyTorch 1.11 and later? I had no issues with NNCF with recent PyTorch versions if I manually remove this line.

**Comment by ljaljushkin** [comment]
Thank you for noticing, Helena!

We're bumping torch version to 1.12/1.13, so that issue will be covered here: https://github.com/openvinotoolkit/nncf/pull/1323

**Comment by helena-intel** [comment]
That's great! I look forward to that and will close this issue then.
