### ISSUE TITLE
AutoQ doesn't choose bitwidth higher than 8

### ISSUE THREAD

**Issue by ljaljushkin** [openvinotoolkit/nncf#1385]
I also tried the `TRIAL` device and the bitwidth distribution logged only consists of N=2, 4, and 8. Please find the following config and output.log files: 

They were generated by the run:

[config.json](https://github.com/i3abghany/nncf/blob/develop/examples/config.json)
[output.log](https://github.com/i3abghany/nncf/blob/develop/examples/output)

_Originally posted by @i3abghany in https://github.com/openvinotoolkit/nncf/discussions/1378#discussioncomment-4178960_

**Comment by MaximProshin** [comment]
@ljaljushkin , I think we can close it and track internally. What do you think?
