### ISSUE TITLE
Subclass QuantizerConfig for INT-N and BFP specialization

### ISSUE THREAD

**Issue by vshampor** [openvinotoolkit/nncf#140]
Some class-level specialization might be in order here, otherwise we end up with a situation when INT-N only uses a half of the available config structs, and certain quantizer configs won't correspond to any real quantizer.
`class IntNQuantizerConfig(QuantizerConfig):`, `class BFPQuantizerConfig(QuantizerConfig):` - what do you think?

_Originally posted by @vshampor in https://github.com/openvinotoolkit/nncf_pytorch/pull/137#discussion_r488457114_

**Comment by RikAllen** [comment]
An option which might resolve things would be to use "bits" in the base class - it is effectively the  number of bits assigned to each quantized component (i.e. what we use mantissa bits for). That would let other classes iterate over collections on the number of bits etc. This might become problematic if ever we offered BFP and intn quantisation options for the same layer for HAWQ to decide between, but that opens a whole new can of worms.

**Comment by RikAllen** [comment]
There are further interesting features where some classes hold a default qconfig to be applied to things. This is typically an intN version - but sometimes it gets used where the underlying quantizer is being setup by a hw_config that has mode=bfp.  I've been adding a second default in these cases and selecting based on mode, but it does not feel the ideal solution. Perhaps creating "default" on demand once knowledge of the mode is available at runtime.
