### ISSUE TITLE
Mixed Precision missquantization

### ISSUE THREAD

**Issue by SKholkin** [openvinotoolkit/nncf#144]
While training object detection model through hawq config, I realized there are much more int8 activation quantizations then int8 weight quantizations. According to [netron](https://lutzroeder.github.io/netron/) some convolutions take int8 activations and int4 weights. I suppose that's not how things should be. What do you think?
![image](https://user-images.githubusercontent.com/59054308/93767516-d3282d00-fc20-11ea-8a49-a91d89bce129.png)

**Comment by vanyalzr** [comment]
@ljaljushkin the activation FakeQuantize acts as an input to two convolutions - one with INT8 quantized weights, another one with INT4. So the bitwidth for this activation quantizer is not defined properly (or there should be requantization). I guess both convs. that share an input activation FQ should have the same bitwidth for weights during precision selection for the layers?

**Comment by SKholkin** [comment]
Same problem has been located on resnet50 and squeezenet mixed precision hawq torch checkpoints from [README.md](https://github.com/openvinotoolkit/nncf_pytorch/blob/develop/examples/classification/README.md)
ResNet-50([link](https://download.01.org/opencv/openvino_training_extensions/models/nncf/resnet50_imagenet_int4_int8.pth))
![resnet_missquant](https://user-images.githubusercontent.com/59054308/94010972-52e40200-fdaf-11ea-8fe8-99cf7f9e6da6.png)
SqueezeNet V1.1 ([link](https://download.01.org/opencv/openvino_training_extensions/models/nncf/squeezenet1_1_imagenet_int4_int8.pth))
![squeezenet_missquant](https://user-images.githubusercontent.com/59054308/94011124-950d4380-fdaf-11ea-8011-b3c69bb97985.png)

**Comment by vshampor** [comment]
Looks like for this case to work we will have to track the node/nodes affected by a propagating quantizer (in addition to the HW configurations). This will require some changes to the `QuantizerPropagationStateGraph`, `PropagatingQuantizer`, `QuantizerPropagationSolver` - basically some additional info has to be gathered and the return values should be extended.

**Comment by RikAllen** [comment]
I would comment that having different bitdepth of activation and weight going into a convolution is  exactly what I do want - there is nothing constraining hardware generally to requite them to match.

**Comment by ljaljushkin** [comment]
> I would comment that having different bitdepth of activation and weight going into a convolution is exactly what I do want - there is nothing constraining hardware generally to requite them to match.

@RikAllen, right. We need a special option for FPGA in HW config to allow different bit-width. The current behavior is the default for the existing hardware: VPU, CPU, GPU.
