### ISSUE TITLE
Suggestion for DynamicGraph.get_all_edges() function 

### ISSUE THREAD

**Issue by NKSagarReddy** [openvinotoolkit/nncf#1469]
Hi, I have tried using NNCF as a part of a model pruning framework which uses DynamicGraph('nncf/nncf/torch/dynamic_graph/graph.py') object to represent model graph.

Overview of the framework:
Pruning ratios for each layer are decided, and then, before parameter shrinking(sparse/0 values are removed), the framework has to find input edges for each node, to generate input mask for shrinking the layer parameters).

DynamicGraph.get_all_edges() helps to find incoming edges for each node, but it is ordered based on node_id.
I had to change the order of edges to ensure correct pruning.

Suggestion:
If DynamicGraph.get_all_edges() returns incoming edges instead of outgoing edges, the output(list of DynamicGraphEdge) is sufficient to reconstruct the model graph in the correct way.(outgoing order of edges results in wrong model graph for nodes like CONCAT).

Suggested Code Change:
![codechange](https://user-images.githubusercontent.com/108252538/210031422-9000c9bc-899c-44b4-b683-d07150f18ce5.jpg)

Example of graph reconstruction based on order of edges:(Input edges to 'node 2' will be in different order in both cases)

![networkx digraph](https://user-images.githubusercontent.com/108252538/210031490-0fb1b214-edee-4744-8aa7-6bcca0a25c41.jpg)

**Comment by alexsu52** [comment]
Could you open a PR with these changes?

**Comment by ljaljushkin** [comment]
Thank you for the suggestion! It was merged to develop #1474
