### ISSUE TITLE
Is it possible to relax jsonschema version pinning?

### ISSUE THREAD

**Issue by helena-intel** [openvinotoolkit/nncf#1482]
In setup.py, jsonschema is currently pinned to 3.2.0 exactly. Recent Jupyter Lab installs have higher version requirements:
- jupyter-events 0.5.0 requires jsonschema>=4.3.0
- jupyterlab-server 2.18.0 requires jsonschema>=4.17.3

If you do `pip install jupyterlab nncf` pip will try to download many versions of dependencies before it eventually manages to resolve versions that work with both jupyterlab and NNCF.

Could the version pinning of jsonschema in NNCF be relaxed?

**Comment by alexsu52** [comment]
Hi @helena-intel,

Thanks for the question. Need to check.

@ljaljushkin, could you take a look?

**Comment by MaximProshin** [comment]
@vshampor , please take a look and check if we can do it during nncf release or there are some issues with it.
