### ISSUE TITLE
NNCF Quantized BERT IR is getting unmatched accuracy to pytorch model

### ISSUE THREAD

**Issue by vuiseng9** [openvinotoolkit/nncf#1498]
Reproduce issue:
1. follow instructions [here](https://github.com/openvinotoolkit/nncf/tree/develop/third_party_integration/huggingface_transformers#integrating-nncf-into-transformers) and quantize bert-large with [out-of-the-box nncf config](https://github.com/openvinotoolkit/nncf/tree/develop/third_party_integration/huggingface_transformers#bert-squad-v11)
`run_qa.py --model_name_or_path bert-large-uncased-whole-word-masking ... --nncf_config nncf_bert_config_squad.json`
2. export the onnx, convert it to IR using OpenVINO-dev 2022.3.
3. evaluate IR on squad dataset. We are getting 
```
***** eval metrics *****
  eval_exact_match =  1.088
  eval_f1          = 8.1601
  eval_samples     =  10784
```
nncf commit `c60566bb3011a01fccf0910bff2bc75d2747dc97`

**Comment by vuiseng9** [comment]
@ljaljushkin fyi.

**Comment by ljaljushkin** [comment]
should be fixed here: https://github.com/openvinotoolkit/openvino/pull/15496

**Comment by helena-intel** [comment]
I saw very similar results when I compressed bert-base-uncased with JPQD with `overflow_fix=disabled` or `overflow_fix=first_layer_only`  and do inference on a computer without avx512_vnni (in OpenVINO 2022.3 and  2023.0.0.dev20230217 prerelease). Accuracy on the same model on a machine that does have VNNI is as expected. 

Of course this is probably why you should set `overflow_fix` to `enabled` on devices without avx512_vnni (but with avx2/avx512) as documented in the [quantization docs](https://github.com/openvinotoolkit/nncf/blob/develop/docs/compression_algorithms/Quantization.md), but it's easy to miss if you usually work on processors that have VNNI and then suddenly see terrible performance for example in a CI system with lower specs, or when you have to use a cloud platform with a different processor.  Mentioning this here in case it helps others who find this issue.

**Comment by MaximProshin** [comment]
@vuiseng9 , is the issue closed by https://github.com/openvinotoolkit/openvino/pull/15496 now?
