### ISSUE TITLE
Error in creating a compressed model with create_compressed_model

### ISSUE THREAD

**Issue by mnl12** [openvinotoolkit/nncf#1550]
Operating system linux ubuntu
Tensorflow 2.9.1
Openvino 2022.3.0
NNCF 2.30
Model: Delg (https://github.com/tensorflow/models/tree/master/research/delf)

Hi,

I try to make a compressed model of the above with nncf create_compressed_model. The training is done and the check point is saved according to https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training.
I use 

  nncf_config_dict = {
        "input_info": {"sample_size": [224, 224, 3]},  # input shape required for model tracing
        "compression": {
            "algorithm": "quantization",  # 8-bit quantization with default settings
        },
    }
    nncf_config = NNCFConfig.from_dict(nncf_config_dict)
    nncf_config = register_default_init_args(nncf_config, train_dataset, batch_size=1) 

    compression_ctrl, model = create_compressed_model(keras_model, nncf_config)

train_dataset is an instance of tf.data.Dataset created according the above link. However I receive an error:

File "/tmp/__autograph_generated_filem08gtxxu.py", line 40, in else_body
    raise ag__.converted_call(ag__.ld(e).with_traceback, (ag__.ld(filtered_tb),), None, fscope) from None
  File "/tmp/__autograph_generated_filem08gtxxu.py", line 34, in else_body
    retval_ = ag__.converted_call(ag__.ld(fn), tuple(ag__.ld(args)), dict(**ag__.ld(kwargs)), fscope)
TypeError: in user code:

    File "/home/devel/dev/data/codes/delg/venv/lib/python3.7/site-packages/keras/engine/base_layer.py", line 899, in error_handler  *
        return fn(*args, **kwargs)

    TypeError: Missing required positional argument

I was wondering if you could help on this issue.
Thanks.

**Comment by AlexKoff88** [comment]
@alexsu52, @andrey-churkin, can you please take a look?

**Comment by andrey-churkin** [comment]
@mnl12 Hello, Thanks for your question! As I can see this model was created using [Keras Subclassing API](https://www.tensorflow.org/guide/keras/custom_layers_and_models). Unfortunately, NNCF for TensorFlow supports quantization for such models only as the experimental feature.

Could you please verify that the `patch_tf_operations()` method was called at beginning of your script? The example is presented below
```python
# First import in the script
from nncf.experimental.tensorflow.patch_tf import patch_tf_operations
patch_tf_operations()

# Rest imports
```

**Comment by MaximProshin** [comment]
@mnl12 , do you have any feedback to the suggestion above?

**Comment by MaximProshin** [comment]
I close this issue as there is no feedback from the user for a long time period. Feel free to create a new issue, if it's still valid.
