### ISSUE TITLE
Error when one module has multiple torch.nn.functional.conv1d in PyTorch filter pruning

### ISSUE THREAD

**Issue by wuyushuwys** [openvinotoolkit/nncf#1555]
Hi, 

I am trying to running the nncf filter pruning with PyTorch. I encountered an error when I have two `torch.nn.functional.conv1d` in one module.

the error log shows 

``` bash
  File "****/lib/python3.9/site-packages/nncf/common/pruning/node_selector.py", line 183, in create_pruning_groups
    can_prune_final_analysis = self._pruning_dimensions_analysis(graph, pruned_nodes_clusterization,
  File "****/lib/python3.9/site-packages/nncf/common/pruning/node_selector.py", line 220, in _pruning_dimensions_analysis
    nodes_of_group_with_non_eq_pruning_dim = self._check_internal_groups_dim(pruned_nodes_clusterization)
  File "****/lib/python3.9/site-packages/nncf/common/pruning/node_selector.py", line 263, in _check_internal_groups_dim
    all(get_output_channels(cluster.elements[0]) == get_output_channels(node)
  File "****/lib/python3.9/site-packages/nncf/common/pruning/node_selector.py", line 263, in <genexpr>
    all(get_output_channels(cluster.elements[0]) == get_output_channels(node)
  File "****/lib/python3.9/site-packages/nncf/common/pruning/utils.py", line 410, in get_output_channels
    raise RuntimeError(f'Can\'t get count of output channels from node {node}')
RuntimeError: Can't get count of output channels from node 2 Foo/conv1d_1 conv1d
```

here is a script that could reproduce the error
```

import torch
from torch.utils.data import DataLoader
import nncf
from nncf import NNCFConfig
from nncf.torch import create_compressed_model, register_default_init_args


class FakeDatset(torch.utils.data.Dataset):
        def __init__(self, size) -> None:
            super(FakeDatset).__init__()
            self.size = size
        
        def __getitem__(self, idx):
            return torch.rand(*(self.size)), torch.rand(*(self.size))

        def __len__(self):
            return 1024

class Foo(torch.nn.Module):
        def __init__(self) -> None:
            super(Foo, self).__init__()
            self.wcos = torch.nn.Parameter(torch.rand(3, 1, 15), requires_grad=False)
            self.wsin = torch.nn.Parameter(torch.rand(3, 1, 15), requires_grad=False)
            
        
        def forward(self, x) -> torch.Tensor:
            x_cos = torch.nn.functional.conv1d(
                x,
                weight=self.wcos,
            )
            x_sin = torch.nn.functional.conv1d(
                x,
                weight=self.wsin,
            )
            x = x_sin + x_cos
            return x

class FooNoError(torch.nn.Module):
        def __init__(self) -> None:
            super(FooNoError, self).__init__()
            self.wcos = torch.nn.Parameter(torch.rand(3, 1, 15), requires_grad=False)

        def forward(self, x) -> torch.Tensor:
            x_cos = torch.nn.functional.conv1d(
                x,
                weight=self.wcos,
            )
            x = x_cos
            return x


def main():
    dataset = FakeDatset((1, 1, 1024))
    loader_train = DataLoader(dataset, batch_size=4)
    model = Foo()  # replace Foo() with FooNoError() for no error test
    nncf_config_dict = {
        # input shape required for model tracing
        "input_info": {"sample_size": [1, 1, 1024]},
        "compression": [
            {
                "algorithm": "filter_pruning",
                "pruning_init": 0.4,
                "params": {
                    "pruning_target": 0.4,
                    "pruning_steps": 15
                }
            },
        ]
    }
    nncf_config = NNCFConfig.from_dict(nncf_config_dict)
    nncf_config = register_default_init_args(nncf_config, loader_train)
    compression_ctrl, model = create_compressed_model(model, nncf_config)


if __name__ == "__main__":
    main()
```

My NNCF version is `2.4.0`
I create a fake dataset and two fake models to reproduce this error. If there is only one `torch.nn.functional.conv1d` every things looks good (as FooNoError shows). Otherwise, there will be an error. Thanks

**Comment by MaximProshin** [comment]
@daniil-lyakhov , @ljaljushkin , please take a look.

**Comment by daniil-lyakhov** [comment]
Hello, @wuyushuwys, thank you for your finding!
Main problem here is that NNCF could only modify specific torch modules (values of dict specified [here](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/layers.py#L372-L380)) but couldn't modify `torch.nn.functional` call.  

Torch models modification algorithm implemented in NNCF is based on `torch.Module` replacement: for example `torch.Conv2d` module is being replaced by `NNCFConv2d` that contains functionality to modify weights/activations values and etc. In your case NNCF pruning algo wrongly considered your functional call as module call and trying to use `NNCFConv1d` functionality. We are aware of this issue and the fix is planed to come soon. So when fix will be implemented NNCF will just say that it could prune nothing from such module.

To actually prune your model you can do following:
1) Replace  `torch.nn.functional.conv1d` by `torch.Conv1d` or `torch.Linear` module call. Module will be replaced automatically. This path is recommended for your case.

2) In case you need a custom conv module you can register it in NNCF by wrapping it by `nncf.torch.layers.register_module` function. Only restriction for your module is requirement to keep weights in `.weights` attribute.

**Comment by wuyushuwys** [comment]
Hello, @daniil-lyakhov. Thanks for your reply.
Actually what we want to do is skip those CONV layer compute by `torch.nn.functional.conv1d`. Since we define the whole convolution layer, we don't want to prune the weight we defined. Would that be possible for NNCF? 

Thanks.

**Comment by daniil-lyakhov** [comment]
NNCF filter pruning algorithm only allows to remove some internal dimensions in a model. So, if you convert two separate convolutions into one group convolution it's theoretically possible to prune part of groups from one conv, but it's not implemented in NNCF.

NNCF has BootstrapNAS (ex here: https://github.com/openvinotoolkit/nncf/tree/develop/examples/experimental/torch/classification). @ljaljushkin, could you please specify limitation of BootstrapNAS? Is it possible to remove one conv in the presented model?

**Comment by ljaljushkin** [comment]
Hello @wuyushuwys!

Seems like `ignored_scope` property in the config is what you need to not prune this layer.
Please refer to these [page](https://github.com/openvinotoolkit/nncf/blob/develop/docs/NNCFArchitecture.md#operation-scope-and-addressing) and the [example](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/configs/quantization/inception_v3_imagenet_int8.json#L25).

**Comment by ljaljushkin** [comment]
Yes, the BootstrapNAS can prune not only filters in the layers, but can also skip the whole layers.
By default, it automatically finds (via [get_building_blocks](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/experimental/torch/search_building_blocks/search_blocks.py#L344) function) building blocks that can be skipped. This function capable to find basic blocks, e.g. Residual or Bottleneck, but may not find very small blocks (1 or 2 ops on the branches).

There's a possibility to specify all blocks to skip manually via [skipped_blocks](https://github.com/openvinotoolkit/nncf/blob/develop/examples/experimental/torch/classification/bootstrapnas_examples/config.json#L44) property.
NNCF skips a single layer by scope of the starting node (this node is executed and resulted tensor is cached) and scope of the end node (this is the last skipped node that outputs cached tensor).
For example, this block: ['VGG/Sequential[features]/NNCFBatchNorm2d[1]/batch_norm_0',                                    'VGG/Sequential[features]/ReLU[2]/relu__0'] will skip relu.
![image](https://user-images.githubusercontent.com/4014476/217569825-29e80ba0-04a3-4013-80d5-ac8b617d1b2e.png)

**Comment by wuyushuwys** [comment]
I was trying to use the `skipped_scopes` or `ignored_scopes` methods to skip those two convolution functions. Neither of them works on my side. Still have the same error; I may need to find a workaround or wrap those conv functions into modules.

**Comment by ljaljushkin** [comment]
> onv function into a module and register w

Sorry for confusing. I've posted the comment about 'ignored_scopes' by mistake. I realized that it shouldn't help and I deleted it. Here's the [clarification](https://github.com/openvinotoolkit/nncf/issues/1555#issuecomment-1422493502) from the Daniil that filter pruning algorithm doesn't support layer's removal. You should consider [NAS capabilities](https://github.com/openvinotoolkit/nncf/issues/1555#issuecomment-1422802030) for that.

**Comment by Yushu-Wu-Bose** [comment]
No problem, I would try the NAS methods. Thanks for your help!

**Comment by ljaljushkin** [comment]
> > onv function into a module and register w
> 
> Sorry for the confusion. I posted the comment about 'ignored_scopes' by mistake. I realized that it shouldn't help and I deleted it. Here's the [clarification](https://github.com/openvinotoolkit/nncf/issues/1555#issuecomment-1422493502) from the Daniil that the filter pruning algorithm currently can't skip a layer on the branch going to `add` op. You should consider [NAS capabilities](https://github.com/openvinotoolkit/nncf/issues/1555#issuecomment-1422802030) for that.

Close it as the possible solution was provided. Otherwise, @wuyushuwys, feel free to contact us.
