### ISSUE TITLE
What is the relationship between POT and  NNCF？

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/nncf#1619]
When I use nncf.quantize, I can see the INFO:

INFO:openvino.tools.pot.xxxxxxx

and I see the same name (pot.pipeline  pot.algorithms）in POT , I want to know the difference between that .

Thank you very much.

**Comment by AlexanderDokuchaev** [comment]
Hi @sanbuphy 

POT and NNCF are developed by the same team. But historically they were split into two tools for post-training (POT) and during training (NNCF) compression algorithm. And POT as a tool for quantizing OpenVINO models is part of the OpenVINO package.
But now we are working on merging them within NNCF.

**Comment by sanbuphy** [comment]
> Hi @sanbuphy
> 
> POT and NNCF are developed by the same team. But historically they were split into two tools for post-training (POT) and during training (NNCF) compression algorithm. And POT as a tool for quantizing OpenVINO models is part of the OpenVINO package. But now we are working on merging them within NNCF.

Thank you very much.
