### ISSUE TITLE
Check consistency of all affected quantizers on activation quantizers merge in propagation mode.

### ISSUE THREAD

**Issue by ljaljushkin** [openvinotoolkit/nncf#164]
By default, the merge of activation quantizers should not happen if they are connected with weight quantizers that have different supported bit-width.
![image](https://user-images.githubusercontent.com/4014476/94909135-6710b900-04ab-11eb-9378-a06076927bad.png)

The merge can happen if the corresponding flag (e.g. allow_different_bitwidth_for_weight_and_activation or something shorter) is specified in the HW Config.
![image](https://user-images.githubusercontent.com/4014476/94909148-6d9f3080-04ab-11eb-8a7d-7c6ad4d07846.png)

@vshampor @asenina @RikAllen

**Comment by RikAllen** [comment]
That sounds quite useful - we would be quantizing activations for storage only once - so in practical terms for storage we would be applying the second case. However - even is stored at e.g. 8 bit activation, we can run them through the convolution as 4 bit anyway if that is optimal for a particular convolution by masking bits off. Merge of quant nodes I think is part of what we need - but I need to figure out what my full ask is.
![image](https://user-images.githubusercontent.com/62760324/94912449-93bed380-049f-11eb-9dc7-4223a3645a85.png)

**Comment by RikAllen** [comment]
(The odd bit depths are because we consider sign:magnitude. Int4 is one bit sign, 3 bits magnitude. Use that twice in long multiplication and we get 1 sign and 2*3 magnitude = 7 bits.

**Comment by ljaljushkin** [comment]
Resolved by introducing liberal and strict modes for assigning bitwidth for activation quantizaer #222 and #191
