### ISSUE TITLE
Merge activation quantizers after HAWQ init in propagation mode.

### ISSUE THREAD

**Issue by ljaljushkin** [openvinotoolkit/nncf#165]
Currently, merge activation quantizers is always happen in the case of consistent bit-width of all affected quantizers.
For example, as in the diagram below.
![image](https://user-images.githubusercontent.com/4014476/94910438-6547f500-04ad-11eb-8239-a382b7f9bff3.png)

But HAWQ may choose a more accurate configuration when the merge is not possible
![image](https://user-images.githubusercontent.com/4014476/94910528-827cc380-04ad-11eb-9d4b-8b0e86f33d3f.png)

Before implementing this feature, some research of possible performance gain for both schemes is required (consider overhead for re-quantizations and compare which configuration is faster)

@asenina @vshampor @AlexKoff88

**Comment by vshampor** [comment]
May be potentially addressed #302

**Comment by vshampor** [comment]
#302 merged, the situation has improved for the better - precision init can now select different precisions for branches. Requantization is, however, not considered both in AutoQ and HAWQ w.r.t. performance impact.
