### ISSUE TITLE
Long graph processing for quantization DENSENET161 

### ISSUE THREAD

**Issue by asenina** [openvinotoolkit/nncf#173]
Long work of creating a compressed model of the quantization algorithm for DENSENET161 (looks to me like a loop while processing a graph)

Steps to reproduce:
0. Create python3.6 env
1. Install nncf (use instructions from README)
2. Run in terminal: ` python examples/classification/main.py --config examples/classification/configs/quantization/densenet161_imagenet_custom_quant_pattern.json  --data <path_to_dataset> `

**Comment by vshampor** [comment]
Model topology and flaws in graph pattern matching lead to possibly ineffective execution. Need to optimize the pattern matching algorithm (HW-fused ops merging).

**Comment by aleksei-kashapov** [comment]
This resolved by https://github.com/openvinotoolkit/nncf/pull/762
