### ISSUE TITLE
Is there a NNCF version which use Openvino 2021.x.x ?

### ISSUE THREAD

**Issue by superkido511** [openvinotoolkit/nncf#1793]
Is there a old release of nncf which work with openvino 2021? Our system use openvino 2021 and I don't really want to refactor everything

**Comment by AlexKoff88** [comment]
Hi,

I think it is not about NNCF but about converting model from PyTorch -> ONNX -> OpenVINO 2021.2. For the NNCF, I would recommend using opset 13 when converting to ONNX after optimization in PyTorch.

**Comment by superkido511** [comment]
> 
Thanks for the tip. I will try this approach.
