### ISSUE TITLE
ModuleNotFoundError: No module named 'jstyleson' when import nncf

### ISSUE THREAD

**Issue by openvino-book** [openvinotoolkit/nncf#1839]
OS: windows 11,
Python 3.9.16
nncf=2.4.0
jstyleson = 0.0.2, I am sure I have ready installed the jstyleson
When execute the import nncf, get the error: ModuleNotFoundError: No module named 'jstyleson', as the sreenshoot below:

![No module named 'jstyleson'](https://github.com/openvinotoolkit/nncf/assets/128127436/744442f6-235c-42f8-a8eb-598414e9703b)

**Comment by vshampor** [comment]
@openvino-book did you have a chance to try the fresh installation?

**Comment by MaximProshin** [comment]
Dear @openvino-book , do you have any feedback?

**Comment by openvino-book** [comment]
re-install the anaconda and nncf, it works!
![image](https://github.com/openvinotoolkit/nncf/assets/128127436/60510d67-914a-4c97-a74f-9c8f7ac36591)
