### ISSUE TITLE
Is filter_pruning supported for Keras SubClass style model?

### ISSUE THREAD

**Issue by lisosia** [openvinotoolkit/nncf#1939]
README says
```
Automatic, configurable model graph transformation to obtain the compressed model.
NOTE: Limited support for TensorFlow models. The models created using Sequential or Keras Functional API are only supported.
```

But there is 
- [experimental feature of qunatization for Keras subclass style model](https://github.com/openvinotoolkit/nncf/issues/1570#issuecomment-1430862097)
- [quantization test code for Keras SubClass style models](
https://github.com/openvinotoolkit/nncf/tree/68b3037bc61c2cd1c5a1c6c22ab014b08d712d8a/tests/experimental/tensorflow)

Is filter_pruning also supported for Keras SubClass style model?
If no, is there any plan?

**Comment by andrey-churkin** [comment]
@lisosia Hello, Thanks for the question! Unfortunately, the filter pruning currently is not supported for Keras Subclass models in NNCF. We have some plans to add the support, but I can't say when exactly it will be done.

**Comment by lisosia** [comment]
Thanks for the reply. I understand the situation.
