### ISSUE TITLE
nncf 2.5 set Advanced_parameters`s weight and activation perchannel quant onnx failed

### ISSUE THREAD

**Issue by jasonlove521** [openvinotoolkit/nncf#1959]
when update nncf to 2.5, i set Advanced_parameters.weight.per_channel=True and Advanced_parameters.activation.per_channel=True, nncf throw the execption as follows:

RuntimeError: Quantization parameter constraints specified in NNCF config are incompatible with HW capabilities as specified in HW config type 'CPU'. First conflicting quantizer location: Conv_0

i  want to know how to fix this problem

**Comment by alexsu52** [comment]
Hi @jasonlove521,

NNCF throws the error for `Advanced_parameters.activation.per_channel=True` because the OpenVINO runtime does not support per-channel activation quantization. Are you going to use OpenVINO for model inference? What target device are you going to use?

**Comment by jasonlove521** [comment]
yes,i want to use OpenVino to do something on intel cpu .when i use nncf 2.4, nncf can genarate a best perfermance quant model with DefaultQuantization, but nncf 2.5 can`t. However, DefaultQuantization use the the ActivationChannelAlignment algorithm, so i want to konw  whether the ActivationChannelAlignment algorithm for activation quantization is per-channel quantization

**Comment by jasonlove521** [comment]
@alexsu52 
yes,i want to use OpenVino to do something on intel cpu .when i use nncf 2.4, nncf can genarate a best perfermance quant model with DefaultQuantization, but nncf 2.5 can`t. However, DefaultQuantization use the the ActivationChannelAlignment algorithm, so i want to konw whether the ActivationChannelAlignment algorithm for activation quantization is per-channel quantization

> Hi @jasonlove521,
> 
> NNCF throws the error for `Advanced_parameters.activation.per_channel=True` because the OpenVINO runtime does not support per-channel activation quantization. Are you going to use OpenVINO for model inference? What target device are you going to use?

yes,i want to use OpenVino to do something on intel cpu .when i use nncf 2.4, nncf can genarate a best perfermance quant model with DefaultQuantization, but nncf 2.5 can`t. However, DefaultQuantization use the the ActivationChannelAlignment algorithm, so i want to konw whether the ActivationChannelAlignment algorithm for activation quantization is per-channel quantization and What is the difference between DefaultQuantization in nncf 2.4 and the unified quantization in nncf 2.5

**Comment by jasonlove521** [comment]
> Hi @jasonlove521,
> 
> NNCF throws the error for `Advanced_parameters.activation.per_channel=True` because the OpenVINO runtime does not support per-channel activation quantization. Are you going to use OpenVINO for model inference? What target device are you going to use?

yes,i want to use OpenVino to do something on intel cpu .when i use nncf 2.4, nncf can genarate a best perfermance quant model with DefaultQuantization, but nncf 2.5 can`t. However, DefaultQuantization use the the ActivationChannelAlignment algorithm, so i want to konw whether the ActivationChannelAlignment algorithm for activation quantization is per-channel quantization and What is the difference between DefaultQuantization in nncf 2.4 and the unified quantization in nncf 2.5.
