### ISSUE TITLE
Usage examples for filter pruning

### ISSUE THREAD

**Issue by cxmscb** [openvinotoolkit/nncf#2004]
Hi, I find there are many usage examples (python codes) for model quantization but less examples for other compression types, especially for filter pruning. Could you provide some usage examples for filter pruning?

**Comment by alexsu52** [comment]
Hi @cxmscb, 

Pruning algorithm is one from NNCF training-time compression algorithms. You can use Training-Time Compression usage example from the main Readme. Also we provide several examples with reported results for filter pruning algorithm for PyTorch and TensorFlow mdoels:

**PyTorch:**
- [classification example](https://github.com/openvinotoolkit/nncf/tree/develop/examples/torch/classification): [ResNet18 pruning config](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/configs/pruning/resnet18_imagenet_pruning_geometric_median.json), [ResNet50 pruning config](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/configs/pruning/resnet50_imagenet_pruning_geometric_median.json)
- [object detection example](https://github.com/openvinotoolkit/nncf/tree/develop/examples/torch/object_detection): [SSD300_VGG pruning config](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/object_detection/configs/ssd300_vgg_voc_pruning_geometric_median.json)
- [semantic segmentation example](https://github.com/openvinotoolkit/nncf/tree/develop/examples/torch/semantic_segmentation): [UNet pruning config](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/semantic_segmentation/configs/unet_mapillary_pruning_geometric_median.json)

**Tensorflow:**
- [classification example](https://github.com/openvinotoolkit/nncf/tree/develop/examples/tensorflow/classification): [ResNet50 pruning config](https://github.com/openvinotoolkit/nncf/blob/develop/examples/tensorflow/classification/configs/pruning/resnet50_imagenet_pruning_geometric_median.json), [ResNet50 pruning + quantization config](https://github.com/openvinotoolkit/nncf/blob/develop/examples/tensorflow/classification/configs/pruning_quantization/resnet50_imagenet_pruning_geometric_median_int8.json)
- [object detection example](https://github.com/openvinotoolkit/nncf/tree/develop/examples/tensorflow/object_detection): [RetinaNet pruning config](https://github.com/openvinotoolkit/nncf/blob/develop/examples/tensorflow/object_detection/configs/pruning/retinanet_coco_pruning_geometric_median.json), [RetinaNet pruning + quantization config](https://github.com/openvinotoolkit/nncf/blob/develop/examples/tensorflow/object_detection/configs/pruning/retinanet_coco_pruning_geometric_median.json)

**Comment by alexsu52** [comment]
Please reopen if you have questions.
