### ISSUE TITLE
Handle frozen layers properly in sparsity and quantization

### ISSUE THREAD

**Issue by vanyalzr** [openvinotoolkit/nncf#201]
Some training pipelines (e.g. Mask-RCNN-R50 in mmdetection) have certain layers frozen by default. Sparsification and low-bitwidth quantization for the frozen layers might lead to accuracy degradation, so these layers have to be skipped. INT8 quantization is expected to be fine (given that FakeQuantized parameters are tuned).

**Comment by ljaljushkin** [comment]
As we discussed internally if frozen layers are not specified in `ignored_scopes`, NNCF should throw an error.

**Comment by ljaljushkin** [comment]
relates to #199

**Comment by vshampor** [comment]
Should be resolved by #455.
