### ISSUE TITLE
Error in post-training quantisation of an openvino model

### ISSUE THREAD

**Issue by mnl12** [openvinotoolkit/nncf#2018]
openvino 2023.0.0
nncf 2.5.0

I have the following model converted to Openvino,
[delg_artivive_syn_8_1.zip](https://github.com/openvinotoolkit/nncf/files/12229697/delg_artivive_syn_8_1.zip)

When I want to quantize the model using post-training quantisation exactly as described in https://github.com/openvinotoolkit/nncf for openvino, I receive the following error in quantized_model = nncf.quantize(model, calibration_dataset),
RuntimeError: More than one node in NNCFGraph matches name Constant_9789
I was wondering if you could help on this issue. Thanks.

**Comment by alexsu52** [comment]
Hello @mnl12,

This is OpenVINO issue. The fix is here https://github.com/openvinotoolkit/openvino/pull/18772. Please use OpenVINO (https://github.com/openvinotoolkit/openvino) from the master branch to convert and quantize your model.

**Comment by mnl12** [comment]
Thanks @alexsu52 for your reply.
The issue is resolved,  the code is complied without error, but I have now another issue that  after  nncf.quantize and saving model with ov.serialize, the benchmark timing is almost the same, when I do the benchmark with -pc the execType of the converted layers are still FP32. I do the procedure according to 
https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
I was wondering if you may know the cause of the problem. Here are the original and converted models
[original.zip](https://github.com/openvinotoolkit/nncf/files/12258989/original.zip)
[quantized.zip](https://github.com/openvinotoolkit/nncf/files/12258990/quantized.zip)

Thanks.

**Comment by alexsu52** [comment]
I have filed the issue to OpenVINO https://github.com/openvinotoolkit/openvino/issues/19019 

As workaround, you can try to use OpenVINO from master to quantize model, but `openvino==2023.0.1` to convert quantized TF model to INT8 IR and for inference model after quantization.

**Comment by mnl12** [comment]
Thanks @alexsu52.
What I found is that when I wrap a model as a input-output way by tf.keras.Model, it does not quantise the layers and keeps them FP32, but for normal models it works fine, for example if the tf model is
keras_model = tf.keras.applications.resnet50.ResNet50(weights='imagenet')
works fine by the approach in  
https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/tensorflow/mobilenet_v2/main.py
but if the model is defined like
   input_image = tf.keras.Input(shape=(None, None, 3), name="input_img", dtype=tf.uint8)
  resnet_model = tf.keras.applications.resnet50.ResNet50(weights='imagenet')
  res_out=resnet_model(input_image)
  keras_model = tf.keras.Model(inputs=input_image, outputs=res_out)

does not quantise the layers in the wrapped keras_model.

**Comment by alexsu52** [comment]
Hello @mnl12, 

Thanks for the interest to NNCF.

Unfortunately, NNCF does not support quantization nested Keras models into Keras model from the box yet. You can quantize nested models separately.

**Comment by alexsu52** [comment]
Hello @mnl12,

The issue in OpenVINO was fixed https://github.com/openvinotoolkit/openvino/issues/19019, you can try. If you have any question, please, reopen this issue.
