### ISSUE TITLE
Error compiling NNCF-quantized model with GRU layers

### ISSUE THREAD

**Issue by akarym-sl** [openvinotoolkit/nncf#2105]
Hello. After performing quantization, I can no longer compile the model in OpenVINO. The model contains convolutional and **GRU** layers as well as some additional operations like pooling and BN. 

Here is the quantization code:

```python
from openvino.runtime import Core, serialize
import nncf
from pathlib import Path


def quantize_nncf(model_xml: Path, result_dir: Path, data_loader: torch.utils.data.DataLoader):
    result_dir = result_dir / "model.xml"
    model = Core().read_model(model_xml)

    class FastDL:
        def __init__(self, dl) -> None:
            self.dl = iter(dl)
        
        def __len__(self):
            return len(data_loader.dataset)

        def __getitem__(self, index):
            dp = next(self.dl)[0]
            return dp
    
    model = nncf.quantize(model, nncf.Dataset(FastDL(data_loader)))

    serialize(model, result_dir)

    return result_dir

def get_model(model_path: Path, num_threads: int=1):
    core = Core()

    model = core.read_model(model=model_path)
    model = core.compile_model(model, "CPU", {"CPU_THREADS_NUM":num_threads})
    
    return model

quantized_model = quantize_nncf(Path(models/model.xml), Path(models/quantized), <some DataLoader>)
```

Here is the traceback of the error:

```commandline
Traceback (most recent call last):
  File "file.py", line 17, in get_model
    model = core.compile_model(model, "CPU", {"CPU_THREADS_NUM":num_threads})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python3.11/site-packages/openvino/runtime/ie_api.py", line 398, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Check 'false' failed at src/inference/src/core.cpp:114:
could not create a primitive descriptor for an LBR GRU forward propagation primitive
```

**Comment by dmitry-gorokhov** [comment]
Hi @akarym-sl, is it possible to share the model itself? It will simplify debugging process a lot. Thanks!

**Comment by akarym-sl** [comment]
Hi, @dmitry-gorokhov, thank you for the fast reply. Unfortunately, the model is proprietary, so I cannot share its architecture. However, I assume that the issue can be reproduced with any model containing GRU layers. I could build one myself and test it, but I will be on vocation and it'll take some time. Until then, I must leave it to you and the community.

**Comment by antonvor** [comment]
Hi, @akarym-sl I think we can fix your problem if we disable GRU quantization in NNCF, there is the ticket for this.
@KodiaqQ may I ask you to respond here when the fix is merged?

**Comment by KodiaqQ** [comment]
Hi, @akarym-sl! Thank you for highlighting the issue!
Here is the branch with the fix that you can try in your case. It would be merged into the `develop` branch as soon as possible.

**Comment by akarym-sl** [comment]
I installed the latest version via 
`pip install git+https://github.com/openvinotoolkit/nncf.git#egg=nncf`
The issue is fixed! Thank you! Waiting for it to be in release
