### ISSUE TITLE
mAP differs from CPU and GPU

### ISSUE THREAD

**Issue by betogulliver** [openvinotoolkit/nncf#215]
I'm getting different mAP values for CPU and GPU as shown below. Any ideas on what am I doing wrong?
I simply downloaded the latest github version (today 2020.10.23), downloaded the weights 'ssd300_vgg_voc.pth' following the instructions in the README.md (./examples/object_detection) and run the following commands :

```
CPU : Mean AP = 0.4680
    python main.py -m test --config=./configs/ssd300_vgg_voc.json --data=../../xdata/datasets/pascal.VOC --resume=../../xdata/checkpoints/object.detection/ssd300_vgg_voc.pth --batch-size=128 --cpu-only

GPU : Mean AP = 0.7828
    python main.py -m test --config=./configs/ssd300_vgg_voc.json --data=../../xdata/datasets/pascal.VOC --resume=../../xdata/checkpoints/object.detection/ssd300_vgg_voc.pth --batch-size=128
```

**Comment by vshampor** [comment]
@betogulliver we will need more info on the exact way you are getting these discrepancies.

**Comment by betogulliver** [comment]
> @betogulliver we will need more info on the exact way you are getting these discrepancies.

I've edit my original post as per your request. Any ideas. thanks in advance.

**Comment by SKholkin** [comment]
Problem has been reproduced and located in NMS(Non-Maximum Suppression) CPU kernels which haven't worked right. So here is  pull request where NMS CPU  kernels in object detections sample were replaced by torch NMS function.
