### ISSUE TITLE
mixed precision quantization doesn't speedup model at all

### ISSUE THREAD

**Issue by chamecall** [openvinotoolkit/nncf#2189]
I performed quantization aware training with my model, exported it to onnx format and obtained the same throughput (~110 on my hardware) as for the same model with no quantization.

As I've read a positive marker that the quantization is done properly is existance of FakeQuantizer nodes inside exported onnx model and that is the case for my
![image](https://github.com/openvinotoolkit/nncf/assets/51739187/0dd34037-b8cd-4d0c-bd4a-6afca0581164)

During the quantization training I got these messages that should also be a marker that the quantization is applied
![image](https://github.com/openvinotoolkit/nncf/assets/51739187/9f238b77-d3b8-4c28-997d-dc654c804c73)

Can you give me some insights why there's no any speedup (but there's a definite accuracy drop) for the model?
Thank you guys

**Comment by MaximProshin** [comment]
@chamecall , what HW are you using for the inference?

**Comment by MaximProshin** [comment]
> > @chamecall , what HW are you using for the inference?
> 
> CPU, I guess it's default value for benchmark_app `benchmark_app -m {openvino_xml_model} -t 1 -report_type average_counters -hint none -nstreams 1 -nthreads 1`

Ok, but what CPU do you have on your machine?

**Comment by chamecall** [comment]
> > > @chamecall , what HW are you using for the inference?
> > 
> > 
> > CPU, I guess it's default value for benchmark_app `benchmark_app -m {openvino_xml_model} -t 1 -report_type average_counters -hint none -nstreams 1 -nthreads 1`
> 
> Ok, but what CPU do you have on your machine?

Model name:            11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

**Comment by MaximProshin** [comment]
> > > > @chamecall , what HW are you using for the inference?
> > > 
> > > 
> > > CPU, I guess it's default value for benchmark_app `benchmark_app -m {openvino_xml_model} -t 1 -report_type average_counters -hint none -nstreams 1 -nthreads 1`
> > 
> > 
> > Ok, but what CPU do you have on your machine?
> 
> sorry, the wrong PC. actual cpu is AMD Ryzen 9 5950X 16-Core Processor

This was my assumption. NNCF and OV are focused on Intel HW, so this is why you don't see the boost here, I believe.

**Comment by chamecall** [comment]
> > > > > @chamecall , what HW are you using for the inference?
> > > > 
> > > > 
> > > > CPU, I guess it's default value for benchmark_app `benchmark_app -m {openvino_xml_model} -t 1 -report_type average_counters -hint none -nstreams 1 -nthreads 1`
> > > 
> > > 
> > > Ok, but what CPU do you have on your machine?
> > 
> > 
> > sorry, the wrong PC. actual cpu is AMD Ryzen 9 5950X 16-Core Processor
> 
> This was my assumption. NNCF and OV are focused on Intel HW, so this is why you don't see the boost here, I believe.

I can run benchmark on Inter machine but along with that I for example tried to run openvino quantization notebook with uniform int8 quantization for resnet18 on tinyimagenet and it worked good, on the same machine (AMD) I've got around 3x speedup for quantized version

**Comment by chamecall** [comment]
additionally simple post training quantization works good (at least much better than qat) as well

**Comment by alexsu52** [comment]
@chamecall, Could you share the ONNX quantized model and OpenVINO version for investigation?

**Comment by chamecall** [comment]
> @chamecall, Could you share the ONNX quantized model and OpenVINO version for investigation?

sure
[model.zip](https://github.com/openvinotoolkit/nncf/files/12881744/model.zip)
```
openvino==2023.1.0
openvino-dev==2023.1.0
openvino-telemetry==2023.1.1
nncf==2.6.0
```

**Comment by chamecall** [comment]
I'd like to notice that this is the case only for mixed precision approach (type hawq), int8 uniform quantization works good, (some speedup is present)

**Comment by chamecall** [comment]
> @chamecall, Could you share the ONNX quantized model and OpenVINO version for investigation?

any updates?

**Comment by alexsu52** [comment]
> > @chamecall, Could you share the ONNX quantized model and OpenVINO version for investigation?
> 
> any updates?

Unfortunately, the update is not good. OpenVINO does not support operations with int4 weights and calculates such operations in FP32 precision, which significantly reduces performance. You can verify this by dumping the benchmark report using benchmark_app with `-report_type average_counters` option. You will see FP32 execution precision for operations with int4 weights.

I think, you can open a feature request to OpenVINO https://github.com/openvinotoolkit/openvino/issues to support mixed precision models. Right now, this task is not included in the OpenVINO roadmap.

**Comment by alexsu52** [comment]
> but if openvino doesn't support those operations why is the option even present to choose?
> is there some other runtimes that can run the obtained int8+int4 model?

Models in low precision is required for inference on embedded devices. NNCF provides capability to obtain such models for under development devices. Stay tune with OpenVINO.

**Comment by alexsu52** [comment]
Please reopen if you have questions.
