### ISSUE TITLE
SmoothQuant on INT8 weight compressed model fail to apply

### ISSUE THREAD

**Issue by xiao1228** [openvinotoolkit/nncf#2223]
SmoothQuant cannot apply to the models that is a INT8 weight compressed model.

if you first compress the weights using:
```
from optimum.intel import OVModelForCausalLM
from nncf import compress_weights
from transformers import AutoConfig
MODEL_ID = "meta-llama/Llama-2-7b-chat-hf"
ov_model = OVModelForCausalLM.from_pretrained(MODEL_ID, export=True, compile=False, trust_remote_code=True,use_cache=True, config=AutoConfig.from_pretrained(MODEL_ID, trust_remote_code=True))
ov_model.model = compress_weights(ov_model.model)
ov_model.save_pretrained("./openvino/llama2_7B_chat_8W")
```

and then apply nncf.quantize onto the weight compressed model.
```
MODEL_ID = "meta-llama/Llama-2-7b-chat-hf"
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = OVModelForCausalLM.from_pretrained("./openvino/llama2_7B_chat_8W")


def preprocess_fn(examples, tokenizer):
    data = tokenizer(examples["text"], truncation=True, max_length=64)
    return data

quantizer = OVQuantizer.from_pretrained(model)

calibration_dataset = quantizer.get_calibration_dataset(
    "wikitext",
    dataset_config_name="wikitext-2-raw-v1",
    preprocess_function=partial(preprocess_fn, tokenizer=tokenizer),
    num_samples=300,
    dataset_split="test",
    preprocess_batch=True,
)

params = AdvancedQuantizationParameters(smooth_quant_alpha=0.15)

ignored_scope = None

quantizer.quantize(
    calibration_dataset=calibration_dataset,
    save_directory="Llama2-7b_8W8A",
    advanced_parameters=params,
    ignored_scope=ignored_scope,
    subset_size=300
)
```

Smoothquant algo is not going to enabled for the Matmul layers. The reason I would like to do 2 steps for weight_compress and nncf.quantize is I would like to only do activation quantization onto certain layers. So in the ignored_scope I would put some layers that i can ignore for activation quantization while still have the weights as INT8 from the compress_weights.

In the example above i didnt include ignore_scope. but even with Ignore_scope as None, smoothquant still can't be enabled.

**Comment by alexsu52** [comment]
@KodiaqQ please take a look.

**Comment by MaximProshin** [comment]
@alexsu52 , @AlexKoff88 , @l-bat, do we really support such flow today: compress_weights() -> quantize()?

**Comment by alexsu52** [comment]
@MaximProshin NNCF does not support calling compress_weights() -> quantize() sequentially.

**Comment by xiao1228** [comment]
i did a hack by putting this line to None
https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/algorithm.py#L404 
so it solved the issue
