### ISSUE TITLE
yolov8+nncf error

### ISSUE THREAD

**Issue by phhh-xh** [openvinotoolkit/nncf#2248]
thanks your work!!! but i have a question about it Concat. and others dimensions are the same except axis 1
can u help me ?very thanks
env：
nncf== 2.5.0
openvino==2023.1.0
torch==2.1.0
Windows10
![1](https://github.com/openvinotoolkit/nncf/assets/127705113/f0694a8b-2cda-4a71-9dab-4cbc109fd591)

![3](https://github.com/openvinotoolkit/nncf/assets/127705113/d49816cf-a766-46c4-b33b-f1572a520c75)

发生异常: RuntimeError
Exception from src\inference\src\infer_request.cpp:224:
[ GENERAL_ERROR ] Shape inference of Concat node with name /model.11/Concat failed: Check 'TRShape::merge_into(output_shape, in_copy)' failed at src\core\shape_inference\include\concat_shape_inference.hpp:44:
While validating node 'opset1::Concat /model.11/Concat (/model.10/Resize[0]:f32[?,256,2..,2..], /model.6/cv2/act/Mul[0]:f32[?,128,1..,1..]) -> (f32[?,384,2..,2..])' with friendly_name '/model.11/Concat':
Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 1).

  File "E:\Demo\YOLOV8\nncf__.py", line 21, in <module>
    quantized_model = nncf.quantize(model, calibration_dataset)
RuntimeError: Exception from src\inference\src\infer_request.cpp:224:
[ GENERAL_ERROR ] Shape inference of Concat node with name /model.11/Concat failed: Check 'TRShape::merge_into(output_shape, in_copy)' failed at src\core\shape_inference\include\concat_shape_inference.hpp:44:
While validating node 'opset1::Concat /model.11/Concat (/model.10/Resize[0]:f32[?,256,2..,2..], /model.6/cv2/act/Mul[0]:f32[?,128,1..,1..]) -> (f32[?,384,2..,2..])' with friendly_name '/model.11/Concat':
Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 1).

**Comment by phhh-xh** [comment]
[best.zip](https://github.com/openvinotoolkit/nncf/files/13293770/best.zip)
my model

**Comment by alexsu52** [comment]
Hi @phhh-xh,

Usually such errors appear when the calibration dataset is incorrectly prepared for the model. You can check the calibration dataset on the original model using the following code:
```
compiled_model = ov.compile_model(ov_model)
for input in calibration_dataset.get_inference_data():
    res = compiled_model(input)
```

Also I would recommend to add resize to the dataset preprocessing
```
val_dataset = datasets.ImageFolder(
    "datasets/coco/images", 
    transform=transforms.Compose(
        [
            transforms.Resize((640, 640)),
            transforms.ToTensor(),
        ]
    ),
)
```

**Comment by phhh-xh** [comment]
thanks your advice，How do I prepare my calibration data set。And calibration_dataset belongs to that library. I can’t find it. Forgive me for being a novice.

**Comment by alexsu52** [comment]
Calibration dataset is usually a part of a validation dataset where a transformation function removes labels from the data item and prepare model input data. So first of all you need to make sure that you can infer your model on `val_dataset` without nncf.

I assume that, in your case, the problem is in the transform function of validation dataset. Could you check if you can infer the model on the validation dataset:
```
compiled_model = ov.compile_model(ov_model)
for input, data in val_dataset:
    res = compiled_model(input)
```

**Comment by phhh-xh** [comment]
thanks again， it work
