### ISSUE TITLE
openvino inference

### ISSUE THREAD

**Issue by sroot0** [openvinotoolkit/nncf#226]
when i want inference INT4 model in openvino , report this error:
C:\Program Files (x86)\Intel\openvino_2021.1.110\deployment_tools\inference_engine\samples\python\classification_sample>python classification_sample.py -m E:\NNCF\Alexnet\int4\ONNX\output\alexmodel_int4.xml -i E:\NNCF\testimage\val_233.jpeg
[ INFO ] Creating Inference Engine
[ INFO ] Loading network files:
        E:\NNCF\Alexnet\int4\ONNX\output\alexmodel_int4.xml
        E:\NNCF\Alexnet\int4\ONNX\output\alexmodel_int4.bin
[ INFO ] Preparing input blobs
[ INFO ] Batch size is 1
[ INFO ] Loading model to the plugin
Traceback (most recent call last):
  File "classification_sample.py", line 124, in <module>
    sys.exit(main() or 0)
  File "classification_sample.py", line 88, in main
    exec_net = ie.load_network(network=net, device_name=args.device)
  File "ie_api.pyx", line 311, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 320, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: unexpected levels 16 for precision I8

Does this mean that openvino does not support the inference of the int4 model?

**Comment by vshampor** [comment]
@sroot0 please direct your question to the proper repository handling OpenVINO runtime issues:
https://github.com/openvinotoolkit/openvino
