### ISSUE TITLE
about saved model after quantization

### ISSUE THREAD

**Issue by phhh-xh** [openvinotoolkit/nncf#2261]
thanks your work!!,and I have a question about it.
I can't find the file of the saved model after quantization

quantized_model = nncf.quantize(model, 
                                calibration_dataset,
                                preset=nncf.QuantizationPreset.MIXED,
                                ignored_scope=ignored_scope,
                                
                                )

**Comment by alexsu52** [comment]
Hi @phhh-xh,

`nncf.quantize()` does not save model itself. `quantized_model` can be saved using methods from the model framework. For example, If model is OpenVINO model, you can use `save_model()`, https://docs.openvino.ai/2023.1/api/ie_python_api/_autosummary/openvino.runtime.save_model.html

**Comment by phhh-xh** [comment]
Thank you for your advice.it work.
I have another question. How to predict images with the least amount of code? Do I need to write the detect function myself? Or are there other methods without using benchmark_app?

**Comment by alexsu52** [comment]
Yes, you are right. You should to implement the detect function on your side.

**Comment by phhh-xh** [comment]
thanks again
