### ISSUE TITLE
why need nncf

### ISSUE THREAD

**Issue by kotomiDu** [openvinotoolkit/nncf#237]
pytorch also has quantization api. Why should be nncf exsisted for quantization tool?

**Comment by AlexKoff88** [comment]
Hi @kotomiDu!

NNCF is aimed to perform quantization in a way that is friendly for Intel HW and considers only the corresponding quantization schemes and operations. 
It is also more automated than the native PyTorch quantization. It means that no additional manipulations with the model code, such as inserting the stubs, folding BNs, etc., is required.

**Comment by kotomiDu** [comment]
Got it! Thanks for the  comments
