### ISSUE TITLE
Quantification problem

### ISSUE THREAD

**Issue by sroot0** [openvinotoolkit/nncf#245]
When viewing the model diagram, I found that the weights were not added to the convolutional layer. 
![image](https://user-images.githubusercontent.com/50287916/97875499-6e9ada80-1d55-11eb-99da-32ea82d7614e.png)

**Comment by AlexKoff88** [comment]
If you click on the FakeQuantize on the left-hand side you will find that the input 0 corresponds to the weights. They are just not displayed correctly in Netron.

**Comment by sroot0** [comment]
> If you click on the FakeQuantize on the left-hand side you will find that the input 0 corresponds to the weights. They are just not displayed correctly in Netron.
than you for your help and  I have another question to ask, how to extract the maximum and minimum values of w in the FQ layer? Is it to add code to the training code to print it out?

**Comment by AlexKoff88** [comment]
These are input 1 and input 2 of FQ layers that corresponds to weights but this is not necessarily min max. This is what was obtained during the QAT and initialized by min/max before the fine-tuning.

**Comment by sroot0** [comment]
> 这些是与权重相对应的FQ层的输入1和输入2，但这不一定是最小最大。这是在QAT期间获得的结果，并在微调之前通过min / max进行了初始化。

![image](https://user-images.githubusercontent.com/50287916/97942593-34feb980-1dbf-11eb-9528-b7aa5b0339b4.png)
Looking at this screenshot, I think that the input 0 should correspond to the input image

**Comment by sroot0** [comment]
> 这些是与权重相对应的FQ层的输入1和输入2，但这不一定是最小最大。这是在QAT期间获得的结果，并在微调之前通过min / max进行了初始化。
I want to extract the maximum and minimum values of the weights in the calculation graph in order to calculate the scale, because I have not found any inference framework to support the conversion and inference of the in4 model, so I can only calculate the sacle and modify it manually.

**Comment by AlexKoff88** [comment]
We gonna have INT4 support in OpenVINO soon.
