### ISSUE TITLE
[Good First Issue] [NNCF] Make NNCF common tensor statistics code pass mypy checks

### ISSUE THREAD

**Issue by vshampor** [openvinotoolkit/nncf#2493]
This is exactly like https://github.com/openvinotoolkit/nncf/issues/2495 (see the description and tasks there), but the target code path for this one is `nncf/common/tensor_statistics` instead of `nncf/common/graph`.

**Comment by andrey-churkin** [comment]
@AtharvaPore01 Hi, do you have any time to finish your PR? Or we may move this issue back to the pool?

**Comment by AtharvaPore01** [comment]
@andrey-churkin Hi, Sorry for the delay from my side. I appreciate your patience. I'm currently tied up with some urgent tasks but will prioritize completing the PR as soon as possible. Your understanding is greatly appreciated.

**Comment by andrey-churkin** [comment]
@AtharvaPore01 Sorry, but we are forced to unassign you from the issue due to a lack of activity

**Comment by rk119** [comment]
.take

**Comment by rk119** [comment]
@andrey-churkin I have created a PR #2865 for this issue.

**Comment by alexsu52** [comment]
@rk119 thanks for the contribution!
