### ISSUE TITLE
[Good First Issue] [NNCF] Make NNCF common graph code pass mypy checks

### ISSUE THREAD

**Issue by vshampor** [openvinotoolkit/nncf#2495]
## Context
[NNCF](https://github.com/openvinotoolkit/nncf) code is mostly typed with conventional type hints, but historically had started out and grown without a CI-enforced `mypy` conformance process in place. Since typing is paramount for software systems of any appreciable complexity, NNCF needs to take steps to attain, ideally, full mypy coverage of at least its non-test code base. The scope of this exact task, however, will be necessarily to start out small, as recommended by the mypy devs.

## Task
Make the files under `nncf/common/graph`, which define the classes and logic for NNCF's main control flow graph abstraction, pass `mypy` without failures. Use the following `.mypy.ini` file:

```ini
[mypy]
files = nncf/common/graph
follow_imports = silent
strict = True

# should be removed later
# mypy recommends the following tool as an autofix:
# https://github.com/hauntsaninja/no_implicit_optional
implicit_optional = True
```
Create this file with the contents above in the repository root, install NNCF in editable mode by running `pip install -e .` from the repository root and then run `mypy` in command line.

This should produce the output similar to the following:
```
nncf/common/graph/utils.py:108: error: Argument 1 to "get_nodes_by_metatypes" of "NNCFGraph" has incompatible type "List[OperatorMetatype]"; expected "List[Type[OperatorMetatype]]"  [arg-type]
nncf/common/graph/utils.py:112: error: Non-overlapping container check (element type: "Type[OperatorMetatype]", container item type: "OperatorMetatype")  [comparison-overlap]
nncf/common/graph/patterns/manager.py:40: error: Returning Any from function declared to return "Dict[HWFusedPatternNames, Callable[[], GraphPattern]]"  [no-any-return]
nncf/common/graph/patterns/manager.py:44: error: Returning Any from function declared to return "Dict[HWFusedPatternNames, Callable[[], GraphPattern]]"  [no-any-return]
nncf/common/graph/patterns/manager.py:48: error: Returning Any from function declared to return "Dict[HWFusedPatternNames, Callable[[], GraphPattern]]"  [no-any-return]
nncf/common/graph/patterns/manager.py:64: error: Returning Any from function declared to return "Dict[IgnoredPatternNames, Callable[[], GraphPattern]]"  [no-any-return]
nncf/common/graph/patterns/manager.py:68: error: Returning Any from function declared to return "Dict[IgnoredPatternNames, Callable[[], GraphPattern]]"  [no-any-return]
nncf/common/graph/patterns/manager.py:72: error: Returning Any from function declared to return "Dict[IgnoredPatternNames, Callable[[], GraphPattern]]"  [no-any-return]
nncf/common/graph/patterns/manager.py:112: error: Call to untyped function "Patterns" in typed context  [no-untyped-call]
nncf/common/graph/patterns/manager.py:131: error: Argument 1 to "_get_full_pattern_graph" of "PatternsManager" has incompatible type "Dict[HWFusedPatternNames, Callable[[], GraphPattern]]"; expected "Dict[Union[IgnoredPatternNames, HWFusedPatternNames], Callable[[], GraphPattern]]"  [arg-type]
nncf/common/graph/patterns/manager.py:131: error: Argument 3 to "_get_full_pattern_graph" of "PatternsManager" has incompatible type "Optional[ModelType]"; expected "ModelType"  [arg-type]
nncf/common/graph/patterns/manager.py:147: error: Argument 1 to "_get_full_pattern_graph" of "PatternsManager" has incompatible type "Dict[IgnoredPatternNames, Callable[[], GraphPattern]]"; expected "Dict[Union[IgnoredPatternNames, HWFusedPatternNames], Callable[[], GraphPattern]]"  [arg-type]
nncf/common/graph/patterns/manager.py:147: error: Argument 3 to "_get_full_pattern_graph" of "PatternsManager" has incompatible type "Optional[ModelType]"; expected "ModelType"  [arg-type]
Found 95 errors in 10 files (checked 15 source files)
```
Walk through the relevant code lines that produced each error and correct them by setting up missing type hints or correcting the existing ones. It should be possible to infer the required type hints from the function bodies and/or usages in most cases; resort to inline-disabling `mypy` for certain lines by `# type:ignore` only if setting up correct type hints requires massive refactoring. 

Refer to https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html for basic type hinting information. Use type hints compatible with Python 3.8, e.g. `List` from the `typing` module instead of `list` etc.

**Comment by Grimoors** [comment]
I am sorry for delay, still on it.

**Comment by p-wysocki** [comment]
I'm reopening the issue due to current assignee's inactivity. If you're still working on this you can repick the task.

**Comment by p-wysocki** [comment]
@vshampor could you please unassign @Grimoors?

**Comment by Grimoors** [comment]
@p-wysocki  I apologise for my inactivity.

**Comment by p-wysocki** [comment]
There's no need to apologize, we're just making sure all assigned issues are actually in progress. :) If you wish to continue working on this task or picking up another feel free to do so, you're always welcome to contribute.

**Comment by p-wysocki** [comment]
It's okay with me, but sadly I currently do not have proper permissions to assign/unassign people to issues created in the NNCF repository. @vshampor could you please help here?

**Comment by Grimoors** [comment]
@DaniAffCH  I am keen to continue work on this.

**Comment by andrey-churkin** [comment]
The assignee was unassigned due to the lack of activity.

**Comment by DaniAffCH** [comment]
.take

**Comment by DaniAffCH** [comment]
Hi, I just opened a PR for this
