### ISSUE TITLE
[Good First Issue][NNCF]: Dump actual_subset_size to ov.Model

### ISSUE THREAD

**Issue by l-bat** [openvinotoolkit/nncf#2562]
### Context

After applying quantization to the ov.Model in Neural Network Compression Framework ([NNCF](https://github.com/openvinotoolkit/nncf/tree/develop)), the quantization parameters, including `subset_size`, are dumped to the meta section of the OpenVINO IR. `subset_size` represents the size of the dataset used for calibration.
https://github.com/openvinotoolkit/nncf/blob/09960b9b71a58f3277d0964531f8ee08365d7c72/nncf/openvino/quantization/quantize_model.py#L102
 
However, inconsistencies arise when the dataset size is less than the provided or default 'subset_size'. To address this confusion, it is proposed to also dump the `actual_subset_size`, which denotes the number of data samples used to calculate activation statistics. This addition will improve clarity and accuracy in managing quantization parameters and assist in reproducing quantization results.

### What needs to be done?

* Dump `actual_subset_size` parameter to ov.Model meta section.
* Add tests

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)

### Contact points

@l-bat

**Comment by AiGaf1** [comment]
.take

**Comment by andrey-churkin** [comment]
@AiGaf1 Hi, are you still working on this task? Do you need any help? Please inform us if you do not plan to continue working on this task. Thanks!

**Comment by RitikaxShakya** [comment]
Hello! Is this task completed? If not i wish to work on this issue.

**Comment by p-wysocki** [comment]
I reopened the issue due to current assignee's inactivity.

@RitikaxShakya I assigned you.

**Comment by p-wysocki** [comment]
Hello @RitikaxShakya, are you still working on that issue? Do you need any help?

**Comment by awayzjj** [comment]
.take

**Comment by awayzjj** [comment]
Hi @l-bat I created a PR after testing locally, and the XML output is as expected:
<img width="705" alt="截屏2024-06-29 11 46 58" src="https://github.com/openvinotoolkit/nncf/assets/38181615/4509f628-042f-4720-b288-b7e0b5516d93">

I ran the pytest in tests/openvino, and the original tests did not break. But I have 2 questions
1. which file I should edit to add my unit test. 
2. how to implement the unit test, should I check the output XML to verify whether the `actual_subset_size` property exists?

Thank you very much!

**Comment by l-bat** [comment]
Hi @awayzjj! 
Thanks for your contribution!

`calibration_dataset.get_length()` returns the size of the dataset that was provided to the `nncf.quantize` method, however `actual_subset_size` should show the number of data samples that were used to calculate the activation statistics.
In the case of `calibration_dataset.get_length() >= subset_size`, `actual_subset_size` is equal to `subset_size`. Otherwise, `actual_subset_size` must be equal to `calibration_dataset.get_length()`. But it is not possible to use the `get_length()` method if  `__len__()` is not implemented. Please take a look at https://github.com/openvinotoolkit/nncf/blob/e8ea2521663de807d654ae4f375d20c904755061/nncf/common/tensor_statistics/aggregator.py#L50-L53. You can implement the `get_actual_subset_size()` function.

**Comment by l-bat** [comment]
> I ran the pytest in tests/openvino, and the original tests did not break. But I have 2 questions
> 1. which file I should edit to add my unit test.
> 2. how to implement the unit test, should I check the output XML to verify whether the actual_subset_size property exists?

1. You can add test to https://github.com/openvinotoolkit/nncf/blob/e8ea2521663de807d654ae4f375d20c904755061/tests/openvino/native/quantization/test_quantization_pipeline.py
2. You can use the test as an example https://github.com/openvinotoolkit/nncf/blob/e8ea2521663de807d654ae4f375d20c904755061/tests/openvino/native/quantization/test_quantization_pipeline.py#L178-L199

**Comment by awayzjj** [comment]
@l-bat Hi, I've been really busy lately, so I've decided to unassign myself for now. I apologize for any inconvenience this may cause.

**Comment by zina-cs** [comment]
.take
