### ISSUE TITLE
[Good First Issue][NNCF]: dump the ignored scope more gracefully

### ISSUE THREAD

**Issue by ljaljushkin** [openvinotoolkit/nncf#2564]
### Context

NNCF saves parameters of the compression to [OpenVINO IR](https://docs.openvino.ai/2024/documentation/openvino-ir-format.html).
It's done in [dump_parameters](https://github.com/openvinotoolkit/nncf/blob/edd397b01f8c45b976785fa67d425467d80835ae/nncf/openvino/rt_info.py#L20) method using [set_rt_info](https://docs.openvino.ai/2024/api/ie_python_api/_autosummary/openvino.runtime.Model.html#openvino.runtime.Model.set_rt_info) API. 
But the problem is that ignored scope is saved not gracefully - it prints all fields even if they are empty. 
![image](https://github.com/openvinotoolkit/nncf/assets/4014476/a8600094-5acb-4651-b111-05d2a9c473f7)

### What needs to be done?

1) Dump ignored scope in more compact way.

- not dump `<validate value="True" />`
- not dump fields `names`, `patterns` or `types` when they are empty. 
![image](https://github.com/openvinotoolkit/nncf/assets/4014476/e4f05d69-ec52-438a-9e2a-0825c6abe705)
- when all fields empty - dump in one line: `<ignored_scope value=[]>`
![image](https://github.com/openvinotoolkit/nncf/assets/4014476/6880bf60-1145-4392-b685-536f715353c8)

2) Add very lightweight unit test checking the content of <rt_info> for a dummy synthetic model, for example via [get_rt_info](https://docs.openvino.ai/2024/api/ie_python_api/_autosummary/openvino.runtime.Model.html#openvino.runtime.Model.get_rt_info) API. 

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)

### Contact points

@ljaljushkin 

### Ticket

129593

**Comment by Viditagarwal7479** [comment]
.take

**Comment by Viditagarwal7479** [comment]
Hello @ljaljushkin and @alexsu52 ,

I have corrected it to,
- not dump `<validate value="True" />`
- not dump `names`, `patterns` or `types` when they are empty.

In the case when,
> when all fields empty

The dump is looking like `<ignored_scope value="None" />` is this fine? If not then is there any other way other than modifying the C++ code of [set_rt_info](https://docs.openvino.ai/2024/api/ie_python_api/_autosummary/openvino.runtime.Model.html#openvino.runtime.Model.set_rt_info) API?

**Comment by Viditagarwal7479** [comment]
Hello, never mind, I figured it out!
Now it's dumping `<ignored_scope value="[]" />` when all fields are empty ^^
Will create a PR soon after adding unit tests.
