### ISSUE TITLE
Different accuracy of quantized ResNet-50 on a single GPU

### ISSUE THREAD

**Issue by ljaljushkin** [openvinotoolkit/nncf#260]
Evaluation of ResNet-50 with different batch-sizes may give different accuracy even for INT8 models on a single GPU.
How to reproduce:
```
cd examples/classification
python main.py --data /path/to/imagenet -c=configs/quantization/resnet50_imagenet_int8.json --resume openvino_training_extensions/models/nncf/resnet50_imagenet_int8.pth -m test -b 256
```
Acc1: 76.074 - **[nightly eval tests have a different accuracy]**

```
cd examples/classification
python main.py --data /path/to/imagenet -c=configs/quantization/resnet50_imagenet_int8.json --resume openvino_training_extensions/models/nncf/resnet50_imagenet_int8.pth -m test -b 85
```
Acc1: 76.082

For the lower precision model, it may happen more often even with the same batch size.
```
cd examples/classification
python main.py --data /path/to/imagenet -c=configs/quantization/resnet50_imagenet_mixed_int_hawq.json --resume openvino_training_extensions/models/nncf/resnet50_imagenet_int4_int8.pth -m test -b 256
```
![image](https://user-images.githubusercontent.com/4014476/98574088-8b409080-22c8-11eb-9d20-91b2d84d2587.png)

**Comment by ljaljushkin** [comment]
Can't reproduce it for MobileNet-v2 quantized models

**Comment by vshampor** [comment]
@ljaljushkin is this still reproducible?

**Comment by ljaljushkin** [comment]
@SKholkin can be related

Training of _**tests/data/configs/squeezenet1_1_cifar10_rb_sparsity_int8.json**_ in DDP gives different accuracy on GPU's.
* Acc@1 19.681 Acc@5 64.613
* Acc@1 19.671 Acc@5 64.613

But single GPU evaluation looks stable.

**Comment by vshampor** [comment]
Does not seem to be impactful.
