### ISSUE TITLE
[Good First Issue][NNCF]: Remove compress_to_fp16=False from examples

### ISSUE THREAD

**Issue by alexsu52** [openvinotoolkit/nncf#2668]
### Context

Using `compress_to_fp16=False` when saving a **compressed/quantized** OpenVINO model is no longer required following changes to OpenVINO https://github.com/openvinotoolkit/openvino/pull/23609 that are included in the OpenVINO 2024.1.0 release.

This issue suggests removing `compress_to_fp16=False` from the [examples](https://github.com/openvinotoolkit/nncf/tree/develop/examples) to simplify the examples.

Example of using `compress_to_fp16=False` in example:
https://github.com/openvinotoolkit/nncf/blob/daec271ae331803681fad433f0d4297c64a3d136/examples/post_training_quantization/openvino/mobilenet_v2/main.py#L145

### What needs to be done?

- Removing `compress_to_fp16=False` attribute when saving a **compressed/quantized** OpenVINO model in [examples](https://github.com/openvinotoolkit/nncf/tree/develop/examples)
- Check that these changes do not change metrics of the examples. [Example tests](https://github.com/openvinotoolkit/nncf/tree/develop/tests/cross_fw/examples) should pass.

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@alexsu52 

### Ticket

ref: 137146

**Comment by truhinnm** [comment]
Hello, I'm new to contributing, can i take this one? I'd be happy to work on this project!

**Comment by alexsu52** [comment]
Hello @truhinnm! Thank you for your interest in our project.  I assigned to you this issue. 

If you have any questions let me know.

**Comment by alexsu52** [comment]
Thanks for the contribution https://github.com/openvinotoolkit/nncf/pull/2682!
