### ISSUE TITLE
AttributeError: 'list' object has no attribute 'keys' when executing yolov8_quantize_with_accuracy_control example

### ISSUE THREAD

**Issue by openvino-book** [openvinotoolkit/nncf#2669]
### 🐛 Describe the bug

OS = **Windows 11** 23H2 (22631.3447)

Reproduce the error by following the [yolov8_quantize_with_accuracy_control/README.md](https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/README.md)

```
git clone https://github.com/openvinotoolkit/nncf.git
cd nncf
pip install .
pip install -r requirements.txt
python main.py
```
Then get the errro as below: 
> File "C:\Users\OV\anaconda3\envs\ptq\Lib\site-packages\ultralytics\models\yolo\segment\val.py", line 141, in update_metrics
    for k in self.stats.keys():
             ^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'keys'

![1714999187651](https://github.com/openvinotoolkit/nncf/assets/128127436/16fe1715-f852-4d33-8dac-58e731fe4e6b)

### Environment

OS = **Windows 11** 23H2 (22631.3447)
```
git clone https://github.com/openvinotoolkit/nncf.git
cd nncf
pip install .
pip install -r requirements.txt
```

### Are you going to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by avitial** [comment]
@openvino-book just tested on master branch (commit: cf73597d05a02a947429488ef695c27933879160) and the example is working fine. Please share the commit you used or simply try again using the latest master. If the issue persists, please share the output of `pip freeze` and the nncf commit used.

![image](https://github.com/openvinotoolkit/nncf/assets/20826577/39052352-c751-4d48-b026-547dd61f6f7d)

**Comment by dxrsgn** [comment]
Had same issue. Guess its something with Yolov8. Fixed this by changing line 149 in main.py from:
`validator.stats = []`
to:
`validator.stats = dict(tp=[], conf=[], pred_cls=[], target_cls=[])`

**Comment by dxrsgn** [comment]
Had this problem, guess its something with new Yolov8 versions. Fixed this by changing in main.py line 149 from:
`validator.stats = []`
to:
`validator.stats = dict(tp=[], conf=[], pred_cls=[], target_cls=[])`

**Comment by andrey-churkin** [comment]
@openvino-book I followed the instruction [yolov8_quantize_with_accuracy_control/README.md](https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/README.md) and I can't reproduce the issues. I checked both Ubuntu and Windows.

NNCF version: 47187e5bbaef678508fdfdc980b258fc4e32d3db

I closed the issue. Please feel free to reopen it if it still does not work for you, and share the output of `pip freeze`, your python version, and the NNCF commit used.

**Comment by openvino-book** [comment]
> @openvino-book I followed the instruction [yolov8_quantize_with_accuracy_control/README.md](https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/README.md) and I can't reproduce the issues. I checked both Ubuntu and Windows.
> 
> NNCF version: [47187e5](https://github.com/openvinotoolkit/nncf/commit/47187e5bbaef678508fdfdc980b258fc4e32d3db) Python: 3.9
> 
> I closed the issue. Please feel free to reopen it if it still does not work for you, and share the output of `pip freeze`, your python version, and the NNCF commit used.

Sure! the problem is fixed by @andrey-churkin 's soluiton, to change the [L149](https://github.com/openvinotoolkit/nncf/blob/b8b3e3b18055c1d326a7cc35c8a3ef73ea7bfa11/examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/main.py#L149) to
```
validator.stats = dict(tp_m=[], tp=[], conf=[], pred_cls=[], target_cls=[])
```
I has submitted a PR to you
