### ISSUE TITLE
Throw an error if frozen layers are not specified in ignored_scope

### ISSUE THREAD

**Issue by ljaljushkin** [openvinotoolkit/nncf#271]
As we discussed, there's no need to compress frozen layers - layers with `requires_grad=False`.

That's why all frozen layers must be explicitly removed from the compression via `ignored_scope` attribute.
If there are frozen layers not specified in `ignored_scope`, the error should happen with the message suggesting to add frozen layers to `ignored_scope` or to make them unfrozen.

That should make things more clear and transparent. AFAIK, the request is coming from mm_detection cases.
@aleksei-kashapov, @AlexKoff88, @vanyalzr, @alexsu52, @vshampor

**Comment by vshampor** [comment]
Related to #201?

**Comment by ljaljushkin** [comment]
sorry, forgot about this
