### ISSUE TITLE
When will there be a c++ interface?

### ISSUE THREAD

**Issue by qq978358810** [openvinotoolkit/nncf#2753]
### 🚀 Feature request

When will there be a c++ interface?

### Are you going to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MaximProshin** [comment]
Hi @qq978358810 , we don't have plans for C++ interface. How that will help you compared to Python? Model compression is an offline step, so usually you don't integrate it to any application code.

**Comment by MaximProshin** [comment]
@qq978358810 , I close this issue. If you want us to consider it in future development, please provide more details on how you plan to use it and why the Python API doesn't suit you.
