### ISSUE TITLE
[Good First Issue][NNCF][TorchFX]: Test model transformer

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#2775]
Greetings🐱! As a part of https://github.com/openvinotoolkit/nncf/issues/2766 TorchFX PTQ backend support, we are gladly presenting to you following issue

### Context

The task is to cover FXModelTransformer by simple unit tests as it done for other backends:
 https://github.com/openvinotoolkit/nncf/blob/develop/tests/onnx/test_model_transformer.py
 

### What needs to be done?

Unit tests in file `tests/torch/fx/test_model_transformer.py` :
* test_leaf_module_insertion_transformation
* test_bias_update_transformation
* test_qdq_insertion_transformation

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@daniil-lyakhov

### Ticket

141640

**Comment by awayzjj** [comment]
.take

**Comment by awayzjj** [comment]
@daniil-lyakhov Hi, I wonder if you can push your branch first before merge into develop branch, so I can develop base your branch. Thank you!

**Comment by daniil-lyakhov** [comment]
Hi @awayzjj,

Thank you for your contribution! PR is on review and will be merged soon, I'll keep you updated. Yes, please use tests/torch/fx directory, I forgot to update the issue.

Thanks!

**Comment by daniil-lyakhov** [comment]
Hi @awayzjj, the base PR #2764 was merged, please rebase your cahnges

**Comment by awayzjj** [comment]
@daniil-lyakhov Hi, I attempted to implement the `test_leaf_module_insertion_transformation` as follows, but encountered two problems:
```
import torch
import torch.nn.functional as F
from torch import nn
from torch._export import capture_pre_autograd_graph

from nncf.common.graph.transformations.commands import TargetType
from nncf.common.graph.transformations.layout import TransformationLayout

def test_leaf_module_insertion_transformation():

    class InsertionPointTestModel(nn.Module):
        def __init__(self):
            super().__init__()
            self.conv1 = nn.Conv2d(1, 1, 1, 1)
            self.linear_wts = nn.Parameter(torch.FloatTensor(size=(100, 100)))
            self.conv2 = nn.Conv2d(1, 1, 1, 1)
            self.relu = nn.ReLU()

        def forward(self, input_):
            x = self.conv1(input_)
            x = x.flatten()
            x = nn.functional.linear(x, self.linear_wts)
            x = x.reshape((1, 1, 10, 10))
            x = self.conv2(x)
            x = self.relu(x)
            return x
  

    model = InsertionPointTestModel() 
    with torch.no_grad():
        ex_input = torch.ones([1, 1, 10, 10])
        model.eval()
        exported_model = capture_pre_autograd_graph(model, args=(ex_input,))
    print(exported_model.print_readable())
    model = InsertionPointTestModel()
    with torch.no_grad():
        ex_input = torch.ones([1, 1, 10, 10])
        model.eval()
        exported_model = capture_pre_autograd_graph(model, args=(ex_input,))
 
    from nncf.experimental.torch.fx.model_transformer import FXModelTransformer
    from nncf.torch.graph.transformations.commands import PTTargetPoint
    from nncf.experimental.torch.fx.transformations import leaf_module_insertion_transformation_builder
    from nncf.experimental.torch.fx.commands import FXApplyTransformationCommand
    model_transformer = FXModelTransformer(exported_model)

    conv1_node_name = "InsertionPointTestModel/NNCFConv2d[conv1]/conv2d_0"
    target_point = PTTargetPoint(
        target_type=TargetType.OPERATION_WITH_WEIGHTS, target_node_name=conv1_node_name, input_port_id=1
    )
    transformation = leaf_module_insertion_transformation_builder(
        exported_model, [target_point]
    )
    command = FXApplyTransformationCommand(
        transformation
    )
    transformation_layout = TransformationLayout()
    transformation_layout.register(command)
    model_transformer.transform(transformation_layout)
```
1. The tests fail with the following exception:
<img width="1862" alt="截屏2024-08-03 20 50 38" src="https://github.com/user-attachments/assets/d25ee508-60d4-4cf5-bd13-37ba4a7abb6f">

2. I have to place the following imports after `exported_model = capture_pre_autograd_graph(model, args=(ex_input,))` 
```
    from nncf.experimental.torch.fx.model_transformer import FXModelTransformer
    from nncf.torch.graph.transformations.commands import PTTargetPoint
    from nncf.experimental.torch.fx.transformations import leaf_module_insertion_transformation_builder
    from nncf.experimental.torch.fx.commands import FXApplyTransformationCommand
```
or it raises an error:
<img width="2044" alt="截屏2024-08-03 20 54 01" src="https://github.com/user-attachments/assets/f794afb4-f13c-4922-8dfd-cc188289e422">

Could you give me some suggestions? Thank you very much!

**Comment by rk119** [comment]
@awayzjj you defined the variable `conv1_node_name` incorrectly. If you define it correctly as `conv2d`, your test shall pass. The node names are different for Torch FX backend. I'd suggest setting a `breakpoint()` in the function `get_graph_node_by_name` and using pdb to view the node names. This helped me.

**Comment by awayzjj** [comment]
@rk119 Thank you so much! Your suggestions does work!

**Comment by daniil-lyakhov** [comment]
@awayzjj, that's ok, thank you for letting us know!

**Comment by daniil-lyakhov** [comment]
PR #2920

**Comment by zina-cs** [comment]
.take

**Comment by daniil-lyakhov** [comment]
@zina-cs, sorry for inconvenience, but this good first issue should have been closed. Big sorry 🙁
