### ISSUE TITLE
[Good First Issue][NNCF][TorchFX]: Test statistic aggregator

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#2777]
Greetings🐱! As a part of  https://github.com/openvinotoolkit/nncf/issues/2766 TorchFX PTQ backend support, we are gladly presenting to you following issue

### Context

Implement `TemplateTestStatisticsAggregator` as it done for other backends (example: https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/test_statistics_aggregator.py)

### What needs to be done?

*  `TemplateTestStatisticsAggregator` test class implementation for the TorchFX PTQ backend in `tests/torch_fx/test_statistics_aggregator.py` file

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@daniil-lyakhov

### Ticket

141640

**Comment by anzr299** [comment]
@rk119

**Comment by rk119** [comment]
.take

**Comment by rk119** [comment]
@daniil-lyakhov I have created a PR #2856 for this issue.

**Comment by daniil-lyakhov** [comment]
@rk119, thank you for the contribution!

**Comment by daniil-lyakhov** [comment]
@rk119, thank you for the contribution!
