### ISSUE TITLE
[TorchFX] TorchFX metatypes support

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#2778]
### 🚀 Feature request

The task is to
* Map following types to a metatypes: index, linalg_vector_norm, clamp_min, clamp
* Add nncf graph tests  to cover nncf graph building for target models scope: resnet18, mobilenet_v3_small, vit_b_16, swin_v2_s (from Torchvision), YoloV8(from ultralytics)

https://github.com/openvinotoolkit/nncf/pull/2764

### Feature Use Case

To enable PTQ quantization for `torch.fx.GrpaphModule` models 

### Are you going to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by anzr299** [comment]
.take
