### ISSUE TITLE
Can I export an onnx model with true int-8 or mixed-precision foramt weights 

### ISSUE THREAD

**Issue by Jonxjdong** [openvinotoolkit/nncf#280]
As refered in title, can I get the exported onnx model with weight values in integer format, without the FakeQuantize node?

**Comment by AlexKoff88** [comment]
Hi, Jonxjdong. Unfortunately, you can't. Only FakeQuantize and QuantizeLinear/DequantizeLinear export is available right now. Actually, right now there is a limitation that does not allow having the full support of such export. The thing is that per-channel quantization of weights was introduced in ONNX opset v13 which is not supported by PyTorch right now. So the support of export to true INT8 should cost some effort. But if you would like to contribute, please welcome.
BTW, the interpretation rules of FakeQuantize are quite simple but of course, some transformations are required to do them.

**Comment by AlexKoff88** [comment]
P.S. OpenVINO is able to dump a runtime graph that corresponds to the real INT8 model. Moreover, you can do it using [OpenVINO DL Workbench](https://docs.openvinotoolkit.org/latest/workbench_docs_Workbench_DG_Introduction.html) which is a web-based tool.

**Comment by kchechil** [comment]
Please feel free to open a new ticket if there are more questions.

**Comment by GitForKriti** [comment]
Hi all,

can I get the exported onnx model with weight values in integer format, without the FakeQuantize nodes now?
or ,how to load the same model with fakequantize nodes with opencv
