### ISSUE TITLE
[NNCF][TorchFX]: Test Fast Bias Correction algorithm

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#2809]
### 🚀 Feature request

Greetings🐱! As a part of https://github.com/openvinotoolkit/nncf/issues/2766 TorchFX PTQ backend support, we are gladly presenting to you following issue:

Implement `TemplateTestFBCAlgorithm` as it done for other backends(example: /home/dlyakhov/Projects/nncf/tests/torch/ptq/test_fast_bias_correction.py)

### Are you going to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by anzr299** [comment]
. take
