### ISSUE TITLE
Make sure a Mask-RCNN/Faster-RCNN model is properly exported to ONNX

### ISSUE THREAD

**Issue by vanyalzr** [openvinotoolkit/nncf#285]

**Comment by vshampor** [comment]
@aleksei-kashapov is this resolved with #363?

**Comment by aleksei-kashapov** [comment]
> @aleksei-kashapov is this resolved with #363?

Currently, export to ONNX is not supported by mmdet team (https://github.com/open-mmlab/mmdetection/issues/4247), therefore it is not supported in our patch. There are **ssd300** and **retinanet_r50_fpn_1x** that could be exported via our patch.
However, Mask-RCNN/Faster-RCNN models could be exported via our mmdet fork (https://github.com/openvinotoolkit/mmdetection)
