### ISSUE TITLE
Fix AC configs for SSD models in detection sample

### ISSUE THREAD

**Issue by vanyalzr** [openvinotoolkit/nncf#286]
[Current AC configs](https://github.com/openvinotoolkit/nncf/blob/develop/tests/data/ac_configs/ssd300_vgg_voc.yml) for end-to-end testing for SSD models specify VOC2012 dataset for validation. We report metrics for the VOC2007 val dataset, so configs should be updated.

NB: VOC2007 annotation conversion settings are not available in `dataset_definitions.yml`, so they should be added to the main config.

**Comment by vanyalzr** [comment]
@pfinashx

**Comment by pfinashx** [comment]
We decided to update NNCF eval with execution on VOC2012, this task in progress.
VOC2007 is not approved for use.

**Comment by vanyalzr** [comment]
All right, please make sure that the reference metrics in PyTorch are also for VOC2012 val in tests.
