### ISSUE TITLE
[Good First Issue][NNCF]: [TorchFX] Test PTQ MinMax parameters

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#2873]
Greetings🐱! As a part of https://github.com/openvinotoolkit/nncf/issues/2766 TorchFX PTQ backend support, we are gladly presenting to you following issue:

Implement TemplateTestPTQParams, TemplateTestQuantizerConfig  as it done for other backends(example: https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/ptq/test_ptq_params.py)

### Example Pull Requests

https://github.com/openvinotoolkit/nncf/pull/2856

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@daniil-lyakhov 

### Ticket

#2766

**Comment by rk119** [comment]
.take

**Comment by daniil-lyakhov** [comment]
Hi, @rk119 , do you still plan to contribute?

**Comment by rk119** [comment]
> Hi, @rk119 , do you still plan to contribute?

Yes. I do.

**Comment by mlukasze** [comment]
@rk119 do you need any help with task? do not hesitate to ask :)

**Comment by rk119** [comment]
> @rk119 do you need any help with task? do not hesitate to ask :)

Hi @mlukasze, I will try to look into this issue over the weekend as I am still eager to continue. If I fail to do so due to lack of availability, then I will unassign myself. I hope it is alright to do so? :)

**Comment by mlukasze** [comment]
if you want to continue we can wait for you, thanks :)

**Comment by rk119** [comment]
> if you want to continue we can wait for you, thanks :)

Oh alright, thank you so much!

**Comment by rk119** [comment]
Hi @daniil-lyakhov,

I am facing an issue trying to implement [test_unified_scales_command_creation](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_ptq_params.py#L351) . I am unable to verify and access the quantizer parameters in [check_unified_scale_layout](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_ptq_params.py#L163), since the [create_unified_scales_quantizers_insertion_commands](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/torch_fx_backend.py#L297) in Torch FX backend returns transformations with only params `priority` and `transformation_fn`. I would appreciate some guidance in this. Thank you!

**Comment by daniil-lyakhov** [comment]
Hi @rk119, please use the `__closure__` attribute of the `transformation_fn` callable object. It will return cells for each captured value. To access cells value please use `cell_contents` attribute.
Ref: https://docs.python.org/3/reference/datamodel.html#special-read-only-attributes
https://stackoverflow.com/a/55320885/9183892

**Comment by rk119** [comment]
> Hi @rk119, please use the `__closure__` attribute of the `transformation_fn` callable object, it will return cells for each captured value. To access cells value please use `cell_contents` attribute. Ref: https://docs.python.org/3/reference/datamodel.html#special-read-only-attributes https://stackoverflow.com/a/55320885/9183892

Ah yes! Thank you. :)

**Comment by rk119** [comment]
Hi @daniil-lyakhov,

I noticed that in the example reference test for this issue, the [test_range_estimator_per_channel](https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/ptq/test_ptq_params.py#L145) parameter in the `test_params` is defined but not used anywhere in the test cases in [TemplateTestPTQParams](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_ptq_params.py) or I could be mistaken. How would you suggest I address this?

**Comment by daniil-lyakhov** [comment]
Hi @rk119, please just skip this key in the FX tests implementation and keep other tests as it is

**Comment by rk119** [comment]
Hi @daniil-lyakhov, I opened a PR #2989 for this issue.

**Comment by alexsu52** [comment]
@rk119, thanks for the contribution!
