### ISSUE TITLE
Print the actual pruning rate

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/nncf#290]
Add calculation of average pruning rate for the whole model (no for pruning layers) and print it after the table with per-layers statistics.

**Comment by AlexKoff88** [comment]
cc'ed @mkaglins

**Comment by AlexKoff88** [comment]
We also need to revise information that is printed after each epoch. I found some strange numbers that make it unclear. Just check out:

+---------------+---------------+------------+-------------+-------+-----------+
|     Name      |   Weight's    | Mask Shape | Mask zero % |  PR   | Filter PR |
|               |     Shape     |            |             |       |           |
+===============+===============+============+=============+=======+===========+
+---------------+---------------+------------+-------------+-------+-----------+
| MobileNetV2/S | [64, 192, 1,  | [64]       | 12.500      | 0     | 0         |
| equential[fea | 1]            |            |             |       |           |
| tures]/Invert |               |            |             |       |           |
| edResidual[7] |               |            |             |       |           |
| /Sequential[c |               |            |             |       |           |
| onv]/NNCFConv |               |            |             |       |           |
| 2d[2]         |               |            |             |       |           |
+---------------+---------------+------------+-------------+-------+-----------+
| MobileNetV2/S | [64, 384, 1,  | [64]       | 12.500      | 0     | 0         |
| equential[fea | 1]            |            |             |       |           |
| tures]/Invert |               |            |             |       |           |
| edResidual[8] |               |            |             |       |           |
| /Sequential[c |               |            |             |       |           |
| onv]/NNCFConv |               |            |             |       |           |
| 2d[2]         |               |            |             |       |           |
+---------------+---------------+------------+-------------+-------+-----------+
| MobileNetV2/S | [64, 384, 1,  | [64]       | 12.500      | 0     | 0         |
| equential[fea | 1]            |            |             |       |           |
| tures]/Invert |               |            |             |       |           |
| edResidual[9] |               |            |             |       |           |
| /Sequential[c |               |            |             |       |           |
| onv]/NNCFConv |               |            |             |       |           |
| 2d[2]         |               |            |             |       |           |
+---------------+---------------+------------+-------------+-------+-----------+
| MobileNetV2/S | [64, 384, 1,  | [64]       | 12.500      | 0     | 0         |
| equential[fea | 1]            |            |             |       |           |
| tures]/Invert |               |            |             |       |           |
| edResidual[10 |               |            |             |       |           |
| ]/Sequential[ |               |            |             |       |           |
| conv]/NNCFCon |               |            |             |       |           |
| v2d[2]        |               |            |             |       |           |
+---------------+---------------+------------+-------------+-------+-----------+
| MobileNetV2/S | [96, 384, 1,  | [96]       | 16.667      | 0.083 | 0.083     |
| equential[fea | 1]            |            |             |       |           |
| tures]/Invert |               |            |             |       |           |
| edResidual[11 |               |            |             |       |           |
| ]/Sequential[ |               |            |             |       |           |
| conv]/NNCFCon |               |            |             |       |           |
| v2d[2]        |               |            |             |       |           |
+---------------+---------------+------------+-------------+-------+-----------+

I don't understand why, for example, "Mask zero" is 12.5%, while "PR" and "Filter PR" are 0. @mkaglins to comment.

**Comment by mkaglins** [comment]
@AlexKoff88 That means weights aren't zeroed for some reason (or became non-zero).
This is strange since applying masks and stats calculation are near in the pipeline (I will re-check it).

**Comment by AlexKoff88** [comment]
Maybe this issue is related to #353. Anyway, we need to change the column names and even the set of columns keeping only something like "Expected PR", "Actual PR".

**Comment by mkaglins** [comment]
@AlexKoff88 you suggest delete `Filter PR` or just rename it too?

**Comment by AlexanderDokuchaev** [comment]
Will added actual pruning rate in flops

**Comment by AlexanderDokuchaev** [comment]
https://github.com/openvinotoolkit/nncf/pull/367
