### ISSUE TITLE
Type mismatch in onnx quantize_with_accuracy_control validation_fn

### ISSUE THREAD

**Issue by w4-jinhyeonkim** [openvinotoolkit/nncf#2957]
### 🐛 Describe the bug

`nncf.quantize_with_accuracy_control` has the following type signature:

```python
def quantize_with_accuracy_control(
    ...,
    validation_fn: Callable[[Any, Iterable[Any]], float],
    ...,
) -> TModel:
```

However, when backend is ONNX, validation_fn with the signature above fails.

When we look at `nncf.onnx.quantization.quantize_model.quantize_with_accuracy_control_impl`, it has the following signature:

```python
def quantize_with_accuracy_control_impl(
    ...,
    validation_fn: Callable[[Any, Iterable[Any]], Tuple[float, Union[None, List[float], List[List[TTensor]]]]],
    ...,
) -> onnx.ModelProto:
```

When I tried calling `quantize_with_accuracy_control` with `validation_fn` of type `Callable[[Any, Iterable[Any]], float]`, using ONNX backend, it failed with the following error:

```
Traceback (most recent call last):
  [...]
  File "[...]/quantize_nncf_acc_control.py", line 272, in main
    quantized_model = nncf.quantize_with_accuracy_control(
  File "[...]/site-packages/nncf/quantization/quantize_model.py", line 327, in quantize_with_accuracy_control
    return quantize_with_accuracy_control_impl(
  File "[...]/site-packages/nncf/onnx/quantization/quantize_model.py", line 136, in quantize_with_accuracy_control_impl
    initial_metric_results = evaluator.collect_metric_results(model, validation_dataset, model_name="initial")
  File "[...]/site-packages/nncf/quantization/algorithms/accuracy_control/evaluator.py", line 332, in collect_metric_results
    metric, values_for_each_item = self.validate_prepared_model(prepared_model, dataset)
  File "[...]/site-packages/nncf/quantization/algorithms/accuracy_control/evaluator.py", line 164, in validate_prepared_model
    metric, values_for_each_item = self._validation_fn(prepared_model.model_for_inference, validation_dataset)
TypeError: cannot unpack non-iterable float object
```

When I tried calling `quantize_with_accuracy_control` with `validation_fn` of type `Callable[[Any, Iterable[Any]], tuple[float, None]]`, using ONNX backend, it succeeded.

### Environment

NNCF 2.12.0

### Are you going to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MaximProshin** [comment]
@andrey-churkin @kshpv please take a look.

**Comment by andrey-churkin** [comment]
@w4-jinhyeonkim Thanks for reporting the problem. I'll check and return shortly with an update.

**Comment by w4-jinhyeonkim** [comment]
@andrey-churkin Yes, it does
Good job for quick response & good luck
