### ISSUE TITLE
Compressed Graph doesn't reflect merged quantizers

### ISSUE THREAD

**Issue by vuiseng9** [openvinotoolkit/nncf#331]
**Reproduce Issue:**
1. Run `resnet50_imagenet_int8.json` with `target_device: "VPU"`
1. Run following snippet after `create_compressed_model`.
    ```python
    quantize_nxnodes = []
    g = model.get_graph()
    for nxnode, node_dict in g._nx_graph.nodes.items():
        if 'symmetric_quantize' in nxnode:
            quantize_nxnodes.append(nxnode)
    print("#Quantize nodes in graph: {}".format(len(quantize_nxnodes)))
    print("#QuantizeId: {}".format(len(compression_ctrl.all_quantizations.items())))
    ```
**Output:**
```
#Quantize nodes in graph: 125
#QuantizeId: 121
```

The redundant quantize nodes are 25, 80, 152, 258.

![resnet50-vpu-compressed_graph](https://user-images.githubusercontent.com/15026897/101320601-fe74fc80-389e-11eb-93db-a2a4bcb6ff92.png)

**Comment by vuiseng9** [comment]
@ljaljushkin

**Comment by ljaljushkin** [comment]
Hi VS!

It doesn't look like an issue, because of the unified scales feature for VPU config.
It assigns a single instance of the `BaseQuantizer` module for different FQ nodes in the graph. This provides common quantization parameters (input_low, input_range or scale) during the training. Now it's implemented not via merging of FQ, which would be more obvious IMHO - each node corresponds to a single quantizer. Probably, @vshampor knows some pitfalls with that approach.
![image](https://user-images.githubusercontent.com/4014476/101324418-48e48200-387b-11eb-935d-da6b400d4a2c.png)

**Comment by vuiseng9** [comment]
@ljaljushkin Thanks for the quick response! It is correct functionally (instance of quantizer module). I am guessing that it is only a disconnection to final representation of compressed graph. IMHO, compressed graph should correspond to base quantizer as user could possibly refer it for debugging/visualiztion.

**Comment by vshampor** [comment]
@vuiseng9 the compressed_graph.dot and original_graph.dot are currently pretty much raw representations of the NNCFGraph that is built and updated as the model is executing its operations. Each node is a call of the wrapped operator - not a call of a module. In fact, there is no explicit information about module boundaries and locations in this graph. The compressed_graph.dot visualization may be extended in the future, but it does not seem that anything from what is visualized currently would be cut, rather, the visualization would be extended e.g. with the information about operations that share a single compression module.

**Comment by vuiseng9** [comment]
Got it @vshampor @ljaljushkin . Any mechanism/meta information to know if a quantizer module are being shared?

**Comment by vuiseng9** [comment]
I guess there is no direct way since you mention there is no explicit information about module boundaries.

**Comment by vshampor** [comment]
@vuiseng9 the operations graph does not store this information, but the controller does. Check the `NonWeightQuantizerInfo` structs as contained in `QuantizationController.non_weight_quantizers`, namely `NonWeightQuantizerInfo.affected_ia_op_exec_contexts`. This list will store all node addresses corresponding to a single quantizer module. Probably should add a method to the controller that queries an insertion location in the graph and returns the actual quantizer module reference.

**Comment by vuiseng9** [comment]
Thanks @vshampor @ljaljushkin. 

For completeness, attaching sample to access the information as you suggested.

```python
g = model.get_graph()

for nwq_id, nwq_info in compression_ctrl.non_weight_quantizers.items():
    if len(nwq_info.affected_ia_op_exec_contexts) > 1:
        print("\nShared Non-Weight QuantizerId: {}".format(str(nwq_id)))
        for ia_op_exc_ctx in nwq_info.affected_ia_op_exec_contexts:
            print("\tAffected Node: {}".format(g.get_node_id_by_iap_context(ia_op_exc_ctx)))
```

```
Shared Non-Weight QuantizerId: ResNet/Sequential[layer1]/Bottleneck[0]/BatchNorm2d[bn3]/batch_norm_0
	Affected Node: 20 ResNet/Sequential[layer1]/Bottleneck[0]/BatchNorm2d[bn3]/batch_norm
	Affected Node: 24 ResNet/Sequential[layer1]/Bottleneck[0]/Sequential[downsample]/BatchNorm2d[1]/batch_norm

Shared Non-Weight QuantizerId: ResNet/Sequential[layer2]/Bottleneck[0]/BatchNorm2d[bn3]/batch_norm_0
	Affected Node: 75 ResNet/Sequential[layer2]/Bottleneck[0]/BatchNorm2d[bn3]/batch_norm
	Affected Node: 79 ResNet/Sequential[layer2]/Bottleneck[0]/Sequential[downsample]/BatchNorm2d[1]/batch_norm

Shared Non-Weight QuantizerId: ResNet/Sequential[layer3]/Bottleneck[0]/BatchNorm2d[bn3]/batch_norm_0
	Affected Node: 147 ResNet/Sequential[layer3]/Bottleneck[0]/BatchNorm2d[bn3]/batch_norm
	Affected Node: 151 ResNet/Sequential[layer3]/Bottleneck[0]/Sequential[downsample]/BatchNorm2d[1]/batch_norm

Shared Non-Weight QuantizerId: ResNet/Sequential[layer4]/Bottleneck[0]/BatchNorm2d[bn3]/batch_norm_0
	Affected Node: 253 ResNet/Sequential[layer4]/Bottleneck[0]/BatchNorm2d[bn3]/batch_norm
	Affected Node: 257 ResNet/Sequential[layer4]/Bottleneck[0]/Sequential[downsample]/BatchNorm2d[1]/batch_norm
```
