### ISSUE TITLE
Corrupted Images of Mock Dataset in Linux System

### ISSUE THREAD

**Issue by vuiseng9** [openvinotoolkit/nncf#358]
On windows, the images are usable but in linux. Wonder if there is inherent step or workaround for this.

We may need [this](https://www.hardwaretutorials.com/programming/fixing-image-corruption-in-git). But the current content in `.gitattributes` does have png-related entry. 

@ljaljushkin

**Comment by vuiseng9** [comment]
do we need git-lfs?

**Comment by ljaljushkin** [comment]
> do we need git-lfs?

yes, it's required to load images for mock datasets. git-lfs usually is needed for such files, which are not source code.

**Comment by vuiseng9** [comment]
Sorry, false alarm. tested working via lfs.
