### ISSUE TITLE
Quantization presets for INT8 quantization.

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/nncf#361]
In POT we have quantization presets for **INT8 quantization** that substantially simplifies the configuration and switching between different quantization schemes. As I understood from the existing samples of configs, now we have a symmetric scheme exposed by default. But in order to switch to the asymmetric one, the user needs to specify it explicitly for weights and activations.
I suggest implementing the following quantization presents for ANY, CPU, and GPU target_devices:
- "performance" - a default preset that stands for symmetric weights and activations.
- "mixed" - a preset that stands for symmetric weights and asymmetric activations.
These presets should have no impact on the VPU target_device.

**Comment by vshampor** [comment]
@AlexKoff88 why is it exactly that the VPU config should not be affected by these presets?

**Comment by AlexKoff88** [comment]
@vshampor, since the only change between two presets is the activations quantization mode (symmetric vs. asymmetric) it should have no impact on VPU because it has only one option for INT8 activations quantization, namely asymmetric one.
