### ISSUE TITLE
Ensure proper filter pruning interaction with per-channel quantization

### ISSUE THREAD

**Issue by vshampor** [openvinotoolkit/nncf#406]
When applying both filter pruning and per-channel quantization to a model and then attempting to export the model, the per-channel scales of the quantizers (either activation or weight quantizers) must be also adjusted in accordance with the pruned dimensions of underlying tensors.

**Comment by AlexKoff88** [comment]
The decision was to have an implementation of "actual" pruning in OpenVINO. Once it is implemented, NNCF should only export the model with corresponding zero filters. So far, we need only to handle errors if someone decides to export a pruned-quantized model.

**Comment by AlexanderDokuchaev** [comment]
JIRA CVS-42179
