### ISSUE TITLE
Invalid quantization metrics: placed AQs more than potential ones

### ISSUE THREAD

**Issue by ljaljushkin** [openvinotoolkit/nncf#408]
steps to reproduce on top of the develop branch with small corrections 
https://github.com/ljaljushkin/nncf_pytorch/commit/457ba2cab30a46c074d9953cd10676137dd25339

$ cd examples/classification
$ python main.py -c=configs/mixed_precision/squeezenet1_1_imagenet_mixed_int_hawq.json ...
![image](https://user-images.githubusercontent.com/4014476/104917266-3e51f800-59a4-11eb-8322-3370f5f8a20f.png)

**Comment by ljaljushkin** [comment]
it would be also great to have the rows sorted in some order to simplify the comparison of logs from different runs.
currently, the order of rows is arbitrary and different from run to run

**Comment by asenina** [comment]
No reproduced on develop after merge #302 .
