### ISSUE TITLE
Transformers quantization improvement

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/nncf#419]
In order to get maximum performance, it is required to quantize MatMul operations with non-constant inputs, e.g. MatMul that calculates dot products for Query and Key. Potentially, we can also quantize MatMul that applies attention mask to the Value but it may affect the final accuracy.

Note: since both inputs are dynamic, it is better to quantize such operations using symmetric scheme (signed). It should be seamlessly run in OpenVINO.

**Comment by vshampor** [comment]
Tracked elsewhere.
