### ISSUE TITLE
Repeated sota checkpoints test_eval launch failure

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#427]
During testing I notice that second launch of TestSotaCheckpoints::test_eval assert keyerror because metric_dump directrory isn't empty. This hasn't any impact on CI work pipeline but appear during hand testing.

Do we need to fix it and clean metrics_dump dir every launch or that's ok?

**Comment by daniil-lyakhov** [comment]
I can patch it if needed

**Comment by vshampor** [comment]
@daniil-lyakhov please provide a PR so that I could review it.

**Comment by daniil-lyakhov** [comment]
I have a suggestion: let's add new parameter --metrics-dump-dir with default value `os.dir.join(PROJECT_ROOT,"test_results","metrics_dump" + str(timestamp))`. If this dir isn't empty - test will be failed

**Comment by vshampor** [comment]
Closed via #445
