### ISSUE TITLE
docker/gpu/Dockerfile is outdated, there is no nn-compression-framework folder.

### ISSUE THREAD

**Issue by wei1tang** [openvinotoolkit/nncf#429]
It shows /home/nncf/nn-compression-framework/ in https://github.com/openvinotoolkit/nncf/blob/develop/docker/gpu/Dockerfile 
line 48: "ENTRYPOINT cd /home/nncf/nn-compression-framework/ && python setup.py install  && bash".
But I did not find the nn-compression-framework folder.

**Comment by FyodorK** [comment]
PR has been created https://github.com/openvinotoolkit/nncf/pull/436

**Comment by vshampor** [comment]
@wei1tang the Dockerfile has been updated. Could you please try again and see if it works for you now?

**Comment by wei1tang** [comment]
@vshampor I have tested the Dockerfile and it will not run successfully when using Chinese network.
According to the response of https://github.com/NVIDIA/nvidia-docker/issues/969#issuecomment-703192434, I solve this problem. I think this method is very useful for Chinese customers. The changes are as follows：
'''
RUN echo "deb https://mirrors.aliyun.com/nvidia-cuda/ubuntu1804/x86_64/ ./" > /etc/apt/sources.list.d/cuda.list

#RUN curl -fsSL https://mirrors.aliyun.com/nvidia-cuda/ubuntu1804/x86_64/7fa2af80.pub | apt-key add -
# Download https://mirrors.aliyun.com/nvidia-cuda/ubuntu1804/x86_64/7fa2af80.pub and save it to nncf/docker/gpu
COPY ./7fa2af80.pub /tmp/7fa2af80.pub
RUN apt-key add /tmp/7fa2af80.pub

RUN echo "" > /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-updates main restricted universe multiverse" >> /etc/apt/sources.list&& \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-security main restricted universe multiverse" >> /etc/apt/sources.list

RUN apt-get update && apt-get install -y --no-install-recommends \
        apt-transport-https \
        git && \
rm -rf /var/lib/apt/lists/*
'''

**Comment by wei1tang** [comment]
There is another error: " Could not load dynamic library 'libcusolver.so.10' with official TF 2.4, even though it's installed "
From https://github.com/tensorflow/tensorflow/issues/45848#issuecomment-766150992 
I use nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04 to build images, and do follows:
```
apt-get update
apt-get install -y libgl1-mesa-glx vim gcc
apt-get install -y libglib2.0-0

pip3 install tensorflow-gpu
pip3 uninstall protobuf
pip3 uninstall google
pip3 install google
pip3 install protobuf
pip3 install tensorflow_datasets
pip3 install tensorflow-addons
pip3 install pycocotools
pip3 install opencv-python

export PYTHONPATH="/home/nncf"
```
can go to nncf/beta/examples/tensorflow/object_detection run retinanet sample.

**Comment by AlexKoff88** [comment]
cc'ed @alexsu52

**Comment by alexsu52** [comment]
@wei1tang, NNCF with TensorFlow Backend (NNCF TF) requires tensorflow==2.3.1 and does not support TF 2.4. All requirements for NNCF TF [here](https://github.com/openvinotoolkit/nncf/blob/develop/beta/requirements.txt).

We plan to provide a GPU Dockerfile with TensorFlow support in the NNCF TF stable release. I use the following GPU [Dockerfile](https://github.com/alexsu52/nncf/blob/as/docker/beta/docker/gpu/Dockerfile) for NNCF TF.

_I should note that NNCF TF is an experimental implementation of the Neural Network Compression Framework for TensorFlow. and will be subject to change without notice._

**Comment by wei1tang** [comment]
@alexsu52  Thanks
