### ISSUE TITLE
Do you have any plan to support YOLOv4?

### ISSUE THREAD

**Issue by 942860759** [openvinotoolkit/nncf#433]
As you can  see https://paperswithcode.com/sota/object-detection-on-coco, YOLOv4-P7 ranked second while RetinaNet ranked 18.
I want to use NNCF to optimize yolov4, and apply on my project.
Do you have any plan to support YOLOv4?

**Comment by vshampor** [comment]
@942860759 there are no direct obstructions to your trying to use NNCF for yolov4. Could you please try to use NNCF for your use case according to the instructions in the main repo and tell us if you encounter any problems?

**Comment by alexsu52** [comment]
@942860759, the functional support for YOLOv4 in the NNCF with TensorFlow backbone has been added at https://github.com/openvinotoolkit/nncf/pull/52. 

We are also working on extending the object detection example for YOLOv4 (https://github.com/openvinotoolkit/nncf/pull/539), so please stay tuned.

I closed the issue. If you have any questions, please reopen it.
