### ISSUE TITLE
Validating model checkpoint

### ISSUE THREAD

**Issue by negvet** [openvinotoolkit/nncf#467]
Hi

I was able to run

`python main.py -m train --config configs/quantization/mobilenet_v2_imagenet_int8.json --data /data/imagenet/ --log-dir=../../results/quantization/mobilenet_v2_int8/`

and went through 5 epochs. Then I tried

`python main.py -m test --config=configs/quantization/mobilenet_v2_imagenet_int8.json --resume <path_to_trained_model_checkpoint>`

and received the following error:

```
python main.py -m test --config=configs/quantization/mobilenet_v2_imagenet_int8.json --resume ../../results/quantization/mobilenet_v2_int8/mobilenet_v2_imagenet_int8/2021-01-30__18-43-11/mobilenet_v2_imagenet_int8_last.pth --data ~/datasets/imagenet/
Traceback (most recent call last):
  File "main.py", line 554, in <module>
    main(sys.argv[1:])
  File "main.py", line 99, in main
    start_worker(main_worker, config)
  File "/home/negvet/nncf/examples/common/execution.py", line 103, in start_worker
    main_worker(current_gpu=None, config=config)
  File "main.py", line 116, in main_worker
    config.mlflow = SafeMLFLow(config)
  File "/home/negvet/nncf/examples/common/utils.py", line 113, in __init__
    self.safe_call('set_tracking_uri', osp.join(root_log_dir, 'mlruns'))
  File "/home/negvet/nncf/examples/common/utils.py", line 133, in safe_call
    lambda obj: Maybe.from_value(getattr(obj, func)(*args, **kwargs)))
  File "/home/negvet/pytorch_venv/lib/python3.7/site-packages/returns/maybe.py", line 381, in bind
    return function(self._inner_value)
  File "/home/negvet/nncf/examples/common/utils.py", line 133, in <lambda>
    lambda obj: Maybe.from_value(getattr(obj, func)(*args, **kwargs)))
AttributeError: 'NoneType' object has no attribute 'set_tracking_uri'
Exception ignored in: <function SafeMLFLow.__del__ at 0x7f1fd1c628c0>
Traceback (most recent call last):
  File "/home/negvet/nncf/examples/common/utils.py", line 128, in __del__
    self.safe_call('end_run')
  File "/home/negvet/nncf/examples/common/utils.py", line 133, in safe_call
    lambda obj: Maybe.from_value(getattr(obj, func)(*args, **kwargs)))
  File "/home/negvet/pytorch_venv/lib/python3.7/site-packages/returns/maybe.py", line 381, in bind
    return function(self._inner_value)
  File "/home/negvet/nncf/examples/common/utils.py", line 133, in <lambda>
    lambda obj: Maybe.from_value(getattr(obj, func)(*args, **kwargs)))
AttributeError: 'NoneType' object has no attribute 'end_run'
```

As I found out, the problem was with the `returns `package which is used [here](https://github.com/openvinotoolkit/nncf/blob/eb75905b09d5a0269498edb54203bbfa4bbbeb13/examples/common/utils.py#L132). 
I do not remember exactly, but probably I installed it manually with `pip 21.0` after it was not able to be imported during `python main.py -m train ...` first trials.
`Pip 21.0` installed `returns 0.15.0` by default. But only `0.14.0` was able to work (I tried almost all other versions - doesn't work). 
Only when I downgraded `pip install --upgrade returns==0.14.0`, `python main.py -m test ...` started to work.

Probably it is also needed to add the path to data `--data /data/imagenet/` to the classification readme (section 'Validate Your Model Checkpoint')

Best

**Comment by vshampor** [comment]
@negvet the `returns` package version is now strictly specified in `examples/requirements.txt`.
https://github.com/openvinotoolkit/nncf/blob/eb75905b09d5a0269498edb54203bbfa4bbbeb13/examples/requirements.txt#L7
 
Could you please retry the installation using NNCF v1.6 and a clean virtual environment? As for extending the README with missing articles - please open a PR and we'll merge it.

**Comment by negvet** [comment]
@vshampor the list of additional dependencies makes things more clear.
I just missed that `pip install examples/requirements.txt` is stated in the main `README.md`.

I reinstalled the latest NNCF in a clean virtual environment and it works.

I will open the PR.

Thanks!
