### ISSUE TITLE
Facing No Module Name " examples.common" Error

### ISSUE THREAD

**Issue by Praveen-mvp** [openvinotoolkit/nncf#472]
Hi , I am fallowed the steps as you given , but while running the python file for all example , I am facing the same error , But I didn't changed any file or folder, Plz check and help me to solve this error Also attached the errors screen shot.

![nncf-error](https://user-images.githubusercontent.com/78363617/106470105-21e6ad00-64c6-11eb-8714-ba336794fe4f.png)

**Comment by Rock15030110082** [comment]
me too

**Comment by AlexKoff88** [comment]
@Praveen-mvp, just run `export PYTHONPATH=$PYTHONPATH:/home/<your user name>/nncf`, where <your user name> is the user name for home directory. Then run your command again.

**Comment by Praveen-mvp** [comment]
Thanks @AlexKoff88  , It worked but also it returned another error , The Error is passed in PyTorch.If any one know the solution plz help me.

![nncf-pytorch-err](https://user-images.githubusercontent.com/78363617/106558836-729fe980-654a-11eb-8483-b7bd85018e9b.png)

**Comment by AlexKoff88** [comment]
I guess the problem is in Python/PyTorch version. Can you please specify what versions that you use?

**Comment by Praveen-mvp** [comment]
Python Version 2.7.17
PyTorch Version 1.5.0+cpu

**Comment by vshampor** [comment]
@Praveen-mvp NNCF only supports Python 3. Check the https://github.com/openvinotoolkit/nncf#system-requirements section.

**Comment by Praveen-mvp** [comment]
@AlexKoff88  Can You able to give  the link to download Imagenet because , I can't able to download it from the given link.

**Comment by Praveen-mvp** [comment]
And also can you able to post or share the work flow of the nncf like , how it works , it may useful for better understanding

**Comment by AlexKoff88** [comment]
> And also can you able to post or share the work flow of the nncf like , how it works , it may useful for better understanding

I suggest referring to the following [plogpost](https://www.intel.com/content/www/us/en/artificial-intelligence/posts/openvino-nncf.html).

**Comment by AlexKoff88** [comment]
> @AlexKoff88 Can You able to give the link to download Imagenet because , I can't able to download it from the given link.

Sorry, but we cannot redistribute public datasets. Please refer to the following [tutorial](https://github.com/pytorch/examples/tree/master/imagenet).
