### ISSUE TITLE
Training and testing models from Object Detection Sample

### ISSUE THREAD

**Issue by AbramovAV** [openvinotoolkit/nncf#478]
Hi! During running the Object Detection Sample, I've encountered few issues:

1. I've tried to run following command ```python3 main.py -m train --config configs/ssd300_vgg_voc_int8.json --data <path_to_dataset> --log-dir=../../results/quantization/ssd300_int8 --workers 0 --gpu-id 0 --batch-size 8``` to quantize pretrained FP32 model, but it seems that QAT started with freshly initialized model without pretrained weights, since first validation returned very low AP (around 0.002). Current config ```ssd300_vgg_voc_int8.json``` doesn't contain any fields for loading backbone/model weights.
2. I've tried to train SSD300 without any compression with default config (changed only total amount of iterations) and following command ```python3 main.py -m train --config configs/ssd300_vgg_voc.json --data <path_to_dataset> --log-dir=../../results/noops/ssd300_int8 --workers 0 --gpu-id 0 --batch-size 8``` and achieved approx. 0.7 AP at best after 180 epochs.
3. After checking the code I've found field ['weights' ](https://github.com/openvinotoolkit/nncf/blob/develop/examples/object_detection/main.py#L261) for config, added local path to downloaded weights ([Link](https://storage.openvinotoolkit.org/repositories/nncf/models/v1.5.0/ssd300_vgg_voc.pth)) into both ```ssd300_vgg_voc.json``` and ```ssd300_vgg_voc_int8.json```, trained a bit and exported from NNCF->ONNX->OpenVINO. Benchmarking both models with benchmark_app gives similar results (3.53 vs 3.64 FPS), but their graphs are obviously different for both ONNX and OpenVINO's IR, as Netron shows. Also I've noticed that benchmark_app outputs ```Network input 'result.1' precision U8, dimensions (NCHW): 1 3 300 300``` for both models, as if both of them were quantized.

Path to PASCAL VOC dataset was replaced here to <path_to_dataset> for convenience.

**Package versions**:

- **NNCF** - 1.5.0
- **Pytorch** - 1.7.1
- **OpenVINO** - 2020.2.120
Other required modules were installed from requirements.txt.

**Models**:
- Uncompressed (ONNX and IR) - [Link](https://www.dropbox.com/s/dqe7mtepl17djfm/ssd300.zip?dl=0)
- Quantized (ONNX and IR) - [Link](https://www.dropbox.com/s/yy4updmsxxugug1/ssd300_int8.zip?dl=0)
- Trained SSD300 - [Link](https://www.dropbox.com/s/c2ib1v4qkp294ev/ssd_vgg_voc_best.pth?dl=0)

Is config ```ssd300_vgg_voc_int8.json``` correct or should I manually provide weights? And are both original and quantized models supposed to show similar latency/throughput? Thanks in advance!

**Comment by AlexKoff88** [comment]
@AbramovAV, thanks for noticing the problem. What kind of HW did you use for performance measurement? Can you please clarify that there were no heavy tasks running at the time when you executed benchmark_app?

**Comment by vshampor** [comment]
Greetings, @AbramovAV!

1. Neither of the configs present in NNCF examples contain the path to the starting weights, although it is indeed possible to specify that in the config files for the examples. By default the training will start from scratch, which is the expected behaviour. `--weights` is indeed supposed to be used in case training should start from a pre-trained uncompressed model; I created #479 to make this more clear in the READMEs.
2. This is probably to be expected too, as we trained the SSD model using batch sizes in the hundreds. We strive for the config files to record the training hyperparameters that were used to obtain the checkpoints we distribute; alas, it is not yet so for the majority of the configs.
3. That the NNCF INT8-compressed model and the FP32 model perform the same in OpenVINO is definitely not intended. From a cursory look on the INT8 ONNX your SSD INT8 model looks fine. Will investigate, but as @AlexKoff88 mentioned we will need some additional info on your benchmarking setup.

**Comment by AbramovAV** [comment]
Thanks for response! There were no heavy tasks running in background during benchmarking, just regular apps (like browser, Slack etc.). I've double checked latency/throughput without background processes for both models with following options: ```-d CPU -niter 1000 -nireq 1 -nstreams 1 -progress -b 1```; achieved approx. 3.9 FPS. Attached output from benchmark_app with used command and lscpu for details.
[lscpu.txt](https://github.com/openvinotoolkit/nncf/files/5916872/lscpu.txt)
[ssd300.txt](https://github.com/openvinotoolkit/nncf/files/5916873/ssd300.txt)
[ssd300_int8.txt](https://github.com/openvinotoolkit/nncf/files/5916875/ssd300_int8.txt)

**Comment by AlexKoff88** [comment]
@AbramovAV, we do not have exactly the same CPU as you mentioned but we observe ~1.9x speedup for similar platforms, e.g. Core-i3 8100 or Core-i5 8500. 

I personally ran the models you provided with OpenVINO 2021.2.144 on my Core-i9 and got ~2.5x speedup.

@nkogteva, can you please look as well and provide you guess what can be a problem?

**Comment by AbramovAV** [comment]
@AlexKoff88, I compared both models with OpenVINO 2021.2.185 and got speedup ~1.6x for my CPU. Guess in my case updating to newer version solved a problem, so I'm closing issue. Attached output from benchmark_app for more info.
[ssd300_2021.2.txt](https://github.com/openvinotoolkit/nncf/files/5918388/ssd300_2021.2.txt)
[ssd300_int8_2021.2.txt](https://github.com/openvinotoolkit/nncf/files/5918389/ssd300_int8_2021.2.txt)
