### ISSUE TITLE
Could the mix-precision model deploy to the Movidius VPU？

### ISSUE THREAD

**Issue by zhangliliang** [openvinotoolkit/nncf#489]
In the hw_configs, it seems that nncf could help to train and export mix-precision model to VPU.  If that so?

**Comment by AlexKoff88** [comment]
Hi @zhangliliang,

It will once we get this feature enabled in the next generations of VPUs. For now, this is mostly an experimental feature.

**Comment by zhangliliang** [comment]
Thanks.
