### ISSUE TITLE
Rename `bitwidth` to `num_bits`

### ISSUE THREAD

**Issue by ljaljushkin** [openvinotoolkit/nncf#505]
> Also, as I've discovered just now, `tensorflow.python.ops.gen_array_ops.fake_quant_with_min_max_vars_per_channel` uses `num_bits` as a corresponding keyword argument. Wouldn't it be better to be aligned with this as well?

ok, I will rename `bitwidth` to `num_bits` in a separate PR then

_Originally posted by @ljaljushkin in https://github.com/openvinotoolkit/nncf/pull/483#discussion_r576152321_

**Comment by vshampor** [comment]
Done where it mattered, as far as I can see.
