### ISSUE TITLE
NNCF E2E examples

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/nncf#513]
NNCF is aimed at optimizing models for inference w/ OpenVINO. But now it looks quite detached from OpenVINO. I suggest creating E2E examples that demonstrate optimization capabilities and show performance speedup with OpenVINO. It can be Jupyter notebooks in Collab or just README files that explain all the steps. The good thing is that OpenVINO and its tools are going to be available via PyPi in the next release. So it allows us fully automate these samples. The only thing we should add and store locally is AC configs (OMZ is not going to be available in OV PyPi distribution).
This task is related both to PyTorch and TF versions.

cc'ed @vshampor, @alexsu52

**Comment by alexsu52** [comment]
@ AlexKoff88, @vshampor I can suggest extending the Jupyter notebook that @negvet is developing.

**Comment by vshampor** [comment]
The 30x notebooks at https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks seem to be covering this at this moment in time.
