### ISSUE TITLE
About RB sparsity.

### ISSUE THREAD

**Issue by HolmesShuan** [openvinotoolkit/nncf#516]
Hi, I have read the [description](https://github.com/openvinotoolkit/nncf/blob/develop/docs/compression_algorithms/Sparsity.md) on RB sparsity and I found the idea of reparameterization quite interesting! 

Note that the experiments on categorization are mainly RB sparsity coupled with quantization. Have you ever tried other settings like magnitude or constant sparsity? Thanks in advance.

**Comment by AlexKoff88** [comment]
Hi @HolmesShuan,

Definitely, the magnitude sparsity is the mainstream method that we use because it can deliver stable results in all cases. Const sparsity is required to apply other methods on top of the already sparse model and keep sparsity during additional fine-tuning/training.

**Comment by HolmesShuan** [comment]
Cool, thanks.
