### ISSUE TITLE
hang on import nncf after import torch

### ISSUE THREAD

**Issue by korabelnikov** [openvinotoolkit/nncf#533]
![image](https://user-images.githubusercontent.com/3808833/109419241-89b4e880-79dd-11eb-8e20-aa38d950ba8b.png)

installed as
![image](https://user-images.githubusercontent.com/3808833/109419300-c97bd000-79dd-11eb-8559-d332c667df79.png)

**Comment by vshampor** [comment]
Greetings, @korabelnikov!

The compilation of the torch extensions may have been interrupted previously on your setup. Torch seems to use file-based locking to ensure only one process is tasked with building the extensions. Remove the folder where torch extensions are built - by default should be located at `~/.cache/torch_extensions` - then run your NNCF-using scripts again and see if it fixes the issue.

**Comment by korabelnikov** [comment]
@vshampor thank you for a quick response.

It imports ok now, but i couldn't understand it without your help

**Comment by daniil-lyakhov** [comment]
@vshampor I think it would be useful to have this into a known issues
