### ISSUE TITLE
Locked when training

### ISSUE THREAD

**Issue by Wang-zipeng** [openvinotoolkit/nncf#563]
I got this problem another time, after i install nncf(1.6.0) and mmdet(v2.7.0)\mmcv(1.1.5)，just in the python shell, i input
![image](https://user-images.githubusercontent.com/40973262/110569498-8ebd2900-818f-11eb-9760-205a19edb9f7.png)
I got this lock another time. In the previous, i can solve this problem by remove /tmp/torch_extensions folder, but there is no /tmp/torch_extensions folder in current version, How could i solve this problem?

**Comment by vuiseng9** [comment]
```~/.cache/torch_extensions``` by any chance? at least it is for my case. Once it is removed, importing NNCF works for me.

**Comment by Wang-zipeng** [comment]
> `~/.cache/torch_extensions` by any chance? it is for my case. Once it is removed, importing NNCF works for me.

I think your reply is correct, i will try it. I just need this folder's location
