### ISSUE TITLE
Question about extension implementation

### ISSUE THREAD

**Issue by Wang-zipeng** [openvinotoolkit/nncf#569]
Could someone tell me why pytorch's extension compile when nncf imported, but not like other's implementation compile when run setup.py?

**Comment by AlexKoff88** [comment]
If you use NNCF in the same HW environment the compilation happens only during the first import. You can also control CUDA architectures for that you are going to compile using an environment variable. 
+ @aleksei-kashapov for more comments on that.

**Comment by aleksei-kashapov** [comment]
@Wang-zipeng we compile our own pytorch extensions through standard torch build function - `torch.utils.cpp_extension.load() `
which is called first time during importing NNCF. 
It works that way as it is necessary to build extensions for the particular hardware that the machine has, using NNCF

If it is clear, please, close the ticket
