### ISSUE TITLE
How to add a custom hardware backend？

### ISSUE THREAD

**Issue by raymon-tian** [openvinotoolkit/nncf#621]
NNCF predefines the corresponding quantization configuration for one specific hardward, such as cpu, vpu and gpu. 

How could we add a custom hardware backend, or NNCF has the plan to provide some interfaces to define user hardware backend?

thanks.

**Comment by vshampor** [comment]
Greetings, @raymon-tian !

Exactly which custom HW backend do you wish to see supported in NNCF?

**Comment by raymon-tian** [comment]
@vshampor thanks for your reply.


it maybe the chips developed by ourselves.

Thus, I would be appreciated it if nncf could provide some flexible APIs.

**Comment by AlexKoff88** [comment]
@raymon-tian, NNCF is a part of OpenVINO ecosystem, so it can only optimize models for the HW that is supported by OpenVINO Toolkit. 
Potentially, you could extend NNCF with the support of your HW by augmenting the set of HW configuration files but I suggest doing this on a fork.

**Comment by raymon-tian** [comment]
@AlexKoff88 I see, thanks for your reply.

**Comment by vshampor** [comment]
NNCF is meant to be used in tandem with OpenVINO and Intel hardware. The "CPU", "GPU" and "VPU" target devices settings in NNCF will therefore mean that NNCF should produce a best-performing model for the corresponding type of Intel HW. Any further HW backends officially supported by NNCF, I presume, will also be Intel-targeted and Intel-targeted only.

That said, it is currently possible to define a custom HW configuration file for NNCF, which will require certain code modification. One may craft a `custom_hw.json` file based on the format used by `.json` files in the `nncf/hw_configs` folder (the `nncf/hw_configs/template.json` might be particularly helpful for understanding of the format), then register it within NNCF and use a corresponding `"target_device": ...` setting in the NNCF config file. 

We may accept reasonable PRs aimed to generalize the HW config format, if they are beneficial to currently supported HW configurations as well, but not the custom HW config files themselves unless there is a serious reason to do so.

**Comment by raymon-tian** [comment]
@vshampor Thanks for your kind explanation, now I understand it.
