### ISSUE TITLE
Supported Cuda Version 10.2 or >=10.2 ?

### ISSUE THREAD

**Issue by Bilal-Yousaf** [openvinotoolkit/nncf#628]
Is it necessary to use CUDA 10.2 or any version later than this is supported

**Comment by vshampor** [comment]
Greetings, @Bilal-Yousaf !

Sorry for the late reply. Starting from the v1.7.0 of NNCF, the NNCF package will use the torch package that is installed in your virtual environment if it has a supported *base* version. For instance, if your environment already contains torch 1.7.1 compiled for CUDA 11.1 (e.g. torch==1.7.1+cu111), then the `pip install nncf` call **won't** uninstall your torch version to replace it with the CUDA 10.2 version (which is designated by torch devs as the default target CUDA version).
