### ISSUE TITLE
No exception raised when passing the wrong parameter names

### ISSUE THREAD

**Issue by dqawami** [openvinotoolkit/nncf#709]
Hello, 

Recently I tried using quantization from the NNCF toolkit, and set up the parameters by declaring the "num_init_steps" and "num_bn_adaptation_steps", which did not raise any errors even though those parameters weren't correct, and quantization was not set up. Please add some error message for when parameters passed are not usable. Let me know if there is further information needed for this particular error.

**Comment by vshampor** [comment]
Greetings, @dqawami ! Thanks for reporting this.

Please provide an exact reproducer - the NNCF config .json file or part thereof that exhibits incorrect behaviour.

**Comment by aleksei-kashapov** [comment]
> Greetings, @dqawami ! Thanks for reporting this.
> 
> Please provide an exact reproducer - the NNCF config .json file or part thereof that exhibits incorrect behaviour.

No needed to provide a config file. The problem is well described. To reproduce the bug you need to change the name field `num_init_samples` `num_init_steps` and NNCF will not raise any exception.

**Comment by vshampor** [comment]
NNCF configs are validated using `jsonschema`, and parameter mistypes should be caught on the schema validation stage. See also https://openvinotoolkit.github.io/nncf/ for visual reference to the schema used for NNCF config file validation.
