### ISSUE TITLE
yolo loss RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by betterhalfwzm** [openvinotoolkit/nncf#739]
INFO:nncf:Performing signed weight quantization for: TargetType.OPERATION_WITH_WEIGHTS MobileNetV2SingleChannel/NNCFConv2d[conv5_2_ds1]
WARNING:nncf:A saturation issue fix will be applied. Now all weight quantizers will effectively use only 7 bits out of 8 bits This resolves the saturation issue problem on AVX2 and AVX-512 machines. Please take a look at the documentation for a detailed information. 
INFO:nncf:Set sign: True and scale: [0.7848, 0.7514, 1.1538, 0.7255, 0.8461, 0.9868, 0.7771, 1.0240, 0.8732, 1.0904, ... (first 10/200 elements shown only) ] for TargetType.OPERATION_WITH_WEIGHTS MobileNetV2SingleChannel/NNCFConv2d[newconv6_0_ds0_det]
INFO:nncf:Performing signed weight quantization for: TargetType.OPERATION_WITH_WEIGHTS MobileNetV2SingleChannel/NNCFConv2d[newconv6_0_ds0_det]
WARNING:nncf:A saturation issue fix will be applied. Now all weight quantizers will effectively use only 7 bits out of 8 bits This resolves the saturation issue problem on AVX2 and AVX-512 machines. Please take a look at the documentation for a detailed information. 
INFO:nncf:Set sign: True and scale: [0.6764, 0.6563, 1.3269, 0.8001, 1.5586, 0.7530, 1.3371, 0.8483, 0.6808, 2.3675, ... (first 10/200 elements shown only) ] for TargetType.OPERATION_WITH_WEIGHTS MobileNetV2SingleChannel/NNCFConv2d[newconv6_0_dw_det]
INFO:nncf:Performing signed weight quantization for: TargetType.OPERATION_WITH_WEIGHTS MobileNetV2SingleChannel/NNCFConv2d[newconv6_0_dw_det]
WARNING:nncf:A saturation issue fix will be applied. Now all weight quantizers will effectively use only 7 bits out of 8 bits This resolves the saturation issue problem on AVX2 and AVX-512 machines. Please take a look at the documentation for a detailed information. 
INFO:nncf:Set sign: True and scale: [1.0785, 0.9607, 0.8347, 0.8926, 0.8043, 0.9081, 0.6159, 0.5772, 0.7461, 0.7233, ... (first 10/76 elements shown only) ] for TargetType.OPERATION_WITH_WEIGHTS MobileNetV2SingleChannel/NNCFConv2d[newconv6_0_ds1_det]
INFO:nncf:Performing signed weight quantization for: TargetType.OPERATION_WITH_WEIGHTS MobileNetV2SingleChannel/NNCFConv2d[newconv6_0_ds1_det]
WARNING:nncf:A saturation issue fix will be applied. Now all weight quantizers will effectively use only 7 bits out of 8 bits This resolves the saturation issue problem on AVX2 and AVX-512 machines. Please take a look at the documentation for a detailed information. 
INFO:nncf:Set sign: True and scale: [0.9423, 0.6994, 0.2990, 0.2387, 0.8855, 1.2630, 0.8313, 0.3672, 0.4299, 1.1484, ... (first 10/25 elements shown only) ] for TargetType.OPERATION_WITH_WEIGHTS MobileNetV2SingleChannel/NNCFConv2d[conv_finalout]
INFO:nncf:Performing signed weight quantization for: TargetType.OPERATION_WITH_WEIGHTS MobileNetV2SingleChannel/NNCFConv2d[conv_finalout]
WARNING:nncf:Enabling quantization batch norm adaptation with default parameters.
INFO:nncf:BatchNorm statistics adaptation █                 | 7 / 63
INFO:nncf:BatchNorm statistics adaptation ███               | 14 / 63
INFO:nncf:BatchNorm statistics adaptation █████             | 21 / 63
INFO:nncf:BatchNorm statistics adaptation ███████           | 28 / 63
INFO:nncf:BatchNorm statistics adaptation ████████          | 35 / 63
INFO:nncf:BatchNorm statistics adaptation ██████████        | 42 / 63
INFO:nncf:BatchNorm statistics adaptation ████████████      | 49 / 63
INFO:nncf:BatchNorm statistics adaptation ██████████████    | 56 / 63
INFO:nncf:BatchNorm statistics adaptation ████████████████  | 63 / 63
WARNING:nncf:Graphviz is not installed - only the .dot model visualization format will be used. Install pygraphviz into your Python environment and graphviz system-wide to enable PNG rendering.
time: 2021-05-28 10:38:38.378322, epoch_num: 0, step_num: 0

loss_tot: nan, loss_conf: nan, loss_coord: 34533.042969, loss_comp: 0.000000

Traceback (most recent call last):
  File "main_singlechannel_nncf.py", line 71, in <module>
    train(compressed_model,compression_ctrl,train_dataloader,opitimizer,criterion,epoch,config)
  File "/data4/wangzhaoming/work_code/yolo_pytorch_nccf/train_regionloss.py", line 101, in train
    train_epoch(model,compression_ctrl,train_dataloader,optimizer,criterion,config,epoch)
  File "/data4/wangzhaoming/work_code/yolo_pytorch_nccf/train_regionloss.py", line 163, in train_epoch
    losses.backward()
  File "/data4/wangzhaoming/Anaconda3/envs/torch1.8/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data4/wangzhaoming/Anaconda3/envs/torch1.8/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/data4/wangzhaoming/Anaconda3/envs/torch1.8/lib/python3.7/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/data4/wangzhaoming/Anaconda3/envs/torch1.8/lib/python3.7/site-packages/nncf/quantization/quantize_functions.py", line 57, in backward
    grad_output, input_, input_low, input_range, levels, level_low, level_high
RuntimeError: CUDA error: device-side assert triggered

**Comment by vshampor** [comment]
@betterhalfwzm please provide a proper reproducer code and the information on your environment.
