### ISSUE TITLE
train int4 and mix[4,16] config is like this?

### ISSUE THREAD

**Issue by betterhalfwzm** [openvinotoolkit/nncf#772]
Thx!!!
INT4:
{
    "input_info": {
      "sample_size": [8, 3, 416, 576]
    },
    "compression": {
      "algorithm": "quantization",
      "initializer": {
        "range": {
          "num_init_samples": 1920
        }
      }    
    },
    "weights": {
      "bits": 4
      },
    "activations": {
      "bits": 4
      }
  }

mix[4,16]
{
    "input_info": {
      "sample_size": [8, 3, 416, 576]
    },
    "compression": {
      "algorithm": "quantization",
      "initializer": {
        "range": {
          "num_init_samples": 1920
        }
      }    
    },
    "precision": {
      "type": "hawq", // Type of precision initialization - either "manual" or "hawq". With "manual", precisions are defined explicitly via "bitwidth_per_scope". With "hawq", these are determined automatically using the HAWQ algorithm.
      "bits": [4, 16], // A list of bitwidth to choose from when performing precision initialization. Overrides bitwidth constraints specified in `weight` and `activation` sections",
      "num_data_points": 100, // Number of data points to iteratively estimate Hessian trace, 100 by default.
      "iter_number": 200, // Maximum number of iterations of Hutchinson algorithm to estimate Hessian trace, 200 by default
      "tolerance": 1e-4, //  Minimum relative tolerance for stopping the Hutchinson algorithm. It's calculated between mean average trace from previous iteration and current one. 1e-4 by default
      "compression_ratio": 1.5, // The desired ratio between bits complexity of fully INT8 model and mixed-precision lower-bit one.
    }
}

**Comment by vshampor** [comment]
@betterhalfwzm although we never tried this, your second config seems to be correct for a mix of INT8 and **INT16**. However, make sure that this is what you want, since **INT16** is not the same as **FP16**.

**Comment by betterhalfwzm** [comment]
> @betterhalfwzm although we never tried this, your second config seems to be correct for a mix of INT8 and **INT16**. However, make sure that this is what you want, since **INT16** is not the same as **FP16**.

@vshampor first int4 config is right? And how to train "bits": [4, 16]?
this is a model with int4, first config,  but i do not find int4 layer or something, look like as same as int8.
NNCFNetwork(
  (nncf_module): MobileNetV2_145M_threechannels(
    (conv0_0): NNCFConv2d(
      3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv0_0_bn): DummyModule()
    (conv1_0_dw): NNCFConv2d(
      16, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=16
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv1_0_dw_bn): DummyModule()
    (conv1_0_ds1): NNCFConv2d(
      16, 8, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv1_0_ds1_bn): DummyModule()
    (conv2_0_ds0): NNCFConv2d(
      8, 40, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv2_0_ds0_bn): DummyModule()
    (conv2_0_dw): NNCFConv2d(
      40, 40, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=40
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv2_0_dw_bn): DummyModule()
    (conv2_0_ds1): NNCFConv2d(
      40, 16, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv2_0_ds1_bn): DummyModule()
    (conv2_1_ds0): NNCFConv2d(
      16, 56, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv2_1_ds0_bn): DummyModule()
    (conv2_1_dw): NNCFConv2d(
      56, 56, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=56
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv2_1_dw_bn): DummyModule()
    (conv2_1_ds1): NNCFConv2d(
      56, 16, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv2_1_ds1_bn): DummyModule()
    (conv3_0_ds0): NNCFConv2d(
      16, 56, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv3_0_ds0_bn): DummyModule()
    (conv3_0_dw): NNCFConv2d(
      56, 56, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=56
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv3_0_dw_bn): DummyModule()
    (conv3_0_ds1): NNCFConv2d(
      56, 24, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv3_0_ds1_bn): DummyModule()
    (conv3_1_ds0): NNCFConv2d(
      24, 72, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv3_1_ds0_bn): DummyModule()
    (conv3_1_dw): NNCFConv2d(
      72, 72, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=72
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv3_1_dw_bn): DummyModule()
    (conv3_1_ds1): NNCFConv2d(
      72, 24, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv3_1_ds1_bn): DummyModule()
    (conv3_2_ds0): NNCFConv2d(
      24, 80, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv3_2_ds0_bn): DummyModule()
    (conv3_2_dw): NNCFConv2d(
      80, 80, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=80
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv3_2_dw_bn): DummyModule()
    (conv3_2_ds1): NNCFConv2d(
      80, 24, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv3_2_ds1_bn): DummyModule()
    (deconv_0_ds0): NNCFConv2d(
      24, 48, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (deconv_0_ds0_bn): DummyModule()
    (conv4_0_ds0): NNCFConv2d(
      24, 88, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_0_ds0_bn): DummyModule()
    (conv4_0_dw): NNCFConv2d(
      88, 88, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=88
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_0_dw_bn): DummyModule()
    (conv4_0_ds1): NNCFConv2d(
      88, 48, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_0_ds1_bn): DummyModule()
    (conv4_1_ds0): NNCFConv2d(
      48, 240, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_1_ds0_bn): DummyModule()
    (conv4_1_dw): NNCFConv2d(
      240, 240, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=240
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_1_dw_bn): DummyModule()
    (conv4_1_ds1): NNCFConv2d(
      240, 48, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_1_ds1_bn): DummyModule()
    (conv4_2_ds0): NNCFConv2d(
      48, 232, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_2_ds0_bn): DummyModule()
    (conv4_2_dw): NNCFConv2d(
      232, 232, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=232
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_2_dw_bn): DummyModule()
    (conv4_2_ds1): NNCFConv2d(
      232, 48, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_2_ds1_bn): DummyModule()
    (conv4_3_ds0): NNCFConv2d(
      48, 224, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_3_ds0_bn): DummyModule()
    (conv4_3_dw): NNCFConv2d(
      224, 224, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=224
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_3_dw_bn): DummyModule()
    (conv4_3_ds1): NNCFConv2d(
      224, 48, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv4_3_ds1_bn): DummyModule()
    (conv5_0_ds0): NNCFConv2d(
      48, 224, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv5_0_ds0_bn): DummyModule()
    (conv5_0_dw): NNCFConv2d(
      224, 224, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=224
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv5_0_dw_bn): DummyModule()
    (conv5_0_ds1): NNCFConv2d(
      224, 72, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv5_0_ds1_bn): DummyModule()
    (conv5_1_ds0): NNCFConv2d(
      72, 288, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv5_1_ds0_bn): DummyModule()
    (conv5_1_dw): NNCFConv2d(
      288, 288, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=288
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv5_1_dw_bn): DummyModule()
    (conv5_1_ds1): NNCFConv2d(
      288, 64, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv5_1_ds1_bn): DummyModule()
    (conv5_2_ds0): NNCFConv2d(
      64, 256, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv5_2_ds0_bn): DummyModule()
    (conv5_2_dw): NNCFConv2d(
      256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv5_2_dw_bn): DummyModule()
    (conv5_2_ds1): NNCFConv2d(
      256, 64, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv5_2_ds1_bn): DummyModule()
    (conv6_0_ds0_det): NNCFConv2d(
      64, 200, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv6_0_ds0_bn_det): DummyModule()
    (conv6_0_dw_det): NNCFConv2d(
      200, 200, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=200
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv6_0_dw_bn_det): DummyModule()
    (conv6_0_ds1_det): NNCFConv2d(
      200, 76, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv6_0_ds1_bn_det): DummyModule()
    (conv6_0_ds2_det): NNCFConv2d(
      76, 96, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv6_0_ds2_bn_det): DummyModule()
    (conv6_0_dw2_det): NNCFConv2d(
      96, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=96
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv6_0_dw2_bn_det): DummyModule()
    (conv6_0_ds3_det): NNCFConv2d(
      96, 48, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv6_0_ds3_bn_det): DummyModule()
    (conv7_0_ds0_det): NNCFConv2d(
      48, 120, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv7_0_ds0_bn_det): DummyModule()
    (conv7_0_dw_det): NNCFConv2d(
      120, 120, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=120
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv7_0_dw_bn_det): DummyModule()
    (conv7_0_ds1_det): NNCFConv2d(
      120, 76, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
    (conv7_0_ds1_bn_det): DummyModule()
    (conv_finalout): NNCFConv2d(
      76, 25, kernel_size=(1, 1), stride=(1, 1)
      (pre_ops): ModuleDict(
        (0): UpdateWeight(
          (op): SymmetricQuantizer(bit=8, ch=True)
        )
      )
      (post_ops): ModuleDict()
    )
  )
  (external_quantizers): ModuleDict(
    (/nncf_model_input_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv1_0_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv2_0_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv2_1_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv3_0_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv3_1_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv3_2_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv4_0_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv4_1_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv4_2_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv4_3_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv5_0_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv5_1_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv5_2_ds1]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/NNCFConv2d[conv6_0_ds1_det]/conv2d_0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_0|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_10|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_11|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_12|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_13|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_14|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_15|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_16|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_17|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_18|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_19|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_1|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_20|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_21|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_22|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_23|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_24|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_25|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_26|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_27|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_28|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_29|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_2|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_30|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_31|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_32|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_33|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_34|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_3|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_4|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_5|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_6|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_7|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/RELU_8|OUTPUT): SymmetricQuantizer(bit=8, ch=True)
    (MobileNetV2_145M_threechannels/RELU_9|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/__add___0|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/__add___1|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/__add___2|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/__add___3|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/__add___4|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/__add___5|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/__add___6|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
    (MobileNetV2_145M_threechannels/__add___7|OUTPUT): SymmetricQuantizer(bit=8, ch=False)
  )
)
