### ISSUE TITLE
train mix bit[4,8],but get the model look like int8

### ISSUE THREAD

**Issue by betterhalfwzm** [openvinotoolkit/nncf#785]
![image](https://user-images.githubusercontent.com/20449990/122325324-ef14f100-cf5c-11eb-936f-5e59d250ca46.png)
trained model:
![image](https://user-images.githubusercontent.com/20449990/122327330-449ecd00-cf60-11eb-9642-5a1d574c9008.png)

**Comment by ljaljushkin** [comment]
Greetings, @betterhalfwzm!

As far as I can see from your config, there's no `target_device` and by default it's CPU. 
Currently, CPU supports [only int8 quantizations](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/common/hardware/configs/cpu.json), that's why mixed-precision initialization wasn't applied.

For mixed precision configuration I should specify VPU or TRIAL device:

```python
"target_device": "VPU",
"compression": {
  ...
}
```

**Comment by betterhalfwzm** [comment]
> Greetings, @betterhalfwzm!
> 
> As far as I can see from your config, there's no `target_device` and by default it's CPU.
> Currently, CPU supports [only int8 quantizations](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/common/hardware/configs/cpu.json), that's why mixed-precision initialization wasn't applied.
> 
> For mixed precision configuration you should specify VPU or TRIAL device:
> 
> ```python
> "target_device": "VPU",
> "compression": {
>   ...
> }
> ```

Thank you for your reply！ But when i use this,  training report error. when "type": "manual", training is normal.
Config:
![image](https://user-images.githubusercontent.com/20449990/122852078-9a012280-d342-11eb-9b79-e5546a1340af.png)
Error:
Traceback (most recent call last):
  File "main_MobileNetV2_145M_threechannels_nncf_fold_BN.py", line 119, in <module>
    compression_ctrl, compressed_model = create_compressed_model(model, nncf_config)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/model_creation.py", line 122, in create_compressed_model
    composite_builder.apply_to(compressed_model)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/composite_compression.py", line 78, in apply_to
    layout = self.get_transformation_layout(target_model)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/composite_compression.py", line 111, in get_transformation_layout
    transformations.update(builder.get_transformation_layout(model))
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/compression_method_api.py", line 225, in get_transformation_layout
    layout = self._get_transformation_layout(target_model)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 607, in _get_transformation_layout
    single_config_quantizer_setup = self._get_quantizer_setup(target_model)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 686, in _get_quantizer_setup
    single_config_quantizer_setup = setup_generator.generate_setup()
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 363, in generate_setup
    quantization_proposal.quantizer_setup)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 300, in select_final_quantizer_setup
    hw_constraints)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 1247, in init_precision
    return initializer.apply_init()
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/precision_init/hawq_init.py", line 263, in apply_init
    traces_per_layer = self._calc_traces(self._criterion_fn, self._criterion, self._iter_number, self._tolerance)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/precision_init/hawq_init.py", line 460, in _calc_traces
    avg_traces = trace_estimator.get_average_traces(max_iter=iter_number, tolerance=tolerance)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/hessian_trace.py", line 127, in get_average_traces
    avg_traces_per_iter.append(self._calc_avg_traces_per_param())
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/hessian_trace.py", line 144, in _calc_avg_traces_per_param
    for gradients in self._gradients_calculator:
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/hessian_trace.py", line 89, in __next__
    loss.backward(create_graph=True)
AttributeError: 'tuple' object has no attribute 'backward'

**Comment by betterhalfwzm** [comment]
> Greetings, @betterhalfwzm!
> 
> As far as I can see from your config, there's no `target_device` and by default it's CPU.
> Currently, CPU supports [only int8 quantizations](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/common/hardware/configs/cpu.json), that's why mixed-precision initialization wasn't applied.
> 
> For mixed precision configuration you should specify VPU or TRIAL device:
> 
> ```python
> "target_device": "VPU",
> "compression": {
>   ...
> }
> ```

@ljaljushkin Thank you for your reply. When i use this config,training report error, use "type": "manual", training is normal.
Config:
![image](https://user-images.githubusercontent.com/20449990/122852682-9c17b100-d343-11eb-9473-f19fc74fc163.png)
Error:
INFO:nncf:Initialization of quantization precisions
Traceback (most recent call last):
  File "main_MobileNetV2_145M_threechannels_nncf_fold_BN.py", line 119, in <module>
    compression_ctrl, compressed_model = create_compressed_model(model, nncf_config)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/model_creation.py", line 122, in create_compressed_model
    composite_builder.apply_to(compressed_model)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/composite_compression.py", line 78, in apply_to
    layout = self.get_transformation_layout(target_model)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/composite_compression.py", line 111, in get_transformation_layout
    transformations.update(builder.get_transformation_layout(model))
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/compression_method_api.py", line 225, in get_transformation_layout
    layout = self._get_transformation_layout(target_model)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 607, in _get_transformation_layout
    single_config_quantizer_setup = self._get_quantizer_setup(target_model)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 686, in _get_quantizer_setup
    single_config_quantizer_setup = setup_generator.generate_setup()
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 363, in generate_setup
    quantization_proposal.quantizer_setup)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 300, in select_final_quantizer_setup
    hw_constraints)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/algo.py", line 1247, in init_precision
    return initializer.apply_init()
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/precision_init/hawq_init.py", line 263, in apply_init
    traces_per_layer = self._calc_traces(self._criterion_fn, self._criterion, self._iter_number, self._tolerance)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/precision_init/hawq_init.py", line 460, in _calc_traces
    avg_traces = trace_estimator.get_average_traces(max_iter=iter_number, tolerance=tolerance)
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/hessian_trace.py", line 127, in get_average_traces
    avg_traces_per_iter.append(self._calc_avg_traces_per_param())
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/hessian_trace.py", line 144, in _calc_avg_traces_per_param
    for gradients in self._gradients_calculator:
  File "/home/wangzhaoming/anaconda3/envs/torch181/lib/python3.7/site-packages/nncf/quantization/hessian_trace.py", line 89, in __next__
    loss.backward(create_graph=True)
AttributeError: 'tuple' object has no attribute 'backward'

**Comment by ljaljushkin** [comment]
HAWQ algorithm calculates importance of quantization precisions by running back propagation multiple times, so it requires registration of valid criterion function to do it. 
By default criterion is Cross Entropy: https://github.com/openvinotoolkit/nncf/blob/5f8c1329be6f40f8fbdc6aad7538aaf6d5b6c239/examples/torch/classification/main.py#L126

This criterion and function that calculates loss for a given output and target are registered by register_default_init_args call: https://github.com/openvinotoolkit/nncf/blob/5f8c1329be6f40f8fbdc6aad7538aaf6d5b6c239/examples/torch/classification/main.py#L148-L150

The error happens because default loss function https://github.com/openvinotoolkit/nncf/blob/5f8c1329be6f40f8fbdc6aad7538aaf6d5b6c239/nncf/torch/initialization.py#L247-L248 is not suitable for your model. We expect that loss function returns a single Tensor, not a Tuple.
You can [register](https://github.com/openvinotoolkit/nncf/blob/5f8c1329be6f40f8fbdc6aad7538aaf6d5b6c239/nncf/torch/initialization.py#L254) custom criterion function that produces loss in the expected format.

**Comment by betterhalfwzm** [comment]
> HAWQ algorithm calculates importance of quantization precisions by running back propagation multiple times, so it requires registration of valid criterion function to do it.
> By default criterion is Cross Entropy:
> 
> https://github.com/openvinotoolkit/nncf/blob/5f8c1329be6f40f8fbdc6aad7538aaf6d5b6c239/examples/torch/classification/main.py#L126
> 
> This criterion and function that calculates loss for a given output and target are registered by register_default_init_args call:
> 
> https://github.com/openvinotoolkit/nncf/blob/5f8c1329be6f40f8fbdc6aad7538aaf6d5b6c239/examples/torch/classification/main.py#L148-L150
> 
> The error happens because default loss function
> 
> https://github.com/openvinotoolkit/nncf/blob/5f8c1329be6f40f8fbdc6aad7538aaf6d5b6c239/nncf/torch/initialization.py#L247-L248
> 
> is not suitable for your model. We expect that loss function returns a single Tensor, not a Tuple.
> You can [register](https://github.com/openvinotoolkit/nncf/blob/5f8c1329be6f40f8fbdc6aad7538aaf6d5b6c239/nncf/torch/initialization.py#L254) custom criterion function that produces loss in the expected format.

@ljaljushkin Thank you for your reply. i add criterion_fn，train log is this，is right？
INFO:nncf:Initialization of quantization precisions
INFO:nncf:0# difference_avg=nan avg_trace=nan
INFO:nncf:1# difference_avg=nan avg_trace=nan
INFO:nncf:2# difference_avg=nan avg_trace=nan
INFO:nncf:3# difference_avg=nan avg_trace=nan
INFO:nncf:4# difference_avg=nan avg_trace=nan
INFO:nncf:Chosen HAWQ bitwidth sequence with ratio=1.53, bitwidth per weightable layer=[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]

**Comment by ljaljushkin** [comment]
It doesn't seem right. Please make sure that compression is applied for a pre-trained model, not for a model from scratch. It's necessary for a correct work of precision initialization. 
For the models from torchvision you can specify "pretrained" property in the config (like in the [example](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/configs/quantization/inception_v3_imagenet_int8.json#L3)).
Loading of custom pre-trained weights can be done via `--weights` argument for the sample.

If it doesn't solve the issue, you could enable collection of debug information and send content of the `nncf_debug/hawq_dumps` folder as an archive.
For that add the "dump_init_precision_data" parameter to initialization section:
```
...
 "compression": {
        "algorithm": "quantization",
       ...
        "initializer": {
            "precision": {
                "dump_init_precision_data": True,
                ...
            }
        }
} 
```

**Comment by betterhalfwzm** [comment]
> It doesn't seem right. Please make sure that compression is applied for a **pre-trained** model, not for a model **from scratch**. It's necessary for a correct work of precision initialization.
> For the models from torchvision you can specify "pretrained" property in the config (like in the [example](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/configs/quantization/inception_v3_imagenet_int8.json#L3)).
> Loading of custom pre-trained weights can be done via `--weights` argument for the sample.
> 
> If it doesn't solve the issue, you could enable collection of debug information and send content of the `nncf_debug/hawq_dumps` folder as an archive.
> For that add the "dump_init_precision_data" parameter to initialization section:
> 
> ```
> ...
>  "compression": {
>         "algorithm": "quantization",
>        ...
>         "initializer": {
>             "precision": {
>                 "dump_init_precision_data": True,
>                 ...
>             }
>         }
> } 
> ```

@ljaljushkin Is this train log look like normal? Thx!!!!!!!!
INFO:nncf:Initialization of quantization precisions
Corrupt JPEG data: premature end of data segment
INFO:nncf:0# difference_avg=22104903680.0 avg_trace=22104.904296875
INFO:nncf:1# difference_avg=0.027886468917131424 avg_trace=22721.33203125
INFO:nncf:2# difference_avg=0.1252446174621582 avg_trace=19875.607421875
INFO:nncf:3# difference_avg=0.021800925955176353 avg_trace=20308.9140625
INFO:nncf:4# difference_avg=0.0012884966563433409 avg_trace=20282.74609375
INFO:nncf:Chosen HAWQ bitwidth sequence with ratio=1.51, bitwidth per weightable layer=[8, 8, 8, 8, 8, 8, 8, 4, 4, 8, 4, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
INFO:nncf:Distribution of HAWQ metrics: min_value=-19297.549, max_value=80152.312, median_value=-118.628, median_index=1, total_number=51

**Comment by ljaljushkin** [comment]
Yes, the HAWQ algorithm has successfully converged, but it seems like the compression ratio is too high for your model, because there're too many int4 were chosen and the model struggle to restore quality. 


First of all, I'd recommend making sure that [fully INT8 quantization](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/configs/quantization/mobilenet_v2_imagenet_int8.json) doesn't lead to such loss degradation, the pipeline is correct and the model is capable to restore quality. 


If this check is OK, then try to gradually increase the compression ratio towards 1.5.
BTW, there's a trick to accelerate experiments with different compression ratios. The algorithm dumps estimated Hessian traces to 
`nncf_debug/hawq_dumps/avg_traces_per_layer` file in the debug mode enabled by `"dump_init_precision_data": true` parameter in the config.
When you try a different compression ratio, you could avoid the calculation of Hessian traces (the most time-consuming part) again by specifying the path to this file. 
```
...
 "compression": {
        "algorithm": "quantization",
       ...
        "initializer": {
            "precision": {
                "traces_per_layer_path": "path/to/nncf_debug/hawq_dumps/avg_traces_per_layer",
                "compression_ratio": 1.1
                ...
            }
        }
} 
```


We have a plan to automate the procedure of choosing compression ratio for a given maximal accuracy degradation by [Accuracy Aware algorithm](https://github.com/openvinotoolkit/nncf/pull/575).
But currently, it works only for the filter pruning and sparsity algorithms: https://github.com/openvinotoolkit/nncf/blob/2d5a55b874a2c53acf726caf6c4471fe742aec3e/examples/torch/classification/configs/pruning/resnet50_imagenet_accuracy_aware.json#L28-L29


In addition, it makes sense to use `per-channel` quantization for weights, because it's more accurate and doesn't add inference overhead on target hardware in comparison with `per-tensor` one. 
Asymmetric quantization and per-channel activations also boost accuracy but increase inference latency.


Finally, mixed-precision quantization tends to be trained more efficiently within a [stage-quantization pipeline](https://github.com/openvinotoolkit/nncf/blob/2d5a55b874a2c53acf726caf6c4471fe742aec3e/nncf/config/schema.py#L426-L438).
It enables knowledge distillation, learning rate annealing and allows to tune quantization of activations first without weights to not drop accuracy a lot on the first stages of tuning.
https://github.com/openvinotoolkit/nncf/blob/2d5a55b874a2c53acf726caf6c4471fe742aec3e/examples/torch/classification/configs/mixed_precision/mobilenet_v2_imagenet_mixed_int_manual_staged.json#L158-L167

**Comment by betterhalfwzm** [comment]
> Yes, the estimation of Hessian traces in the HAWQ algorithm has successfully converged, but it seems like the compression ratio is too high for your model - there're too many int4 were chosen and the model struggles to restore quality.
> 
> First of all, I'd recommend making sure that [fully INT8 quantization](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/configs/quantization/mobilenet_v2_imagenet_int8.json) doesn't lead to such loss degradation, the pipeline is correct and the model is capable to restore quality.
> 
> If this check is OK, then try to gradually increase the compression ratio towards 1.5.
> BTW, there's a trick to accelerate experiments with different compression ratios. The algorithm dumps estimated Hessian traces to
> `nncf_debug/hawq_dumps/avg_traces_per_layer` file in the debug mode enabled by `"dump_init_precision_data": true` parameter in the config.
> When you try a different compression ratio, you could avoid the calculation of Hessian traces (the most time-consuming part) again by specifying the path to this file.
> 
> ```
> ...
>  "compression": {
>         "algorithm": "quantization",
>        ...
>         "initializer": {
>             "precision": {
>                 "traces_per_layer_path": "path/to/nncf_debug/hawq_dumps/avg_traces_per_layer",
>                 "compression_ratio": 1.1
>                 ...
>             }
>         }
> } 
> ```
> 
> We have a plan to automate the procedure of choosing compression ratio for a given maximal accuracy degradation by [Accuracy Aware algorithm](https://github.com/openvinotoolkit/nncf/pull/575).
> But currently, it works only for the filter pruning and sparsity algorithms:
> 
> https://github.com/openvinotoolkit/nncf/blob/2d5a55b874a2c53acf726caf6c4471fe742aec3e/examples/torch/classification/configs/pruning/resnet50_imagenet_accuracy_aware.json#L28-L29
> 
> In addition, it makes sense to use `per-channel` quantization for weights, because it's more accurate and doesn't add inference overhead on target hardware in comparison with `per-tensor` one.
> Asymmetric quantization and per-channel activations also boost accuracy but increase inference latency.
> 
> Finally, mixed-precision quantization tends to be trained more efficiently within a [stage-quantization pipeline](https://github.com/openvinotoolkit/nncf/blob/2d5a55b874a2c53acf726caf6c4471fe742aec3e/nncf/config/schema.py#L426-L438).
> It enables knowledge distillation, learning rate annealing and allows to tune quantization of activations first without weights to not drop accuracy a lot on the first stages of tuning.
> https://github.com/openvinotoolkit/nncf/blob/2d5a55b874a2c53acf726caf6c4471fe742aec3e/examples/torch/classification/configs/mixed_precision/mobilenet_v2_imagenet_mixed_int_manual_staged.json#L158-L167

@ljaljushkin Thank you very much for your work and suggestions. I will try them one by one.
