### ISSUE TITLE
Purpose of output_low and output_high in ExportQuantizeToFakeQuantize

### ISSUE THREAD

**Issue by raymon-tian** [openvinotoolkit/nncf#795]
While exporting a quantizer to FakeQuantize, five inputs, `input_`, `input_low`, `input_high`, `output_low` and `output_high`, are given to the op.

But we could conclude from [here](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/quantization/layers.py#L249) that the `input_low` and `input_high` are always same as the `output_low` and `output_high`, respectively.

Thus, I would like to know the purpose of `output_low` and `output_high` in ExportQuantizeToFakeQuantize.

Thanks.

**Comment by vshampor** [comment]
Greetings, @raymon-tian !

The semantics of exported ONNX FakeQuantize ops follows the OpenVINO's FakeQuantize operation description:
https://docs.openvinotoolkit.org/latest/openvino_docs_ops_quantization_FakeQuantize_1.html

**Comment by raymon-tian** [comment]
Thanks, I get it.
