### ISSUE TITLE
How to use int8 onnx  model to inference?

### ISSUE THREAD

**Issue by betterhalfwzm** [openvinotoolkit/nncf#808]
Int8 onnx model only run in openvivo? Others devices can run it? Thx!!!!!!!

**Comment by AlexKoff88** [comment]
Hi @betterhalfwzm,

These are basically Intel CPUs and GPUs. But if you use an alternative export of the quantized model to QuantizeLinear/DequantizeLinera you will be able to run such a model with TensorRT on NVidia GPUs or go to ONNXRuntime and try a broader scope of devices available there. But, of course, we don't validate the flow with non-Intel HW.

**Comment by GitForKriti** [comment]
Hi @AlexKoff88 ,

can i do inference on the int8 onnx model using opencv dnn?
if yes how do we do it.Please refer the error below.
Also i have attached an image of the model loaded in [netron.](
![model onnx](https://user-images.githubusercontent.com/92289483/165054084-d8a18658-b7f8-43e9-942c-bb5879d65ecc.png)

)



    net =  cv2.dnn.readNet(onnx_model_path)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'handleNode'
> Node [QuantizeLinear@ai.onnx]:(827) parse error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/int8layers/quantization_utils.cpp:34: error: (-215:Assertion failed) inputs.size() == 1 in function 'getMemoryShapes'
