### ISSUE TITLE
Does not detect RTX 3090 GPU

### ISSUE THREAD

**Issue by bdh0404** [openvinotoolkit/nncf#815]
I've new to this project, and I wanted to run nncf on my machine with 4x NVIDIA RTX 3090.
I changed the torch version check to use torch 1.9.0+cu111 version for full support NVIDIA RTX 3090.
However, the example code shows that nncf does not detect any GPUs from torch.
This code was run at ~/nncf/examples/torch/classification.

python main.py -m train --config configs/sparsity/resnet50_imagenet_rb_sparsity.json --data /mnt/data/data.imagenet/ --log-dir=../../results/sparsity/resnet50_imagenet_rb_sparsity/ --target-device GPU
batch_size                 : 256
batch_size_init            : None
checkpoint_save_dir        : ../../results/sparsity/resnet50_imagenet_rb_sparsity/resnet50_imagenet_rb_sparsity/2021-07-01__11-21-21
compression                : {'algorithm': 'rb_sparsity', 'sparsity_init': 0.02, 'params': {'sparsity_target': 0.61, 'sparsity_target_epoch': 5, 'sparsity_freeze_epoch': 10}}
config                     : configs/sparsity/resnet50_imagenet_rb_sparsity.json
cpu_only                   : False
current_gpu                : None
dataset                    : None
dataset_dir                : /mnt/data/data.imagenet/
device                     : cuda
dist_backend               : nccl
dist_url                   : tcp://127.0.0.1:8899
distributed                : False
epochs                     : 40
execution_mode             : gpu_dataparallel
gpu_id                     : None
imshow_batch               : False
input_info                 : {'sample_size': [1, 3, 224, 224]}
intermediate_checkpoints_path: ../../results/sparsity/resnet50_imagenet_rb_sparsity/resnet50_imagenet_rb_sparsity/2021-07-01__11-21-21/intermediate_checkpoints
log_dir                    : ../../results/sparsity/resnet50_imagenet_rb_sparsity/resnet50_imagenet_rb_sparsity/2021-07-01__11-21-21
metrics_dump               : None
mlflow                     : <examples.torch.common.utils.SafeMLFLow object at 0x7efd7fe990b8>
mode                       : train
model                      : resnet50
multiprocessing_distributed: False
name                       : resnet50_imagenet_rb_sparsity
nncf_config                : {'model': 'resnet50', 'pretrained': True, 'input_info': {'sample_size': [1, 3, 224, 224]}, 'num_classes': 1000, 'batch_size': 256, 'epochs': 40, 'optimizer': {'type': 'Adam', 'base_lr': 0.001, 'schedule_type': 'multistep', 'steps': [15, 20, 25]}, 'compression': {'algorithm': 'rb_sparsity', 'sparsity_init': 0.02, 'params': {'sparsity_target': 0.61, 'sparsity_target_epoch': 5, 'sparsity_freeze_epoch': 10}}, 'target_device': 'GPU', 'log_dir': '../../results/sparsity/resnet50_imagenet_rb_sparsity/resnet50_imagenet_rb_sparsity/2021-07-01__11-21-21'}
num_classes                : 1000
optimizer                  : {'type': 'Adam', 'base_lr': 0.001, 'schedule_type': 'multistep', 'steps': [15, 20, 25]}
pretrained                 : True
print_freq                 : 10
print_step                 : False
rank                       : 0
resuming_checkpoint_path   : None
save_freq                  : 5
seed                       : None
start_epoch                : 0
tb                         : <torch.utils.tensorboard.writer.SummaryWriter object at 0x7efd7fe83f60>
test_every_n_epochs        : 1
to_onnx                    : None
weights                    : None
workers                    : 4
world_size                 : 1
Traceback (most recent call last):
  File "main.py", line 613, in <module>
    main(sys.argv[1:])
  File "main.py", line 104, in main
    start_worker(main_worker, config)
  File "/home/dhbaek/nncf/examples/torch/common/execution.py", line 106, in start_worker
    main_worker(current_gpu=None, config=config)
  File "main.py", line 157, in main_worker
    autoq_eval_fn, val_loader, model_eval_fn, config.device)
  File "/home/dhbaek/nncf/nncf/torch/initialization.py", line 261, in register_default_init_args
    nncf_config.register_extra_structs([QuantizationRangeInitArgs(data_loader=wrap_dataloader_for_init(train_loader),
  File "/home/dhbaek/nncf/nncf/torch/initialization.py", line 73, in wrap_dataloader_for_init
    loaded_item = next(iter(data_loader))
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 234, in __getitem__
    sample = self.transform(sample)
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 97, in __call__
    return F.to_tensor(pic)
  File "/home/dhbaek/nncf/env/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 129, in to_tensor
    np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
TypeError: __array__() takes 1 positional argument but 2 were given

And this is what nvidia-smi says
nvidia-smi
Thu Jul  1 11:21:48 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:00:06.0 Off |                  N/A |
| 34%   35C    P8    28W / 350W |      1MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:00:07.0 Off |                  N/A |
| 34%   35C    P8    28W / 350W |      1MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:00:08.0 Off |                  N/A |
| 33%   35C    P8    22W / 350W |      1MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:00:09.0 Off |                  N/A |
| 33%   35C    P8    27W / 350W |      1MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by vshampor** [comment]
Greetings, @bdh0404!

I believe that your code shows a runtime error somewhere inside torchvision way before the training and device allocation even starts. Make sure you are using torchvision that is compatible with your torch version.

**Comment by bdh0404** [comment]
I'm using torchvision 0.10.0+cu111 version that is compatible with torch 1.9.0+cu111 and changed BKC_TORCH_VERSION to "1.9.0" and BKC_TORCHVISION_VERSION to "0.10.0" but that does not change any behavior of nncf. It shows same error.

**Comment by bdh0404** [comment]
It's working when using torchvision 0.9.1+cu111 and torch 1.8.1+cu111. I think this is bug from pytorch. Checkout https://stackoverflow.com/questions/68211850/typeerror-array-takes-1-positional-argument-but-2-were-given that shows same error.
