### ISSUE TITLE
URL for VOC2007/2012 datasets not working

### ISSUE THREAD

**Issue by ryanloney** [openvinotoolkit/nncf#878]
These URLs seem to be down:
http://host.robots.ox.ac.uk/pascal/VOC/voc2012/index.html#devkit
and
http://host.robots.ox.ac.uk/pascal/VOC/voc2007/index.html#devkit 

They are provided in https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/object_detection/README.md

I was able to download from this URL:
https://pjreddie.com/projects/pascal-voc-dataset-mirror/

I suggest changing the README to pjreddie.com or another mirror.

**Comment by ryanloney** [comment]
There is also a typo in the examples/torch/object_detection/README.md:

> * Run the following command to start compression with fine-tuning on GPUs:
> `python main.py -m train --config configs/ssd300_vgg_int8_voc.json --data <path_to_dataset> --log-dir=../../results/quantization/ssd300_int8`

The config filename is incorrect. It should be `configs/ssd300_vgg_voc_int8.json` (the voc and int8 are reversed in the README)

**Comment by vshampor** [comment]
@ryanloney thanks for spotting this!
