### ISSUE TITLE
Running mixed-precision quantized models

### ISSUE THREAD

**Issue by abuvaneswari** [openvinotoolkit/nncf#887]
Hello,

I have successfully produced a mixed precision quantized model using the config file under:
[examples/torch/classification/configs/mixed_precision/resnet50_imagenet_mixed_int_autoq_staged.json](https://github.com/openvinotoolkit/nncf/blob/master/examples/torch/classification/configs/mixed_precision/resnet50_imagenet_mixed_int_autoq_staged.json)

This config produces a model with bit precisions 2, 4 and 8 bits. I have exported the pth model to onnx, am able to viewed it thru netron and notice the fakequantize nodes, which is fine. 

I would like to know whether openvino cpu can understand this format. Or, if there are other runtimes / devices that can understand the mixed precision models. 

I understand that NVIDIA A100 GPUs support low bit precisions all the way down to int-1. But I am not sure how to get this mixed-precision onnx model inferenced in a GPU or CPU or any other device.

Any pointers will be helpful.
Thank you.

**Comment by vshampor** [comment]
@ljaljushkin
