### ISSUE TITLE
Sparsity examples are not working as intended

### ISSUE THREAD

**Issue by lpuglia** [openvinotoolkit/nncf#907]
Hello, I just tried to use the example config for sparisification purpose:
https://github.com/openvinotoolkit/nncf/blob/develop/docs/compression_algorithms/Sparsity.md

in particular:
``` python
{
    "algorithm": "rb_sparsity",
    "sparsity_init": 0.05,// "Initial value of the sparsity level applied to the model in 'create_compressed_model' function
    "params": {
            "schedule": "multistep",  // The type of scheduling to use for adjusting the target sparsity level
            "patience": 3, // A regular patience parameter for the scheduler, as for any other standard scheduler. Specified in units of scheduler steps.
            "sparsity_target": 0.7, // Target value of the sparsity level for the model
            "sparsity_target_epoch": 3, // Index of the epoch from which the sparsity level of the model will be equal to spatsity_target value
            "sparsity_freeze_epoch": 50, // Index of the epoch from which the sparsity mask will be frozen and no longer trained
            "multistep_steps": [10, 20], // A list of scheduler steps at which to transition to the next scheduled sparsity level (multistep scheduler only).
            "multistep_sparsity_levels": [0.2, 0.5] //Levels of sparsity to use at each step of the scheduler as specified in the 'multistep_steps' attribute. The firstsparsity level will be applied immediately, so the length of this list should be larger than the length of the 'steps' by one."
    },

    // A list of model control flow graph node scopes to be ignored for this operation - functions as a 'denylist'. Optional.
    "ignored_scopes": []

    // A list of model control flow graph node scopes to be considered for this operation - functions as a 'allowlist'. Optional.
    // "target_scopes": []
}
```

there seems to be multiple problems with this example, first of all, this config is faulty because (as it is stated in the example itself):
```
the length of this list should be larger than the length of the 'steps' by one
```
which is not the case and in fact an error is thrown during execution.
Second, but more important, the last level of sparsity specified in `multistep_sparsity_levels` is the one that is actually used as final target (i.e. using the previous example the final sparsity rate of the model is going to be `0.5` and not `0.7`).

Is there anything I am missing by any chance? can you think of any reason why this is not intended to happen and the problem is only on my side?

**Comment by vshampor** [comment]
Greetings, @lpuglia!

Thanks for spotting this. Your observations and the understanding of how this is supposed to function are all correct,  I have adjusted the config and the description in the related PR, hopefully it makes more sense now.
