### ISSUE TITLE
NNCF on Windows doesn't find cl.exe

### ISSUE THREAD

**Issue by helena-intel** [openvinotoolkit/nncf#917]
NNCF on Windows tries to find `cl` by using subprocess to execute `where cl`. This does not work on Windows with an out-of-the-box install of VS Build Tools, because the executables are not added to the system path during installation.

From VSCode docs [docs](https://code.visualstudio.com/docs/cpp/config-msvc): _To use MSVC from a command line or VS Code, you must run from a Developer Command Prompt for Visual Studio. An ordinary shell such as PowerShell, Bash, or the Windows command prompt does not have the necessary path environment variables set._

Screenshots from `where cl` and showing that the file does exist on the system
![image](https://user-images.githubusercontent.com/77325899/131983095-445ea795-c412-4d5d-a929-17303ecf8fc6.png)
![image](https://user-images.githubusercontent.com/77325899/131983762-5f522a6d-ca0f-495d-8fd3-989c3baadfe2.png)

This screenshot is from https://github.com/openvinotoolkit/openvino_notebooks/pull/207
![image](https://user-images.githubusercontent.com/77325899/131979142-d30b49f0-fbc3-4793-8ba5-7b9460243d06.png)

I found  [vswhere](https://github.com/Microsoft/vswhere) as a  way to get the installation path - not sure if that is the best way though.

**Comment by AlexKoff88** [comment]
@helena-intel, thanks for reporting that. But to be honest we've never positioned NNCF to be run on Windows. Can we somehow notify/restrict that this works in Linux environment only?

**Comment by helena-intel** [comment]
@AlexKoff88 I got this notebook to work after adding the Hostx86/x86 build tools directory to the path. I hope that that means that NNCF works on Windows (after installing VS Build Tools) and only need some documentation. I'll test some more and see if it works in the CI too. This notebook doesn't test all NNCF functionality - do you expect any issues other than path related ones?

**Comment by AlexKoff88** [comment]
@helena-intel, thanks for trying it out. Since everything is on Python we don't expect many issues on Windows except path and build of C++/CUDA extensions. There can be problems with the 3rd party packages we depend on in NNCF.

**Comment by vshampor** [comment]
@helena-intel since we rely on PyTorch's public mechanism of JIT-compilation for the custom extensions, the way that the PyTorch searches for the correct C++ compiler is not exactly something that we have complete control over. Thanks for finding a way to resolve this in the scope of the NNCF-showcasing notebook provisioning.
