### ISSUE TITLE
Compress the structured model as well as the .json file

### ISSUE THREAD

**Issue by dhwgithub** [openvinotoolkit/nncf#922]
Can the framework compress the structured model? 

Then there's how to customize the .json file, which means what's required of the .json file

thanks

**Comment by vshampor** [comment]
@dhwgithub please elaborate on your proposition - it is not quite clear what you mean under a "structured model". The .json file ingested by NNCF as an NNCFConfig is documented via a JSON schema defined [here](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/config/schema.py). I propose you ask the remaining questions in the [discussions](https://github.com/openvinotoolkit/nncf/discussions) section of this repo.
