### ISSUE TITLE
Something Wrong when Running mixed-precision quantized models examples

### ISSUE THREAD

**Issue by lianxintao** [openvinotoolkit/nncf#950]
when i run 
[https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/main.py](url) with command
python main.py  --config=configs/quantization/mobilenet_v2_imagenet_mixed_int_hawq.json  --to-onnx=../../results/mixed.onnx

then it report an error 
`/usr/bin/python3.6 /root/nncf/examples/torch/classification/main.py
/root/nncf/nncf/torch/__init__.py:26: UserWarning: NNCF provides best results with torch==1.8.1, while current torch version is 1.7.1+cu110 - consider switching to torch==1.8.1
  curr=torch.__version__
WARNING:nncf:Skip applying a patch to building extension with a reason: PyTorch version is not supported for this
batch_size                 : 200
batch_size_init            : None
checkpoint_save_dir        : runs/mobilenet_v2_imagenet_mixed_int/2021-09-27__18-02-55
compression                : {'algorithm': 'quantization', 'quantize_inputs': True, 'initializer': {'precision': {'type': 'hawq', 'bits': [4, 8], 'compression_ratio': 1.5}}}
config                     : /root/nncf/examples/torch/classification/configs/mixed_precision/mobilenet_v2_imagenet_mixed_int_hawq.json
cpu_only                   : False
current_gpu                : 0
dataset                    : imagenet
dataset_dir                : /data1/dataset/imagenet/
device                     : cuda:0
dist_backend               : nccl
dist_url                   : tcp://127.0.0.1:8899
distributed                : False
epochs                     : 300
execution_mode             : single_gpu
gpu_id                     : 0
imshow_batch               : False
input_info                 : {'sample_size': [2, 3, 224, 224]}
intermediate_checkpoints_path: runs/mobilenet_v2_imagenet_mixed_int/2021-09-27__18-02-55/intermediate_checkpoints
log_dir                    : runs/mobilenet_v2_imagenet_mixed_int/2021-09-27__18-02-55
metrics_dump               : metrics.json
mlflow                     : <examples.torch.common.utils.SafeMLFLow object at 0x7fa8d67e9c18>
mode                       : train
model                      : mobilenet_v2
multiprocessing_distributed: True
name                       : mobilenet_v2_imagenet_mixed_int
nncf_config                : {'model': 'mobilenet_v2', 'pretrained': True, 'input_info': {'sample_size': [2, 3, 224, 224]}, 'num_classes': 1000, 'batch_size': 200, 'workers': 6, 'multiprocessing_distributed': True, 'optimizer': {'base_lr': 0.00031, 'schedule_type': 'plateau', 'type': 'Adam', 'schedule_params': {'threshold': 0.1, 'cooldown': 3}, 'weight_decay': 1e-05}, 'target_device': 'VPU', 'compression': {'algorithm': 'quantization', 'quantize_inputs': True, 'initializer': {'precision': {'type': 'hawq', 'bits': [4, 8], 'compression_ratio': 1.5}}}, 'log_dir': 'runs/mobilenet_v2_imagenet_mixed_int/2021-09-27__18-02-55'}
num_classes                : 1000
optimizer                  : {'base_lr': 0.00031, 'schedule_type': 'plateau', 'type': 'Adam', 'schedule_params': {'threshold': 0.1, 'cooldown': 3}, 'weight_decay': 1e-05}
pretrained                 : True
print_freq                 : 10
print_step                 : False
rank                       : 0
resuming_checkpoint_path   : None
save_freq                  : 5
seed                       : None
start_epoch                : 0
tb                         : <torch.utils.tensorboard.writer.SummaryWriter object at 0x7fa8d5ba1b38>
test_every_n_epochs        : 1
to_onnx                    : mixed.onnx
weights                    : None
workers                    : 6
world_size                 : 1
Loading model: mobilenet_v2
WARNING:nncf:Graphviz is not installed - only the .dot model visualization format will be used. Install pygraphviz into your Python environment and graphviz system-wide to enable PNG rendering.
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[1]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[1]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[1]/Sequential[conv]/Conv2d[1] by MobileNetV2/Sequential[features]/InvertedResidual[1]/Sequential[conv]/NNCFConv2d[1]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[2]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[2]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[2]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[2]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[2]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[2]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[3]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[3]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[3]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[3]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[3]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[3]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[4]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[4]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[4]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[4]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[4]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[4]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[5]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[5]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[5]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[5]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[5]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[5]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[6]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[6]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[6]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[6]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[6]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[6]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[7]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[7]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[7]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[7]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[7]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[7]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[8]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[8]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[8]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[8]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[8]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[8]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[9]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[9]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[9]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[9]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[9]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[9]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[10]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[10]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[10]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[10]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[10]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[10]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[11]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[11]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[11]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[11]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[11]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[11]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[12]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[12]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[12]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[12]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[12]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[12]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[13]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[13]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[13]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[13]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[13]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[13]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[14]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[14]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[14]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[14]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[14]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[14]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[15]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[15]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[15]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[15]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[15]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[15]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[16]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[16]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[16]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[16]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[16]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[16]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[17]/Sequential[conv]/ConvBNReLU[0]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[17]/Sequential[conv]/ConvBNReLU[0]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[17]/Sequential[conv]/ConvBNReLU[1]/Conv2d[0] by MobileNetV2/Sequential[features]/InvertedResidual[17]/Sequential[conv]/ConvBNReLU[1]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/InvertedResidual[17]/Sequential[conv]/Conv2d[2] by MobileNetV2/Sequential[features]/InvertedResidual[17]/Sequential[conv]/NNCFConv2d[2]
INFO:nncf:Wrapping module MobileNetV2/Sequential[features]/ConvBNReLU[18]/Conv2d[0] by MobileNetV2/Sequential[features]/ConvBNReLU[18]/NNCFConv2d[0]
INFO:nncf:Wrapping module MobileNetV2/Sequential[classifier]/Linear[1] by MobileNetV2/Sequential[classifier]/NNCFLinear[1]
WARNING:nncf:Initializer section not specified for quantization algorithm in NNCF config and quantization init args not supplied - the necessary parameters are not specified to run the quantizer range initialization algorithm
Traceback (most recent call last):
  File "/root/nncf/nncf/torch/quantization/algo.py", line 490, in _parse_precision_init_params
    precision_init_args = self.config.get_extra_struct(QuantizationPrecisionInitArgs)
  File "/root/nncf/nncf/config/config.py", line 60, in get_extra_struct
    return self.__nncf_extra_structs[struct_cls.get_id()]
KeyError: 'quantization_precision_init_args'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/nncf/examples/torch/classification/main.py", line 666, in <module>
    main(sys.argv[1:])
  File "/root/nncf/examples/torch/classification/main.py", line 126, in main
    start_worker(main_worker, config)
  File "/root/nncf/examples/torch/common/execution.py", line 102, in start_worker
    main_worker(current_gpu=config.gpu_id, config=config)
  File "/root/nncf/examples/torch/classification/main.py", line 210, in main_worker
    compression_ctrl, model = create_compressed_model(model, nncf_config, compression_state)
  File "/root/nncf/nncf/torch/model_creation.py", line 141, in create_compressed_model
    builder = create_compression_algorithm_builder(config, should_init)
  File "/root/nncf/nncf/torch/model_creation.py", line 195, in create_compression_algorithm_builder
    builder = next(iter(algo_builder_classes))(config, should_init=should_init)
  File "/root/nncf/nncf/torch/quantization/algo.py", line 432, in __init__
    self._parse_init_params()
  File "/root/nncf/nncf/torch/quantization/algo.py", line 477, in _parse_init_params
    self._algo_config.get('initializer', {}))
  File "/root/nncf/nncf/torch/quantization/algo.py", line 496, in _parse_precision_init_params
    'class') from e
ValueError: Specified non-manual precision initialization in the NNCF config, but the initializing data loader and loss criterion are not provided as an extra struct. Refer to `NNCFConfig.register_extra_structs` and the `QuantizationPrecisionInitArgs` class

Process finished with exit code 1
`

I have just contacted nncf, what is the cause of the above error, I hope to get an answer

**Comment by ljaljushkin** [comment]
Greetings @lianxintao!

There're 2 ways to export mixed-precision quantized model:
1.  At first, run sample in a train mode. It would train compression and save NNCF checkpoint.
(Please note, it's a default mode in the sample, would be equal to the same command line with `-m train` added).
`
python main.py --config=configs/quantization/mobilenet_v2_imagenet_mixed_int_hawq.json
`
Then run sample in the export mode with specifying path to the NNCF checkpoint to load weights and restore compression (locations of the quantization operations with their parameters, particularly).
`
python main.py --config=configs/quantization/mobilenet_v2_imagenet_mixed_int_hawq.json --resume resnet50_imagenet_mixed_int_best.pth --to-onnx model.onnx -m export
`
2. You could train and export the last state to ONNX in a single run.
`
python main.py --config=configs/quantization/mobilenet_v2_imagenet_mixed_int_hawq.json --to-onnx model.onnx -m train export
`
Please note, that now `-m` has 2 arguments: `train` and `export`.

Unfortunately, the second approach is not working now because of bug in the classification sample with handling `--to-onnx` option.
I will fix it shortly. While it's not fixed, you can use the first approach.

Your command line runs sample in a default mode - train. In that case, export shouldn't happen and path to onnx is an redundant argument here.

**Comment by lianxintao** [comment]
It worked . Thank you for your reply.
